# Acknowledgements {-}

This text was assembled using various pages from [Wikipedia](https://www.wikipedia.org) as my source. I copied text passages from many Wikipedia pages, remixed, edited, adapted and suplemented it with my own words to assemble the chapters of this text. I make this text available as an open educational resource under [Creative Commons Attribution-Share Alike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/deed.en) United States License ([same](https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License) as Wikipedia) for others to do as I did and freely copy, remix, edit and adapt as required. Illustrations with associated hyperlinks are from Wikimedia Commons, which should be consulted for copyright details. Pictures and illustrations that I generated myself are subject to the [Creative Commons Attribution-Share Alike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/deed.en) United States License. I want to thank all the contributors and supporters of Wikipedia for making it possible and keeping it relevant. I am grateful for the support provided by the Salem State University's OER initiative.
