# The Autonomic Nervous System

The autonomic nervous system (ANS), formerly the vegetative nervous system, is a division of the peripheral nervous system that supplies smooth muscle and glands, and thus influences the function of internal organs. The autonomic nervous system is a control system that acts largely unconsciously and regulates bodily functions such as the heart rate, digestion, respiratory rate, pupillary response, urination, and sexual arousal. This system is the primary mechanism in control of the fight-or-flight response.

Within the brain, the autonomic nervous system is regulated by the hypothalamus. Autonomic functions include control of respiration, cardiac regulation (the cardiac control center), vasomotor activity (the vasomotor center), and certain reflex actions such as coughing, sneezing, swallowing and vomiting. Those are then subdivided into other areas and are also linked to ANS subsystems and nervous systems external to the brain. The hypothalamus, just above the brain stem, acts as an integrator for autonomic functions, receiving ANS regulatory input from the limbic system to do so.

The autonomic nervous system has three branches: the sympathetic nervous system, the parasympathetic nervous system and the enteric nervous system. Some textbooks do not include the enteric nervous system as part of this system. The sympathetic nervous system is often considered the "fight or flight" system, while the parasympathetic nervous system is often considered the "rest and digest" or "feed and breed" system. In many cases, both of these systems have "opposite" actions where one system activates a physiological response and the other inhibits it. An older simplification of the sympathetic and parasympathetic nervous systems as "excitatory" and "inhibitory" was overturned due to the many exceptions found. A more modern characterization is that the sympathetic nervous system is a "quick response mobilizing system" and the parasympathetic is a "more slowly activated dampening system", but even this has exceptions, such as in sexual arousal and orgasm, wherein both play a role.

There are inhibitory and excitatory synapses between neurons. Relatively recently, a third subsystem of neurons that have been named non-noradrenergic, non-cholinergic transmitters (because they use nitric oxide as a neurotransmitter) have been described and found to be integral in autonomic function, in particular in the gut and the lungs.

Although the ANS is also known as the visceral nervous system, the ANS is only connected with the motor side. Most autonomous functions are involuntary but they can often work in conjunction with the somatic nervous system which provides voluntary control.

The autonomic nervous system is divided into the sympathetic nervous system and parasympathetic nervous system. The sympathetic division emerges from the spinal cord in the thoracic and lumbar areas, terminating around L2-3. The parasympathetic division has craniosacral “outflow”, meaning that the neurons begin at the cranial nerves (specifically the oculomotor nerve, facial nerve, glossopharyngeal nerve and vagus nerve) and sacral (S2-S4) spinal cord.

The autonomic nervous system is unique in that it requires a sequential two-neuron efferent pathway; the preganglionic neuron must first synapse onto a postganglionic neuron before innervating the target organ. The preganglionic, or first, neuron will begin at the “outflow” and will synapse at the postganglionic, or second, neuron's cell body. The postganglionic neuron will then synapse at the target organ.

```{r autonomic, out.width='75%', echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(printr)        
library(kableExtra)

setwd("~/Dropbox/R/neuroanatomy-text-master")

comparison <-  as_tibble(read.csv("data/macroglia.csv"))

knitr::kable(comparison, col.names = c("Target organ/system", "Parasympathetic", "Sympathetic"), digits = 2, align = 'lll', longtable = TRUE, booktabs = TRUE, caption = "Effects of the parasympathetic and sympathetic branches of the autonomic system on their target organs.") %>% kable_styling(latex_options = c("striped", "scale_down", "hold_position")) %>% column_spec(1, width = "5em") %>% column_spec(2, width = "5em") %>% column_spec(3, width = "40em") %>% collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") 
```

## Sympathetic division

There are two kinds of neurons involved in the transmission of any signal through the sympathetic system: pre-ganglionic and post-ganglionic. The shorter preganglionic neurons originate in the thoracolumbar division of the spinal cord specifically at T1 to L2~L3, and travel to a ganglion, often one of the paravertebral ganglia, where they synapse with a postganglionic neuron. From there, the long postganglionic neurons extend across most of the body.

At the synapses within the ganglia, preganglionic neurons release acetylcholine, a neurotransmitter that activates nicotinic acetylcholine receptors on postganglionic neurons. In response to this stimulus, the postganglionic neurons release norepinephrine, which activates adrenergic receptors that are present on the peripheral target tissues. The activation of target tissue receptors causes the effects associated with the sympathetic system. However, there are three important exceptions:

Postganglionic neurons of sweat glands release acetylcholine for the activation of muscarinic receptors, except for areas of thick skin, the palms and the plantar surfaces of the feet, where norepinephrine is released and acts on adrenergic receptors.
Chromaffin cells of the adrenal medulla are analogous to post-ganglionic neurons; the adrenal medulla develops in tandem with the sympathetic nervous system and acts as a modified sympathetic ganglion. Within this endocrine gland, pre-ganglionic neurons synapse with chromaffin cells, triggering the release of two transmitters: a small proportion of norepinephrine, and more substantially, epinephrine. The synthesis and release of epinephrine as opposed to norepinephrine is another distinguishing feature of chromaffin cells compared to postganglionic sympathetic neurons.
Postganglionic sympathetic nerves terminating in the kidney release dopamine, which acts on dopamine D1 receptors of blood vessels to control how much blood the kidney filters. Dopamine is the immediate metabolic precursor to norepinephrine, but is nonetheless a distinct signaling molecule.
Organization

The sympathetic nervous system extends from the thoracic to lumbar vertebrae and has connections with the thoracic, abdominal, and pelvic plexuses.
Sympathetic nerves arise from near the middle of the spinal cord in the intermediolateral nucleus of the lateral grey column, beginning at the first thoracic vertebra of the vertebral column and are thought to extend to the second or third lumbar vertebra. Because its cells begin in the thoracolumbar division – the thoracic and lumbar regions of the spinal cord, the sympathetic nervous system is said to have a thoracolumbar outflow. Axons of these nerves leave the spinal cord through the anterior root. They pass near the spinal (sensory) ganglion, where they enter the anterior rami of the spinal nerves. However, unlike somatic innervation, they quickly separate out through white rami connectors (so called from the shiny white sheaths of myelin around each axon) that connect to either the paravertebral (which lie near the vertebral column) or prevertebral (which lie near the aortic bifurcation) ganglia extending alongside the spinal column.

To reach target organs and glands, the axons must travel long distances in the body, and, to accomplish this, many axons relay their message to a second cell through synaptic transmission. The ends of the axons link across a space, the synapse, to the dendrites of the second cell. The first cell (the presynaptic cell) sends a neurotransmitter across the synaptic cleft where it activates the second cell (the postsynaptic cell). The message is then carried to the final destination.

Presynaptic nerves' axons terminate in either the paravertebral ganglia or prevertebral ganglia. There are four different paths an axon can take before reaching its terminal. In all cases, the axon enters the paravertebral ganglion at the level of its originating spinal nerve. After this, it can then either synapse in this ganglion, ascend to a more superior or descend to a more inferior paravertebral ganglion and synapse there, or it can descend to a prevertebral ganglion and synapse there with the postsynaptic cell.

The postsynaptic cell then goes on to innervate the targeted end effector (i.e. gland, smooth muscle, etc.). Because paravertebral and prevertebral ganglia are relatively close to the spinal cord, presynaptic neurons are generally much shorter than their postsynaptic counterparts, which must extend throughout the body to reach their destinations.

A notable exception to the routes mentioned above is the sympathetic innervation of the suprarenal (adrenal) medulla. In this case, presynaptic neurons pass through paravertebral ganglia, on through prevertebral ganglia and then synapse directly with suprarenal tissue. This tissue consists of cells that have pseudo-neuron like qualities in that when activated by the presynaptic neuron, they will release their neurotransmitter (epinephrine) directly into the bloodstream.

In the sympathetic nervous system and other components of the peripheral nervous system, these synapses are made at sites called ganglia. The cell that sends its fiber is called a preganglionic cell, while the cell whose fiber leaves the ganglion is called a postganglionic cell. As mentioned previously, the preganglionic cells of the sympathetic nervous system are located between the first thoracic segment and third lumbar segments of the spinal cord. Postganglionic cells have their cell bodies in the ganglia and send their axons to target organs or glands.

The ganglia include not just the sympathetic trunks but also the cervical ganglia (superior, middle and inferior), which send sympathetic nerve fibers to the head and thorax organs, and the celiac and mesenteric ganglia, which send sympathetic fibers to the gut.

## Parasympathetic division

The parasympathetic nerves are autonomic or visceral  branches of the peripheral nervous system (PNS). Parasympathetic nerve supply arises through three primary areas:

Certain cranial nerves in the cranium, namely the preganglionic parasympathetic nerves (CN III, CN VII, and CN IX) usually arise from specific nuclei in the central nervous system (CNS) and synapse at one of four parasympathetic ganglia: ciliary, pterygopalatine, otic, or submandibular. From these four ganglia the parasympathetic nerves complete their journey to target tissues via trigeminal branches (ophthalmic nerve, maxillary nerve, mandibular nerve).
The vagus nerve does not participate in these cranial ganglia as most of its parasympathetic fibers are destined for a broad array of ganglia on or near thoracic viscera (esophagus, trachea, heart, lungs) and abdominal viscera (stomach, pancreas, liver, kidneys, small intestine, and about half of the large intestine). The vagus innervation ends at the junction between the midgut and hindgut, just before the splenic flexure of the transverse colon.
The pelvic splanchnic efferent preganglionic nerve cell bodies reside in the lateral gray horn of the spinal cord at the T12-L1 vertebral levels (the spinal cord terminates at the L1-L2 vertebrae with the conus medullaris), and their axons exit the vertebral column as S2-S4 spinal nerves through the sacral foramina. Their axons continue away from the CNS to synapse at an autonomic ganglion. The parasympathetic ganglion where these preganglionic neurons synapse will be close to the organ of innervation. This differs from the sympathetic nervous system, where synapses between pre- and post-ganglionic efferent nerves in general occur at ganglia that are farther away from the target organ.
As in the sympathetic nervous system, efferent parasympathetic nerve signals are carried from the central nervous system to their targets by a system of two neurons. The first neuron in this pathway is referred to as the preganglionic or presynaptic neuron. Its cell body sits in the central nervous system and its axon usually extends to synapse with the dendrites of a postganglionic neuron somewhere else in the body. The axons of presynaptic parasympathetic neurons are usually long, extending from the CNS into a ganglion that is either very close to or embedded in their target organ. As a result, the postsynaptic parasympathetic nerve fibers are very short.:42

Cranial nerves
The oculomotor nerve is responsible for a number of parasympathetic functions related to the eye. The oculomotor PNS fibers originate in the Edinger-Westphal nucleus in the central nervous system and travel through the superior orbital fissure to synapse in the ciliary ganglion located just behind the orbit (eye). From the ciliary ganglion the postganglionic parasympathetic fibers leave via short ciliary nerve fibers, a continuation of the nasociliary nerve (a branch of ophthalmic division of the trigeminal nerve (CN V1)). The short ciliary nerves innervate the orbit to control the ciliary muscle (responsible for accommodation) and the iris sphincter muscle, which is responsible for miosis or constriction of the pupil (in response to light or accommodation). There are two motors that are part of the oculomotor nerve known as the somatic motor and visceral motor. The somatic motor is responsible for moving the eye in precise motions and for keeping the eye fixated on an object. The visceral motor helps constrict the pupil.

The parasympathetic aspect of the facial nerve controls secretion of the sublingual and submandibular salivary glands, the lacrimal gland, and the glands associated with the nasal cavity. The preganglionic fibers originate within the CNS in the superior salivatory nucleus and leave as the intermediate nerve (which some consider a separate cranial nerve altogether) to connect with the facial nerve just distal (further out) to it surfacing the central nervous system. Just after the facial nerve geniculate ganglion (general sensory ganglion) in the temporal bone, the facial nerve gives off two separate parasympathetic nerves. The first is the greater petrosal nerve and the second is the chorda tympani. The greater petrosal nerve travels through the middle ear and eventually combines with the deep petrosal nerve (sympathetic fibers) to form the nerve of the pterygoid canal. The parasympathetic fibers of the nerve of the pterygoid canal synapse at the pterygopalatine ganglion, which is closely associated with the maxillary division of the trigeminal nerve (CN V2). The postganglionic parasympathetic fibers leave the pterygopalatine ganglion in several directions. One division leaves on the zygomatic division of CN V2 and travels on a communicating branch to unite with the lacrimal nerve (branch of the ophthalmic nerve of CN V1) before synapsing at the lacrimal gland. These parasympathetic to the lacrimal gland control tear production.

A separate group of parasympathetic leaving from the pterygopalatine ganglion are the descending palatine nerves (CN V2 branch), which include the greater and lesser palatine nerves. The greater palatine parasympathetic synapse on the hard palate and regulate mucus glands located there. The lesser palatine nerve synapses at the soft palate and controls sparse taste receptors and mucus glands. Yet another set of divisions from the pterygopalatine ganglion are the posterior, superior, and inferior lateral nasal nerves; and the nasopalatine nerves (all branches of CN V2, maxillary division of the trigeminal nerve) that bring parasympathetic innervation to glands of the nasal mucosa. The second parasympathetic branch that leaves the facial nerve is the chorda tympani. This nerve carries secretomotor fibers to the submandibular and sublingual glands. The chorda tympani travels through the middle ear and attaches to the lingual nerve (mandibular division of trigeminal, CN V3). After joining the lingual nerve, the preganglionic fibers synapse at the submandibular ganglion and send postganglionic fibers to the sublingual and submandibular salivary glands.

The glossopharyngeal nerve has parasympathetic fibers that innervate the parotid salivary gland. The preganglionic fibers depart CN IX as the tympanic nerve and continue to the middle ear where they make up a tympanic plexus on the cochlear promontory of the mesotympanum. The tympanic plexus of nerves rejoin and form the lesser petrosal nerve and exit through the foramen ovale to synapse at the otic ganglion. From the otic ganglion postganglionic parasympathetic fibers travel with the auriculotemporal nerve (mandibular branch of trigeminal, CN V3) to the parotid salivary gland.

Vagus nerve
The vagus nerve, named after the Latin word vagus (because the nerve controls such a broad range of target tissues – vagus in Latin literally means "wandering"), has parasympathetic functions that originate in the dorsal nucleus of the vagus nerve and the nucleus ambiguus in the CNS. The vagus nerve is an unusual cranial parasympathetic in that it doesn't join the trigeminal nerve in order to get to its target tissues. Another peculiarity is that the vagus has an autonomic ganglion associated with it at approximately the level of C1 vertebra. The vagus gives no parasympathetic to the cranium. The vagus nerve is hard to track definitively due to its ubiquitous nature in the thorax and abdomen so the major contributions will be discussed. Several parasympathetic nerves come off the vagus nerve as it enters the thorax. One nerve is the recurrent laryngeal nerve, which becomes the inferior laryngeal nerve. From the left vagus nerve the recurrent laryngeal nerve hooks around the aorta to travel back up to the larynx and proximal esophagus while, from the right vagus nerve, the recurrent laryngeal nerve hooks around the right subclavian artery to travel back up to the same location as its counterpart. These different paths are a direct result of embryological development of the circulatory system. Each recurrent laryngeal nerve supplies the trachea and the esophagus with parasympathetic secretomotor innervation for glands associated with them (and other fibers that are not PN).

Another nerve that comes off the vagus nerves approximately at the level of entering the thorax are the cardiac nerves. These cardiac nerves go on to form cardiac and pulmonary plexuses around the heart and lungs. As the main vagus nerves continue into the thorax they become intimately linked with the esophagus and sympathetic nerves from the sympathetic trunks to form the esophageal plexus. This is very efficient as the major function of the vagus nerve from there on will be control of the gut smooth muscles and glands. As the esophageal plexus enter the abdomen through the esophageal hiatus anterior and posterior vagus trunks form. The vagus trunks then join with preaortic sympathetic ganglion around the aorta to disperse with the blood vessels and sympathetic nerves throughout the abdomen. The extent of the parasympathetic in the abdomen include the pancreas, kidneys, liver, gall bladder, stomach and gut tube. The vagus contribution of parasympathetic continues down the gut tube until the end of the midgut. The midgut ends two thirds of the way across the transverse colon near the splenic flexure.

Pelvic splanchnic nerves
The pelvic splanchnic nerves, S2-4, work in tandem to innervate the pelvic viscera. Unlike in the cranium, where one parasympathetic is in charge of one particular tissue or region, for the most part the pelvic splanchnics each contribute fibers to pelvic viscera by traveling to one or more plexuses before being dispersed to the target tissue. These plexuses are composed of mixed autonomic nerve fibers (parasympathetic and sympathetic) and include the vesical, prostatic, rectal, uterovaginal, and inferior hypogastric plexuses. The preganglionic neurons in the pathway do not synapse in a ganglion as in the cranium but rather in the walls of the tissues or organs that they innervate. The fiber paths are variable and each individual's autonomic nervous system in the pelvis is unique. The visceral tissues in the pelvis that the parasympathetic nerve pathway controls include those of the urinary bladder, ureters, urinary sphincter, anal sphincter, uterus, prostate, glands, vagina, and penis. Unconsciously, the parasympathetic will cause peristaltic movements of the ureters and intestines, moving urine from the kidneys into the bladder and food down the intestinal tract and, upon necessity, the parasympathetic will assist in excreting urine from the bladder or defecation. Stimulation of the parasympathetic will cause the detrusor muscle (urinary bladder wall) to contract and simultaneously relax the internal sphincter muscle between the bladder and the urethra, allowing the bladder to void. Also, parasympathetic stimulation of the internal anal sphincter will relax this muscle to allow defecation. There are other skeletal muscles involved with these processes but the parasympathetic plays a huge role in continence and bowel retention.

A study published in 2016, suggests that all sacral autonomic output may be sympathetic; indicating that the rectum, bladder and reproductive organs may only be innervated by the sympathetic nervous system. This suggestion is based on detailed analysis of 15 phenotypic and ontogenetic factors differentiating sympathetic from parasympathetic neurons in the mouse. Assuming that the reported findings most likely applies to other mammals as well, this perspective suggests a simplified, bipartite architecture of the autonomic nervous system, in which the parasympathetic nervous system receives input from cranial nerves exclusively and the sympathetic nervous system from thoracic to sacral spinal nerves.



The parasympathetic nervous system consists of cells with bodies in one of two locations: the brainstem (Cranial Nerves III, VII, IX, X) or the sacral spinal cord (S2, S3, S4). These are the preganglionic neurons, which synapse with postganglionic neurons in these locations:

Parasympathetic ganglia of the head: Ciliary (Cranial nerve III), Submandibular (Cranial nerve VII), Pterygopalatine (Cranial nerve VII), and Otic (Cranial nerve IX)
In or near the wall of an organ innervated by the Vagus (Cranial nerve X) or Sacral nerves (S2, S3, S4)
These ganglia provide the postganglionic neurons from which innervations of target organs follows. Examples are:

The postganglionic parasympathetic splanchnic (visceral) nerves
The vagus nerve, which passes through the thorax and abdominal regions innervating, among other organs, the heart, lungs, liver and stomach


The sensory arm is composed of primary visceral sensory neurons found in the peripheral nervous system (PNS), in cranial sensory ganglia: the geniculate, petrosal and nodose ganglia, appended respectively to cranial nerves VII, IX and X. These sensory neurons monitor the levels of carbon dioxide, oxygen and sugar in the blood, arterial pressure and the chemical composition of the stomach and gut content. They also convey the sense of taste and smell, which, unlike most functions of the ANS, is a conscious perception. Blood oxygen and carbon dioxide are in fact directly sensed by the carotid body, a small collection of chemosensors at the bifurcation of the carotid artery, innervated by the petrosal (IXth) ganglion. Primary sensory neurons project (synapse) onto “second order” visceral sensory neurons located in the medulla oblongata, forming the nucleus of the solitary tract (nTS), that integrates all visceral information. The nTS also receives input from a nearby chemosensory center, the area postrema, that detects toxins in the blood and the cerebrospinal fluid and is essential for chemically induced vomiting or conditional taste aversion (the memory that ensures that an animal that has been poisoned by a food never touches it again). All this visceral sensory information constantly and unconsciously modulates the activity of the motor neurons of the ANS.

Motor neurons of the autonomic nervous system are found in ‘’autonomic ganglia’’. Those of the parasympathetic branch are located close to the target organ whilst the ganglia of the sympathetic branch are located close to the spinal cord.

The sympathetic ganglia here, are found in two chains: the pre-vertebral and pre-aortic chains. The activity of autonomic ganglionic neurons is modulated by “preganglionic neurons” located in the central nervous system. Preganglionic sympathetic neurons are located in the spinal cord, at the thorax and upper lumbar levels. Preganglionic parasympathetic neurons are found in the medulla oblongata where they form visceral motor nuclei; the dorsal motor nucleus of the vagus nerve; the nucleus ambiguus, the salivatory nuclei, and in the sacral region of the spinal cord.

Function

Function of the autonomic nervous system 
Sympathetic and parasympathetic divisions typically function in opposition to each other. But this opposition is better termed complementary in nature rather than antagonistic. For an analogy, one may think of the sympathetic division as the accelerator and the parasympathetic division as the brake. The sympathetic division typically functions in actions requiring quick responses. The parasympathetic division functions with actions that do not require immediate reaction. The sympathetic system is often considered the "fight or flight" system, while the parasympathetic system is often considered the "rest and digest" or "feed and breed" system.

However, many instances of sympathetic and parasympathetic activity cannot be ascribed to "fight" or "rest" situations. For example, standing up from a reclining or sitting position would entail an unsustainable drop in blood pressure if not for a compensatory increase in the arterial sympathetic tonus. Another example is the constant, second-to-second, modulation of heart rate by sympathetic and parasympathetic influences, as a function of the respiratory cycles. In general, these two systems should be seen as permanently modulating vital functions, in usually antagonistic fashion, to achieve homeostasis. Higher organisms maintain their integrity via homeostasis which relies on negative feedback regulation which, in turn, typically depends on the autonomic nervous system. Some typical actions of the sympathetic and parasympathetic nervous systems are listed below.

Innervation
Autonomic nerves travel to organs throughout the body. Most organs receive parasympathetic supply by the vagus nerve and sympathetic supply by splanchnic nerves. The sensory part of the latter reaches the spinal column at certain spinal segments. Pain in any internal organ is perceived as referred pain, more specifically as pain from the dermatome corresponding to the spinal segment.

Sympathetic nervous system
Main article: Sympathetic nervous system
Promotes a fight-or-flight response, corresponds with arousal and energy generation, and inhibits digestion

Diverts blood flow away from the gastro-intestinal (GI) tract and skin via vasoconstriction
Blood flow to skeletal muscles and the lungs is enhanced (by as much as 1200% in the case of skeletal muscles)
Dilates bronchioles of the lung through circulating epinephrine, which allows for greater alveolar oxygen exchange
Increases heart rate and the contractility of cardiac cells (myocytes), thereby providing a mechanism for enhanced blood flow to skeletal muscles
Dilates pupils and relaxes the ciliary muscle to the lens, allowing more light to enter the eye and enhances far vision
Provides vasodilation for the coronary vessels of the heart
Constricts all the intestinal sphincters and the urinary sphincter
Inhibits peristalsis
Stimulates orgasm
Parasympathetic nervous system
Main article: Parasympathetic nervous system
The parasympathetic nervous system has been said to promote a "rest and digest" response, promotes calming of the nerves return to regular function, and enhancing digestion. Functions of nerves within the parasympathetic nervous system include:[citation needed]

Dilating blood vessels leading to the GI tract, increasing the blood flow.
Constricting the bronchiolar diameter when the need for oxygen has diminished
Dedicated cardiac branches of the vagus and thoracic spinal accessory nerves impart parasympathetic control of the heart (myocardium)
Constriction of the pupil and contraction of the ciliary muscles, facilitating accommodation and allowing for closer vision
Stimulating salivary gland secretion, and accelerates peristalsis, mediating digestion of food and, indirectly, the absorption of nutrients
Sexual. Nerves of the peripheral nervous system are involved in the erection of genital tissues via the pelvic splanchnic nerves 2–4. They are also responsible for stimulating sexual arousal.
Enteric nervous system
Main article: Enteric nervous system
The enteric nervous system is the intrinsic nervous system of the gastrointestinal system. It has been described as "the Second Brain of the Human Body". Its functions include:

Sensing chemical and mechanical changes in the gut
Regulating secretions in the gut
Controlling peristalsis and some other movements
Neurotransmitters
Main articles: Table of neurotransmitter actions in the ANS and Non-noradrenergic, non-cholinergic transmitter

A flow diagram showing the process of stimulation of adrenal medulla that makes it release adrenaline, that further acts on adrenoreceptors, indirectly mediating or mimicking sympathetic activity.
At the effector organs, sympathetic ganglionic neurons release noradrenaline (norepinephrine), along with other cotransmitters such as ATP, to act on adrenergic receptors, with the exception of the sweat glands and the adrenal medulla:

Acetylcholine is the preganglionic neurotransmitter for both divisions of the ANS, as well as the postganglionic neurotransmitter of parasympathetic neurons. Nerves that release acetylcholine are said to be cholinergic. In the parasympathetic system, ganglionic neurons use acetylcholine as a neurotransmitter to stimulate muscarinic receptors.
At the adrenal medulla, there is no postsynaptic neuron. Instead the presynaptic neuron releases acetylcholine to act on nicotinic receptors. Stimulation of the adrenal medulla releases adrenaline (epinephrine) into the bloodstream, which acts on adrenoceptors, thereby indirectly mediating or mimicking sympathetic activity.
