# The Central Nervous System

The central nervous system (CNS) is the part of the nervous system consisting of the brain and spinal cord. The CNS is so named because it integrates the received information and coordinates and influences the activity of all parts of the bodies of bilaterally symmetric animals—that is, all multicellular animals except sponges and radially symmetric animals such as jellyfish—and it contains the majority of the nervous system. Many consider the retina and the optic nerve (cranial nerve II), as well as the olfactory nerves (cranial nerve I) and olfactory epithelium as parts of the CNS, synapsing directly on brain tissue without intermediate ganglia. As such, the olfactory epithelium is the only central nervous tissue in direct contact with the environment, which opens up for therapeutic treatments.  The CNS is contained within the dorsal body cavity, with the brain housed in the cranial cavity and the spinal cord in the spinal canal. In vertebrates, the brain is protected by the skull, while the spinal cord is protected by the vertebrae. The brain and spinal cord are both enclosed in the meninges. Within the CNS, the interneuronal space is filled with a large amount of supporting non-nervous cells called neuroglia or glia from the Greek for "glue".

The CNS consists of the two major structures: the brain and spinal cord. The brain is encased in the skull, and protected by the cranium. The spinal cord is continuous with the brain and lies caudally to the brain. It is protected by the vertebrae. The spinal cord reaches from the base of the skull, continues through or starting below the foramen magnum, and terminates roughly level with the first or second lumbar vertebra, occupying the upper sections of the vertebral canal.

Microscopically, there are differences between the neurons and tissue of the CNS and the peripheral nervous system (PNS). The CNS is composed of white and gray matter. This can also be seen macroscopically on brain tissue. The white matter consists of axons and oligodendrocytes, while the gray matter consists of neurons and unmyelinated fibers. Both tissues include a number of glial cells (although the white matter contains more), which are often referred to as supporting cells of the CNS. Different forms of glial cells have different functions, some acting almost as scaffolding for neuroblasts to climb during neurogenesis such as bergmann glia, while others such as microglia are a specialized form of macrophage, involved in the immune system of the brain as well as the clearance of various metabolites from the brain tissue. Astrocytes may be involved with both clearance of metabolites as well as transport of fuel and various beneficial substances to neurons from the capillaries of the brain. Upon CNS injury astrocytes will proliferate, causing gliosis, a form of neuronal scar tissue, lacking in functional neurons.

The brain (cerebrum as well as midbrain and hindbrain) consists of a cortex, composed of neuron-bodies constituting gray matter, while internally there is more white matter that form tracts and commissures. Apart from cortical gray matter there is also subcortical gray matter making up a large number of different nuclei.

The human brain is the central organ of the human nervous system, and with the spinal cord makes up the central nervous system. The brain consists of the cerebrum, the brainstem and the cerebellum. It controls most of the activities of the body, processing, integrating, and coordinating the information it receives from the sense organs, and making decisions as to the instructions sent to the rest of the body. The brain is contained in, and protected by, the skull bones of the head.

The cerebrum is the largest part of the human brain. It is divided into two cerebral hemispheres. The cerebral cortex is an outer layer of grey matter, covering the core of white matter. The cortex is split into the neocortex and the much smaller allocortex. The neocortex is made up of six neuronal layers, while the allocortex has three or four. Each hemisphere is conventionally divided into four lobes – the frontal, temporal, parietal, and occipital lobes. The frontal lobe is associated with executive functions including self-control, planning, reasoning, and abstract thought, while the occipital lobe is dedicated to vision. Within each lobe, cortical areas are associated with specific functions, such as the sensory, motor and association regions. Although the left and right hemispheres are broadly similar in shape and function, some functions are associated with one side, such as language in the left and visual-spatial ability in the right. The hemispheres are connected by commissural nerve tracts, the largest being the corpus callosum.

The cerebrum is connected by the brainstem to the spinal cord. The brainstem consists of the midbrain, the pons, and the medulla oblongata. The cerebellum is connected to the brainstem by pairs of tracts. Within the cerebrum is the ventricular system, consisting of four interconnected ventricles in which cerebrospinal fluid is produced and circulated. Underneath the cerebral cortex are several important structures, including the thalamus, the epithalamus, the pineal gland, the hypothalamus, the pituitary gland, and the subthalamus; the limbic structures, including the amygdala and the hippocampus; the claustrum, the various nuclei of the basal ganglia; the basal forebrain structures, and the three circumventricular organs. The cells of the brain include neurons and supportive glial cells. There are more than 86 billion neurons in the brain, and a more or less equal number of other cells. Brain activity is made possible by the interconnections of neurons and their release of neurotransmitters in response to nerve impulses. Neurons connect to form neural pathways, neural circuits, and elaborate network systems. The whole circuitry is driven by the process of neurotransmission.

The brain is protected by the skull, suspended in cerebrospinal fluid, and isolated from the bloodstream by the blood–brain barrier. However, the brain is still susceptible to damage, disease, and infection. Damage can be caused by trauma, or a loss of blood supply known as a stroke. The brain is susceptible to degenerative disorders, such as Parkinson's disease, dementias including Alzheimer's disease, and multiple sclerosis. Psychiatric conditions, including schizophrenia and clinical depression, are thought to be associated with brain dysfunctions. The brain can also be the site of tumours, both benign and malignant; these mostly originate from other sites in the body.

The cerebrum, consisting of the cerebral hemispheres, forms the largest part of the brain and overlies the other brain structures. The outer region of the hemispheres, the cerebral cortex, is grey matter, consisting of cortical layers of neurons. Each hemisphere is divided into four main lobes – the frontal lobe, parietal lobe, temporal lobe, and occipital lobe. Three other lobes are included by some sources which are a central lobe, a limbic lobe, and an insular lobe. The central lobe comprises the precentral gyrus and the postcentral gyrus and is included since it forms a distinct functional role.

The brainstem, resembling a stalk, attaches to and leaves the cerebrum at the start of the midbrain area. The brainstem includes the midbrain, the pons, and the medulla oblongata. Behind the brainstem is the cerebellum (Latin: little brain).

The cerebrum, brainstem, cerebellum, and spinal cord are covered by three membranes called meninges. The membranes are the tough dura mater; the middle arachnoid mater and the more delicate inner pia mater. Between the arachnoid mater and the pia mater is the subarachnoid space and subarachnoid cisterns, which contain the cerebrospinal fluid. The outermost membrane of the cerebral cortex is the basement membrane of the pia mater called the glia limitans and is an important part of the blood–brain barrier. The living brain is very soft, having a gel-like consistency similar to soft tofu. The cortical layers of neurons constitute much of the cerebral grey matter, while the deeper subcortical regions of myelinated axons, make up the white matter. he white matter of the brain makes up about half of the total brain volume.

## The Meninges

The meninges (from Ancient Greek: μῆνιγξ, romanized: mēninx, lit. 'membrane', adjectival: meningeal) are the three membranes that envelop the brain and spinal cord. In mammals, the meninges are the dura mater, the arachnoid mater, and the pia mater. Cerebrospinal fluid is located in the subarachnoid space between the arachnoid mater and the pia mater. The primary function of the meninges is to protect the central nervous system.

### Dura mater

The dura mater (Latin: tough mother) (also rarely called meninx fibrosa or pachymeninx) is a thick, durable membrane, closest to the skull and vertebrae. The dura mater, the outermost part, is a loosely arranged, fibroelastic layer of cells, characterized by multiple interdigitating cell processes, no extracellular collagen [source?], and significant extracellular spaces. The middle region is a mostly fibrous portion. It consists of two layers: the endosteal layer, which lies closest to the skull, and the inner meningeal layer, which lies closer to the brain. It contains larger blood vessels that split into the capillaries in the pia mater. It is composed of dense fibrous tissue, and its inner surface is covered by flattened cells like those present on the surfaces of the pia mater and arachnoid mater. The dura mater is a sac that envelops the arachnoid mater and surrounds and supports the large dural sinuses carrying blood from the brain toward the heart.

The dura has four areas of infolding:

* Falx cerebri, the largest, sickle-shaped; separates the cerebral hemispheres. Starts from the frontal crest of frontal bone and the crista galli running to the internal occipital protuberance.
* Tentorium cerebelli, the second largest, crescent-shaped; separates the occipital lobes from cerebellum. The falx cerebri attaches to it giving a tentlike appearance.
* Falx cerebelli, vertical infolding; lies inferior to the tentorium cerebelli, separating the cerebellar hemispheres.
* Diaphragma sellae, smallest infolding; covers the pituitary gland and sella turcica.

### Arachnoid mater

The middle element of the meninges is the arachnoid mater, so named because of its spider web-like appearance. It cushions the central nervous system. This thin, transparent membrane is composed of fibrous tissue and, like the pia mater, is covered by flat cells also thought to be impermeable to fluid.

The shape of the arachnoid does not follow the convolutions of the surface of the brain and so looks like a loosely fitting sac. In particular, in the region of the brain a large number of fine filaments called arachnoid trabeculae pass from the arachnoid through the subarachnoid space to blend with the tissue of the pia mater. The arachnoid is composed of an outermost portion (arachnoid barrier cell layer) with tightly packed cells and no extracellular collagen; that is why it is considered to represent an effective morphological and physiological meningeal barrier between the cerebrospinal fluid and subarachnoid space and the blood circulation in the dura.

The arachnoid barrier layer is characterized by a distinct continuous basal lamina on its inner surface toward the innermost collagenous portion of the arachnoid reticular layer.

### Pia mater

The pia mater (Latin: tender mother) is a very delicate membrane. It is the meningeal envelope that firmly adheres to the surface of the brain and spinal cord, following all of the brain's contours (the gyri and sulci). It is a very thin membrane composed of fibrous tissue covered on its outer surface by a sheet of flat cells thought to be impermeable to fluid. The pia mater is pierced by blood vessels to the brain and spinal cord, and its capillaries nourish the brain.

The arachnoid and pia mater together are sometimes called the leptomeninges, literally "thin meninges" (Greek: λεπτός "leptos"—"thin"). Acute meningococcal meningitis can lead to an exudate within the leptomeninges along the surface of the brain. Because the arachnoid is connected to the pia by cob-web like strands, it is structurally continuous with the pia, hence the name pia-arachnoid or leptomeninges. They are responsible for the production of beta-trace protein (prostaglandin D2 synthase), a major cerebrospinal fluid protein.

### Subarachnoid spaces

The subarachnoid space is the space that normally exists between the arachnoid and the pia mater, which is filled with cerebrospinal fluid, and continues down the spinal cord. Spaces are formed from openings at different points along the subarachnoid space; these are the subarachnoid cisterns, which are filled with cerebrospinal fluid.

The dura mater is attached to the skull, whereas in the spinal cord, the dura mater is separated from the vertebrae by a space called the epidural space, which contains fat and blood vessels. The arachnoid is attached to the dura mater, while the pia mater is attached to the central nervous system tissue. When the dura mater and the arachnoid separate through injury or illness, the space between them is the subdural space. There is a subpial space underneath the pia mater that separates it from the glia limitans.

## The Blood-Brain-Barrier

The blood–brain barrier (BBB) is a highly selective semipermeable border that separates the circulating blood from the brain and extracellular fluid in the central nervous system (CNS). The blood-brain barrier is formed by endothelial cells of the capillary wall, astrocyte end-feet ensheathing the capillary, and pericytes embedded in the capillary basement membrane. This system allows the passage of some molecules by passive diffusion, as well as the selective transport of molecules such as glucose, water and amino acids that are crucial to neural function.

Specialized structures participating in sensory and secretory integration within neural circuits—the circumventricular organs and choroid plexus—do not have a blood-brain barrier.

The blood-brain barrier restricts the passage of pathogens, the diffusion of solutes in the blood, and large or hydrophilic molecules into the cerebrospinal fluid (CSF), while allowing the diffusion of hydrophobic molecules (O2, CO2, hormones) and small polar molecules. Cells of the barrier actively transport metabolic products such as glucose across the barrier using specific transport proteins.

Technically, the BBB is a shorthand for the Blood-CNS barrier, which has two parts: the Blood-Brain portion and the Blood-Spinal Cord Barrier portion. The two parts are often breached simultaneously, but may be independently breached.

The blood-brain barrier results from the selectivity of the tight junctions between endothelial cells in CNS vessels, which restricts the passage of solutes. At the interface between blood and the brain, endothelial cells are stitched together by these tight junctions, which are composed of smaller subunits, frequently biochemical dimers, that are transmembrane proteins such as occludin, claudins, junctional adhesion molecule (JAM), or ESAM, for example. Each of these transmembrane proteins is anchored into the endothelial cells by another protein complex that includes ZO-1 and associated proteins.

The blood-brain barrier is composed of high-density cells restricting passage of substances from the bloodstream much more than do the endothelial cells in capillaries elsewhere in the body. Astrocyte cell projections called astrocytic feet (also known as "glia limitans") surround the endothelial cells of the BBB, providing biochemical support to those cells. The BBB is distinct from the quite similar blood-cerebrospinal fluid barrier, which is a function of the choroidal cells of the choroid plexus, and from the blood-retinal barrier, which can be considered a part of the whole realm of such barriers.

Several areas of the human brain are not on the brain side of the BBB. Some examples of this include the circumventricular organs, the roof of the third and fourth ventricles, capillaries in the pineal gland on the roof of the diencephalon and the pineal gland. The pineal gland secretes the hormone melatonin "directly into the systemic circulation", thus melatonin is not affected by the blood-brain barrier.

The blood-brain barrier acts effectively to protect the brain from circulating pathogens. Accordingly, blood-borne infections of the brain are rare. Infections of the brain that do occur are often difficult to treat. Antibodies are too large to cross the blood-brain barrier, and only certain antibiotics are able to pass. In some cases, a drug has to be administered directly into the cerebrospinal fluid (CSF) where it can enter the brain by crossing the blood-cerebrospinal fluid barrier.

The blood-brain barrier may become leaky in select neurological diseases, such as amyotrophic lateral sclerosis, epilepsy, brain trauma and edema, and in systemic diseases, such as liver failure. The blood-brain barrier becomes more permeable during inflammation, allowing antibiotics and phagocytes to move across the BBB. However, this also allows bacteria and viruses to infiltrate the blood-brain barrier. Examples of pathogens that can traverse the blood-brain barrier include Toxoplasma gondii which causes toxoplasmosis, spirochetes like Borrelia (Lyme disease), Group B streptococci which causes meningitis in newborns, and Treponema pallidum which causes syphilis. Some of these harmful bacteria gain access by releasing cytotoxins like pneumolysin which have a direct toxic effect on brain microvascular endothelium and tight junctions.

### Circumventricular organs

Circumventricular organs (CVOs) are individual structures located adjacent to the fourth ventricle or third ventricle in the brain, and are characterized by dense capillary beds with permeable endothelial cells unlike those of the blood-brain barrier. Included among CVOs having highly permeable capillaries are the area postrema, subfornical organ, vascular organ of the lamina terminalis, median eminence, pineal gland, and three lobes of the pituitary gland.

Permeable capillaries of the sensory CVOs (area postrema, subfornical organ, vascular organ of the lamina terminalis) enable rapid detection of circulating signals in systemic blood, while those of the secretory CVOs (median eminence, pineal gland, pituitary lobes) facilitate transport of brain-derived signals into the circulating blood. Consequently, the CVO permeable capillaries are the point of bidirectional blood-brain communication for neuroendocrine function.

The border zones between brain tissue "behind" the blood-brain barrier and zones "open" to blood signals in certain CVOs contain specialized hybrid capillaries that are leakier than typical brain capillaries, but not as permeable as CVO capillaries. Such zones exist at the border of the area postrema—nucleus tractus solitarii (NTS), and median eminence—hypothalamic arcuate nucleus. These zones appear to function as rapid transit regions for brain structures involved in diverse neural circuits—like the NTS and arcuate nucleus—to rapidly control neurohumoral integration[clarification needed]. The permeable capillary zone shared between the median eminence and hypothalamic arcuate nucleus is augmented by wide pericapillary spaces, facilitating bidirectional flow of solutes between the two structures, and indicating that the median eminence is not only a secretory organ, but may also be a sensory CVO.

Paul Ehrlich was a bacteriologist studying staining, a procedure that is used in many microscopy studies to make fine biological structures visible using chemical dyes. As Ehrlich injected some of these dyes (notably the aniline dyes that were then widely used), the dye stained all of the organs of some kinds of animals except for their brains. At that time, Ehrlich attributed this lack of staining to the brain simply not picking up as much of the dye.

However, in a later experiment in 1913, Edwin Goldmann (one of Ehrlich's students) injected the dye directly into the cerebrospinal fluids of animal brains. He found then the brains did become dyed, but the rest of the body did not, demonstrating the existence of a compartmentalization between the two. At that time, it was thought that the blood vessels themselves were responsible for the barrier, since no obvious membrane could be found. The concept of the blood–brain barrier (then termed hematoencephalic barrier) was proposed by a Berlin physician, Lewandowsky, in 1900.

## The Cerebrum

The cerebrum is the largest part of the brain, and is divided into nearly symmetrical left and right hemispheres by a deep groove, the longitudinal fissure. Asymmetry between the lobes is noted as a petalia. The hemispheres are connected by five commissures that span the longitudinal fissure, the largest of these is the corpus callosum. Each hemisphere is conventionally divided into four main lobes; the frontal lobe, parietal lobe, temporal lobe, and occipital lobe, named according to the skull bones that overlie them. Each lobe is associated with one or two specialised functions though there is some functional overlap between them. The surface of the brain is folded into ridges (gyri) and grooves (sulci), many of which are named, usually according to their position, such as the frontal gyrus of the frontal lobe or the central sulcus separating the central regions of the hemispheres. There are many small variations in the secondary and tertiary folds.

### The cerebral cortex

The outer part of the cerebrum is the cerebral cortex, made up of grey matter arranged in layers. It is 2 to 4 millimetres (0.079 to 0.157 in) thick, and deeply folded to give a convoluted appearance. Beneath the cortex is the cerebral white matter. Based on the differences in laminar organization the cerebral cortex can be classified into two types, the large area of neocortex which has six cell layers, and the much smaller area of allocortex that has three or four layers:

* The neocortex is also known as the isocortex or neopallium and is the part of the mature cerebral cortex with six distinct layers. Examples of neocortical areas include the granular primary motor cortex, and the striate primary visual cortex. The neocortex has two subtypes, the true isocortex and the proisocortex which is a transitional region between the isocortex and the regions of the periallocortex.
* The allocortex is the part of the cerebral cortex with three or four layers, and has three subtypes, the paleocortex with three cortical laminae, the archicortex which has four or five, and a transitional area adjacent to the allocortex, the periallocortex. Examples of allocortex are the olfactory cortex and the hippocampus.

There is a transitional area between the neocortex and the allocortex called the paralimbic cortex, where layers 2, 3 and 4 are merged. This area incorporates the proisocortex of the neocortex and the periallocortex of the allocortex. In addition, the cerebral cortex may be classified into four lobes: the frontal lobe, temporal lobe, the parietal lobe, and the occipital lobe, named from their overlying bones of the skull.The largest part of the cerebral cortex is the neocortex, which has six neuronal layers. The rest of the cortex is of allocortex, which has three or four layers.

The six cortical layers of the neocortex each contain a characteristic distribution of different neurons and their connections with other cortical and subcortical regions. There are direct connections between different cortical areas and indirect connections via the thalamus. One of the clearest examples of cortical layering is the line of Gennari in the primary visual cortex. This is a band of whiter tissue that can be observed with the naked eye in the fundus of the calcarine sulcus of the occipital lobe. The line of Gennari is composed of axons bringing visual information from the thalamus into layer IV of the visual cortex.

Staining cross-sections of the cortex to reveal the position of neuronal cell bodies and the intracortical axon tracts allowed neuroanatomists in the early 20th century to produce a detailed description of the laminar structure of the cortex in different species. The cortex is mapped by divisions into fifty-two different functional areas known as Brodmann's areas. These areas are distinctly different when seen under a microscope. After the work of Korbinian Brodmann (1909) the neurons of the cerebral cortex are grouped into six main layers, from the outer pial surface to the inner white matter.

Layer I is the molecular layer, and contains few scattered neurons, including GABAergic rosehip neurons. Layer I consists largely of extensions of apical dendritic tufts of pyramidal neurons and horizontally oriented axons, as well as glial cells. During development Cajal-Retzius cells and subpial granular layer cells are present in this layer. Also, some spiny stellate cells can be found here. Inputs to the apical tufts are thought to be crucial for the feedback interactions in the cerebral cortex involved in associative learning and attention. While it was once thought that the input to layer I came from the cortex itself, it is now realized that layer I across the cerebral cortex mantle receives substantial input from matrix or M-type thalamus cells (in contrast to core or C-type that go to layer IV).

Layer II, the external granular layer, contains small pyramidal neurons and numerous stellate neurons.

Layer III, the external pyramidal layer, contains predominantly small and medium-size pyramidal neurons, as well as non-pyramidal neurons with vertically oriented intracortical axons; layers I through III are the main target of interhemispheric corticocortical afferents, and layer III is the principal source of corticocortical efferents.

Layer IV, the internal granular layer, contains different types of stellate and pyramidal cells, and is the main target of thalamocortical afferents from thalamus type C neurons (core-type ) as well as intra-hemispheric corticocortical afferents. The layers above layer IV are also referred to as supragranular layers (layers I-III), whereas the layers below are referred to as infragranular layers (layers V and VI).

Layer V, the internal pyramidal layer, contains large pyramidal neurons. Axons from these leave the cortex and connect with subcortical structures including the basal ganglia. In the primary motor cortex of the frontal lobe, layer V contains giant pyramidal cells called Betz cells, whose axons travel through the internal capsule, the brain stem, and the spinal cord forming the corticospinal tract, which is the main pathway for voluntary motor control.

Layer VI, the polymorphic or multiform layer, contains few large pyramidal neurons and many small spindle-like pyramidal and multiform neurons; layer VI sends efferent fibers to the thalamus, establishing a very precise reciprocal interconnection between the cortex and the thalamus. That is, layer VI neurons from one cortical column connect with thalamus neurons that provide input to the same cortical column. These connections are both excitatory and inhibitory. Neurons send excitatory fibers to neurons in the thalamus and also send collaterals to the thalamic reticular nucleus that inhibit these same thalamus neurons or ones adjacent to them. One theory is that because the inhibitory output is reduced by cholinergic input to the cerebral cortex, this provides the brainstem with adjustable "gain control for the relay of lemniscal inputs".

The cerebral cortex is connected to various subcortical structures such as the thalamus and the basal ganglia, sending information to them along efferent connections and receiving information from them via afferent connections. Most sensory information is routed to the cerebral cortex via the thalamus. Olfactory information, however, passes through the olfactory bulb to the olfactory cortex (piriform cortex). The majority of connections are from one area of the cortex to another, rather than from subcortical areas; Braitenberg and Schüz (1998) claim that in primary sensory areas, at the cortical level where the input fibres terminate, up to 20% of the synapses are supplied by extracortical afferents but that in other areas and other layers the percentage is likely to be much lower.

The cortex is divided into two main functional areas – a motor cortex and a sensory cortex. 

The Brodmann areas, are based on their cytoarchitecture but also relate to various functions. An example is Brodmann area 17 which is the primary visual cortex.

In more general terms the cortex is typically described as comprising three parts: sensory, motor, and association areas.

The sensory areas are the cortical areas that receive and process information from the senses. Parts of the cortex that receive sensory inputs from the thalamus are called primary sensory areas. The senses of vision, hearing, and touch are served by the primary visual cortex, primary auditory cortex and primary somatosensory cortex respectively. In general, the two hemispheres receive information from the opposite (contralateral) side of the body. For example, the right primary somatosensory cortex receives information from the left limbs, and the right visual cortex receives information from the left visual field. The organization of sensory maps in the cortex reflects that of the corresponding sensing organ, in what is known as a topographic map. Neighboring points in the primary visual cortex, for example, correspond to neighboring points in the retina. This topographic map is called a retinotopic map. In the same way, there exists a tonotopic map in the primary auditory cortex and a somatotopic map in the primary sensory cortex. This last topographic map of the body onto the posterior central gyrus has been illustrated as a deformed human representation, the somatosensory homunculus, where the size of different body parts reflects the relative density of their innervation. Areas with lots of sensory innervation, such as the fingertips and the lips, require more cortical area to process finer sensation.

The motor areas are located in both hemispheres of the cortex. The motor areas are very closely related to the control of voluntary movements, especially fine fragmented movements performed by the hand. The right half of the motor area controls the left side of the body, and vice versa.

Two areas of the cortex are commonly referred to as motor:

* Primary motor cortex, which executes voluntary movements
* Supplementary motor areas and premotor cortex, which select voluntary movements.

In addition, motor functions have been described for:

* Posterior parietal cortex, which guides voluntary movements in space
* Dorsolateral prefrontal cortex, which decides which voluntary movements to make according to higher-order instructions, rules, and self-generated thoughts.

Just underneath the cerebral cortex are interconnected subcortical masses of grey matter called basal ganglia (or nuclei). The basal ganglia receive input from the substantia nigra of the midbrain and motor areas of the cerebral cortex, and send signals back to both of these locations. They are involved in motor control. They are found lateral to the thalamus. The main components of the basal ganglia are the caudate nucleus, the putamen, the globus pallidus, the substantia nigra, the nucleus accumbens, and the subthalamic nucleus. The putamen and globus pallidus are also collectively known as the lentiform nucleus, because together they form a lens-shaped body. The putamen and caudate nucleus are also collectively called the corpus striatum after their striped appearance.

The association areas are the parts of the cerebral cortex that do not belong to the primary regions. They function to produce a meaningful perceptual experience of the world, enable us to interact effectively, and support abstract thinking and language. The parietal, temporal, and occipital lobes - all located in the posterior part of the cortex - integrate sensory information and information stored in memory. The frontal lobe or prefrontal association complex is involved in planning actions and movement, as well as abstract thought. Globally, the association areas are organized as distributed networks. Each network connects areas distributed across widely spaced regions of the cortex. Distinct networks are positioned adjacent to one another yielding a complex series of interwoven networks. The specific organization of the association networks is debated with evidence for interactions, hierarchical relationships, and competition between networks.

In humans, association networks are particularly important to language function. In the past it was theorized that language abilities are localized in Broca's area in areas of the left inferior frontal gyrus, BA44 and BA45, for language expression and in Wernicke's area BA22, for language reception. However, the processes of language expression and reception have been shown to occur in areas other than just those structures around the lateral sulcus, including the frontal lobe, basal ganglia, cerebellum, and pons.

The primary motor cortex, which sends axons down to motor neurons in the brainstem and spinal cord, occupies the rear portion of the frontal lobe, directly in front of the somatosensory area. The primary sensory areas receive signals from the sensory nerves and tracts by way of relay nuclei in the thalamus. Primary sensory areas include the visual cortex of the occipital lobe, the auditory cortex in parts of the temporal lobe and insular cortex, and the somatosensory cortex in the parietal lobe. The remaining parts of the cortex, are called the association areas. These areas receive input from the sensory areas and lower parts of the brain and are involved in the complex cognitive processes of perception, thought, and decision-making. The main functions of the frontal lobe are to control attention, abstract thinking, behaviour, problem solving tasks, and physical reactions and personality. The occipital lobe is the smallest lobe; its main functions are visual reception, visual-spatial processing, movement, and colour recognition. There is a smaller occipital lobule in the lobe known as the cuneus. The temporal lobe controls auditory and visual memories, language, and some hearing and speech.

The cerebrum contains the ventricles where the cerebrospinal fluid is produced and circulated. Below the corpus callosum is the septum pellucidum, a membrane that separates the lateral ventricles. Beneath the lateral ventricles is the thalamus and to the front and below this is the hypothalamus. The hypothalamus leads on to the pituitary gland. At the back of the thalamus is the brainstem.

The basal ganglia, also called basal nuclei, are a set of structures deep within the hemispheres involved in behaviour and movement regulation. The largest component is the striatum, others are the globus pallidus, the substantia nigra and the subthalamic nucleus. Part of the dorsal striatum, the putamen, and the globus pallidus, lie separated from the lateral ventricles and thalamus by the internal capsule, whereas the caudate nucleus stretches around and abuts the lateral ventricles on their outer sides. At the deepest part of the lateral sulcus between the insular cortex and the striatum is a thin neuronal sheet called the claustrum.

Below and in front of the striatum are a number of basal forebrain structures. These include the nucleus accumbens, nucleus basalis, diagonal band of Broca, substantia innominata, and the medial septal nucleus. These structures are important in producing the neurotransmitter, acetylcholine, which is then distributed widely throughout the brain. The basal forebrain, in particular the nucleus basalis, is considered to be the major cholinergic output of the central nervous system to the striatum and neocortex.
The cerebrum or telencephalon is a large part of the brain containing the cerebral cortex (of the two cerebral hemispheres), as well as several subcortical structures, including the hippocampus, basal ganglia, and olfactory bulb. In the human brain, the cerebrum is the uppermost region of the central nervous system. The prosencephalon or forebrain is the embryonic structure from which the cerebrum develops prenatally. In mammals, the dorsal telencephalon, or pallium, develops into the cerebral cortex, and the ventral telencephalon, or subpallium, becomes the basal ganglia. The cerebrum is also divided into approximately symmetric left and right cerebral hemispheres.

With the assistance of the cerebellum, the cerebrum controls all voluntary actions in the human body.

### The basal ganglia

The basal ganglia (or basal nuclei) are a group of subcortical nuclei, of varied origin, in the brains of vertebrates, including humans, which are situated at the base of the forebrain and top of the midbrain. There are some differences in the basal ganglia of primates. Basal ganglia are strongly interconnected with the cerebral cortex, thalamus, and brainstem, as well as several other brain areas. The basal ganglia are associated with a variety of functions, including control of voluntary motor movements, procedural learning, habit learning, eye movements, cognition, and emotion.

The main components of the basal ganglia – as defined functionally – are the striatum; both dorsal striatum (caudate nucleus and putamen) and ventral striatum (nucleus accumbens and olfactory tubercle), globus pallidus, ventral pallidum, substantia nigra, and subthalamic nucleus. Each of these components has a complex internal anatomical and neurochemical organization. The largest component, the striatum (dorsal and ventral), receives input from many brain areas beyond the basal ganglia, but only sends output to other components of the basal ganglia. The pallidum receives input from the striatum, and sends inhibitory output to a number of motor-related areas. The substantia nigra is the source of the striatal input of the neurotransmitter dopamine, which plays an important role in basal ganglia function. The subthalamic nucleus receives input mainly from the striatum and cerebral cortex, and projects to the globus pallidus.

Popular theories implicate the basal ganglia primarily in action selection – in helping to decide which of several possible behaviors to execute at any given time. In more specific terms, the basal ganglia's primary function is likely to control and regulate activities of the motor and premotor cortical areas so that voluntary movements can be performed smoothly. Experimental studies show that the basal ganglia exert an inhibitory influence on a number of motor systems, and that a release of this inhibition permits a motor system to become active. The "behavior switching" that takes place within the basal ganglia is influenced by signals from many parts of the brain, including the prefrontal cortex, which plays a key role in executive functions.

The basal ganglia are of major importance for normal brain function and behaviour. Their dysfunction results in a wide range of neurological conditions including disorders of behaviour control and movement. Those of behaviour include Tourette syndrome, obsessive–compulsive disorder, and addiction. Movement disorders include, most notably Parkinson's disease, which involves degeneration of the dopamine-producing cells in the substantia nigra, Huntington's disease, which primarily involves damage to the striatum, dystonia, and more rarely hemiballismus. The basal ganglia have a limbic sector whose components are assigned distinct names: the nucleus accumbens, ventral pallidum, and ventral tegmental area (VTA). There is considerable evidence that this limbic part plays a central role in reward learning as well as cognition and frontal lobe functioning, via the mesolimbic pathway from the VTA to the nucleus accumbens that uses the neurotransmitter dopamine, and the mesocortical pathway. A number of highly addictive drugs, including cocaine, amphetamine, specific medications that are prescribed by a doctor, and nicotine, are thought to work by increasing the efficacy of this dopamine signal. There is also evidence implicating overactivity of the VTA dopaminergic projection in schizophrenia.

The basal ganglia form a fundamental component of the cerebrum. In contrast to the cortical layer that lines the surface of the forebrain, the basal ganglia are a collection of distinct masses of gray matter lying deep in the brain not far from the junction of the thalamus. They lie to the side of and surround the thalamus. Like most parts of the brain, the basal ganglia consist of left and right sides that are virtual mirror images of each other.

In terms of anatomy, the basal ganglia are divided into four distinct structures, depending on how superior or rostral they are (in other words depending on how close to the top of the head they are): Two of them, the striatum and the pallidum, are relatively large; the other two, the substantia nigra and the subthalamic nucleus, are smaller. In the illustration to the right, two coronal sections of the human brain show the location of the basal ganglia components. Of note, and not seen in this section, the subthalamic nucleus and substantia nigra lie farther back (posteriorly) in the brain than the striatum and pallidum.

#### The striatum

The striatum is a subcortical structure generally divided into the dorsal striatum and ventral striatum, although a medial lateral classification has been suggested to be more relevant behaviorally and is being more widely used.

The striatum is composed mostly of medium spiny neurons. These GABAergic neurons project to the external (lateral) globus pallidus and internal (medial) globus pallidus as well as the substantia nigra pars reticulata. The projections into the globus pallidus and substantia nigra are primarily dopaminergic, although enkephalin, dynorphin and substance P are expressed. The striatum also contains interneurons that are classified into nitrergic neurons (due to use of nitric oxide as a neurotransmitter), tonically active[clarification needed] cholinergic interneurons, parvalbumin-expressing neurons and calretinin-expressing neurons. The dorsal striatum receives significant glutamatergic inputs from the cortex, as well as dopaminergic inputs from the substantia nigra pars compacta. The dorsal striatum is generally considered to be involved in sensorimotor activities. The ventral striatum receives glutamatergic inputs from the limbic areas as well as dopaminergic inputs from the VTA, via the mesolimbic pathway. The ventral striatum is believed to play a role in reward and other limbic functions. The dorsal striatum is divided into the caudate and putamen by the internal capsule while the ventral striatum is composed of the nucleus accumbens and olfactory tubercle. The caudate has three primary regions of connectivity, with the head of the caudate demonstrating connectivity to the prefrontal cortex, cingulate cortex and amygdala. The body and tail show differentiation between the dorsolateral rim and ventral caudate, projecting to the sensorimotor and limbic regions of the striatum respectively. Striatopallidal fibres connect the striatum to the pallidus.

#### The pallidum

The pallidum consists of a large structure called the globus pallidus ("pale globe") together with a smaller ventral extension called the ventral pallidum. The globus pallidus appears as a single neural mass, but can be divided into two functionally distinct parts, called the internal (or medial) and external (lateral) segments, abbreviated GPi and GPe. Both segments contain primarily GABAergic neurons, which therefore have inhibitory effects on their targets. The two segments participate in distinct neural circuits. The GPe receives input mainly from the striatum, and projects to the subthalamic nucleus. The GPi receives signals from the striatum via the "direct" and "indirect" pathways. Pallidal neurons operate using a disinhibition principle. These neurons fire at steady high rates in the absence of input, and signals from the striatum cause them to pause or reduce their rate of firing. Because pallidal neurons themselves have inhibitory effects on their targets, the net effect of striatal input to the pallidum is a reduction of the tonic inhibition exerted by pallidal cells on their targets (disinhibition) with an increased rate of firing in the targets.

#### The substantia nigra

The substantia nigra is a midbrain gray matter portion of the basal ganglia that has two parts – the pars compacta (SNc) and the pars reticulata (SNr). SNr often works in unison with GPi, and the SNr-GPi complex inhibits the thalamus. Substantia nigra pars compacta (SNc) however, produces the neurotransmitter dopamine, which is very significant in maintaining balance in the striatal pathway. The circuit portion below explains the role and circuit connections of each of the components of the basal ganglia.

#### The subthalamic nucleus

The subthalamic nucleus is a diencephalic gray matter portion of the basal ganglia, and the only portion of the ganglia that produces an excitatory neurotransmitter, glutamate. The role of the subthalamic nucleus is to stimulate the SNr-GPi complex and it is part of the indirect pathway. The subthalamic nucleus receives inhibitory input from the external part of the globus pallidus and sends excitatory input to the GPi.

### Thalamus

The thalamus (from Greek θάλαμος, "chamber") is a large mass of gray matter located in the dorsal part of the diencephalon (a division of the forebrain). Nerve fibers project out of the thalamus to the cerebral cortex in all directions, allowing hub-like exchanges of information. It has several functions, such as relaying of sensory signals, including motor signals to the cerebral cortex,[page needed] and the regulation of consciousness, sleep, and alertness.

Anatomically, it is a midline symmetrical structure of two halves (left and right), within the vertebrate brain, situated between the cerebral cortex and the midbrain. It forms during embryonic development as the main product of the diencephalon, as first recognized by the Swiss embryologist and anatomist Wilhelm His Sr. in 1893.

The thalamus has many connections to the hippocampus via the mammillothalamic tract, this tract comprises the mammillary bodies and fornix.

The thalamus is connected to the cerebral cortex via the thalamocortical radiations.

The spinothalamic tract is a sensory pathway originating in the spinal cord. It transmits information to the thalamus about pain, temperature, itch and crude touch. There are two main parts: the lateral spinothalamic tract, which transmits pain and temperature, and the anterior (or ventral) spinothalamic tract, which transmits crude touch and pressure.

The thalamus has multiple functions, generally believed to act as a relay station, or hub, relaying information between different subcortical areas and the cerebral cortex. In particular, every sensory system (with the exception of the olfactory system) includes a thalamic nucleus that receives sensory signals and sends them to the associated primary cortical area. For the visual system, for example, inputs from the retina are sent to the lateral geniculate nucleus of the thalamus, which in turn projects to the visual cortex in the occipital lobe. The thalamus is believed to both process sensory information as well as relay it—each of the primary sensory relay areas receives strong feedback connections from the cerebral cortex. Similarly the medial geniculate nucleus acts as a key auditory relay between the inferior colliculus of the midbrain and the primary auditory cortex. The ventral posterior nucleus is a key somatosensory relay, which sends touch and proprioceptive information to the primary somatosensory cortex.

The thalamus also plays an important role in regulating states of sleep and wakefulness. Thalamic nuclei have strong reciprocal connections with the cerebral cortex, forming thalamo-cortico-thalamic circuits that are believed to be involved with consciousness. The thalamus plays a major role in regulating arousal, the level of awareness, and activity. Damage to the thalamus can lead to permanent coma.

The role of the thalamus in the more anterior pallidal and nigral territories in the basal ganglia system disturbances is recognized but still poorly understood. The contribution of the thalamus to vestibular or to tectal functions is almost ignored. The thalamus has been thought of as a "relay" that simply forwards signals to the cerebral cortex. Newer research suggests that thalamic function is more selective. Many different functions are linked to various regions of the thalamus. This is the case for many of the sensory systems (except for the olfactory system), such as the auditory, somatic, visceral, gustatory and visual systems where localized lesions provoke specific sensory deficits. A major role of the thalamus is support of motor and language systems, and much of the circuitry implicated for these systems is shared. The thalamus is functionally connected to the hippocampus as part of the extended hippocampal system at the thalamic anterior nuclei with respect to spatial memory and spatial sensory datum they are crucial for human episodic memory and rodent event memory. There is support for the hypothesis that thalamic regions connection to particular parts of the mesio-temporal lobe provide differentiation of the functioning of recollective and familiarity memory.

The neuronal information processes necessary for motor control were proposed as a network involving the thalamus as a subcortical motor center. Through investigations of the anatomy of the brains of primates the nature of the interconnected tissues of the cerebellum to the multiple motor cortices suggested that the thalamus fulfills a key function in providing the specific channels from the basal ganglia and cerebellum to the cortical motor areas. In an investigation of the saccade and antisaccade motor response in three monkeys, the thalamic regions were found to be involved in the generation of antisaccade eye-movement (that is, the ability to inhibit the reflexive jerking movement of the eyes in the direction of a presented stimulus].

Recent research suggests that the mediodorsal thalamus may play a broader role in cognition. Specifically, the mediodorsal thalamus may "amplify the connectivity (signaling strength) of just the circuits in the cortex appropriate for the current context and thereby contribute to the flexibility (of the mammalian brain) to make complex decisions by wiring the many associations on which decisions depend into weakly connected cortical circuits." Researchers founds that "enhancing MD activity magnified the ability of mice to “think,” driving down by more than 25 percent their error rate in deciding which conflicting sensory stimuli to follow to find the reward." 

### Hypothalamus

The hypothalamus is a portion of the brain that contains a number of small nuclei with a variety of functions. One of the most important functions of the hypothalamus is to link the nervous system to the endocrine system via the pituitary gland. The hypothalamus is located below the thalamus and is part of the limbic system. In the terminology of neuroanatomy, it forms the ventral part of the diencephalon. All vertebrate brains contain a hypothalamus. In humans, it is the size of an almond. The hypothalamus is responsible for the regulation of certain metabolic processes and other activities of the autonomic nervous system. It synthesizes and secretes certain neurohormones, called releasing hormones or hypothalamic hormones, and these in turn stimulate or inhibit the secretion of hormones from the pituitary gland. The hypothalamus controls body temperature, hunger, important aspects of parenting and attachment behaviours, thirst, fatigue, sleep, and circadian rhythms. The hypothalamus derives its name from Greek ὑπό, under and θάλαμος, chamber.

The hypothalamus has a central neuroendocrine function, most notably by its control of the anterior pituitary, which in turn regulates various endocrine glands and organs. Releasing hormones (also called releasing factors) are produced in hypothalamic nuclei then transported along axons to either the median eminence or the posterior pituitary, where they are stored and released as needed.

In the hypothalamic–adenohypophyseal axis, releasing hormones, also known as hypophysiotropic or hypothalamic hormones, are released from the median eminence, a prolongation of the hypothalamus, into the hypophyseal portal system, which carries them to the anterior pituitary where they exert their regulatory functions on the secretion of adenohypophyseal hormones. These hypophysiotropic hormones are stimulated by parvocellular neurosecretory cells located in the periventricular area of the hypothalamus. After their release into the capillaries of the third ventricle, the hypophysiotropic hormones travel through what is known as the hypothalamo-pituitary portal circulation. Once they reach their destination in the anterior pituitary, these hormones bind to specific receptors located on the surface of pituitary cells. Depending on which cells are activated through this binding, the pituitary will either begin secreting or stop secreting hormones into the rest of the bloodstream.

### The midbrain

The midbrain or mesencephalon is the rostral-most portion of the brainstem and is associated with vision, hearing, motor control, sleep and wakefulness, arousal (alertness), and temperature regulation.

The principal regions of the midbrain are the tectum, the cerebral aqueduct, tegmentum, and the cerebral peduncles. Rostrally the midbrain adjoins the diencephalon (thalamus, hypothalamus, etc.), while caudally it adjoins the hindbrain (pons, medulla and cerebellum). In the rostral direction, the midbrain noticeably splays laterally.

Sectioning of the midbrain is usually performed axially, at one of two levels – that of the superior colliculi, or that of the inferior colliculi. One common technique for remembering the structures of the midbrain involves visualizing these cross-sections (especially at the level of the superior colliculi) as the upside-down face of a bear, with the cerebral peduncles forming the ears, the cerebral aqueduct the mouth, and the tectum the chin; prominent features of the tegmentum form the eyes and certain sculptural shadows of the face.

#### Tectum

The tectum (Latin for roof) is the dorsal side of the midbrain. The position of the tectum is contrasted with the tegmentum, which refers to the region in front of the ventricular system, or floor of the midbrain.

The mesencephalon is considered part of the brainstem. Its substantia nigra is closely associated with motor system pathways of the basal ganglia. The human mesencephalon is archipallian in origin, meaning that its general architecture is shared with the most ancient of vertebrates. Dopamine produced in the substantia nigra and ventral tegmental area plays a role in movement, movement planning, excitation, motivation and habituation of species from humans to the most elementary animals such as insects. Laboratory house mice from lines that have been selectively bred for high voluntary wheel running have enlarged midbrains. The midbrain helps to relay information for vision and hearing.It is involved in certain reflexes in response to visual or auditory stimuli. The reticulospinal tract, which exerts some control over alertness, takes input from the tectum, and travels both rostrally and caudally from it.

The corpora quadrigemina are four mounds, called colliculi, in two pairs – a superior and an inferior pair, on the surface of the tectum. The superior colliculi process some visual information, aid the decussation of several fibres of the optic nerve (some fibres remain ipsilateral), and are involved with saccadic eye movements. The tectospinal tract connects the superior colliculi to the cervical nerves of the neck, and co-ordinates head and eye movements. Each superior colliculi also sends information to the corresponding lateral geniculate nucleus, with which it is directly connected. The homologous structure to the superior colliculus in non mammalian vertebrates including fish and amphibians, is called the optic tectum; in those animals, the optic tectum integrates sensory information from the eyes and certain auditory reflexes.

The inferior colliculi – located just above the trochlear nerve – process certain auditory information. Each inferior colliculus sends information to the corresponding medial geniculate nucleus, with which it is directly connected.

The cerebral aqueduct is the part of the ventricular system which links the third ventricle (rostrally) with the fourth ventricle (caudally); as such it is responsible for continuing the circulation of cerebrospinal fluid. The cerebral aqueduct is a narrow channel located between the tectum and the tegmentum, and is surrounded by the periaqueductal grey, which has a role in analgesia, quiescence, and bonding. The dorsal raphe nucleus (which releases serotonin in response to certain neural activity) is located at the ventral side of the periaqueductal grey, at the level of the inferior colliculus.

The nuclei of two pairs of cranial nerves are similarly located at the ventral side of the periaqueductal grey – the pair of oculomotor nuclei (which control the eyelid, and most eye movements) is located at the level of the superior colliculus, while the pair of trochlear nuclei (which helps focus vision on more proximal objects) is located caudally to that, at the level of the inferior colliculus, immediatetly lateral to the dorsal raphe nucleus. The oculomotor nerve emerges from the nucleus by traversing the ventral width of the tegmentum, while the trochlear nerve emerges via the tectum, just below the inferior colliculus itself; the trochlear is the only cranial nerve to exit the brainstem dorsally. The Edinger-Westphal nucleus (which controls the shape of the lens and size of the pupil) is located between the oculomotor nucleus and the cerebral aqueduct.

#### The tegmentum

The midbrain tegmentum is the portion of the midbrain ventral to the cerebral aqueduct, and is much larger in size than the tectum. It communicates with the cerebellum by the superior cerebellar peduncles, which enter at the caudal end, medially, on the ventral side; the cerebellar peduncles are distinctive at the level of the inferior colliculus, where they decussate, but they dissipate more rostrally. Between these peduncles, on the ventral side, is the median raphe nucleus, which is involved in memory consolidation.

The main bulk of the tegmentum contains a complex synaptic network of neurons, primarily involved in homeostasis and reflex actions. It includes portions of the reticular formation. A number of distinct nerve tracts between other parts of the brain pass through it. The medial lemniscus – a narrow ribbon of fibres – passes through in a relatively constant axial position; at the level of the inferior colliculus it is near the lateral edge, on the ventral side, and retains a similar position rostrally (due to widening of the tegmentum towards the rostral end, the position can appears more medial). The spinothalamic tract – another ribbon-like region of fibres – are located at the lateral edge of the tegmentum; at the level of the inferior colliculus it is immediately dorsal to the medial lemiscus, but due to the rostral widening of the tegmentum, is lateral of the medial lemiscus at the level of the superior colliculus.

A prominent pair of round, reddish, regions – the red nuclei (which have a role in motor co-ordination) – are located in the rostral portion of the midbrain, somewhat medially, at the level of the superior colliculus. The rubrospinal tract emerges from the red nucleus and descends caudally, primarily heading to the cervical portion of the spine, to implement the red nuclei's decisions. The area between the red nuclei, on the ventral side – known as the ventral tegmental area – is the largest dopamine-producing area in the brain, and is heavily involved in the neural reward system. The ventral tegmental area is in contact with parts of the forebrain – the mammillary bodies (from the telencephalon) and hypothalamus (of the diencephalon).

The cerebral peduncles each form a lobe ventrally of the tegmentum, on either side of the midline. Beyond the midbrain, between the lobes, is the interpeduncular fossa, which is a cistern filled with cerebrospinal fluid.

The majority of each lobe constitutes the cerebral crus. The cerebral crura are the main tracts descending from the thalamus to caudal parts of the central nervous system; the central and medial ventral portions contain the corticobulbar and corticospinal tracts, while the remainder of each crus primarily contains tracts connecting the cortex to the pons. Older texts refer to the crus cerebri as the cerebral peduncle; however, the latter term actually covers all fibres communicating with the cerebrum (usually via the diencephalon), and therefore would include much of the tegmentum as well. The remainder of the crus pedunculi – small regions around the main cortical tracts – contain tracts from the internal capsule.

The portion of the lobes in connection with the tegmentum, except the most lateral portion, is dominated by a blackened band – the substantia nigra (literally black substance) – which is the only part of the basal ganglia system outside the forebrain. It is ventrally wider at the rostral end. By means of the basal ganglia, the substantia nigra is involved in motor-planning, learning, addiction, and other functions. There are two regions within the substantia nigra – one where neurons are densely packed (the pars compacta) and one where they aren't (the pars reticulata), which serve a different role from one another within the basal ganglia system. The substantia nigra has extremely high production of melanin (hence the colour), dopamine, and noradrenalin; the loss of dopamine-producing neurons in this region contributes to the progression of Parkinson's disease.

### Cerebellum

The cerebellum (Latin for "little brain") is a major feature of the hindbrain of all vertebrates. Although usually smaller than the cerebrum, in some animals such as the mormyrid fishes it may be as large as or even larger. In humans, the cerebellum plays an important role in motor control. It may also be involved in some cognitive functions such as attention and language as well as in regulating fear and pleasure responses, but its movement-related functions are the most solidly established. The human cerebellum does not initiate movement, but contributes to coordination, precision, and accurate timing: it receives input from sensory systems of the spinal cord and from other parts of the brain, and integrates these inputs to fine-tune motor activity. Cerebellar damage produces disorders in fine movement, equilibrium, posture, and motor learning in humans.

Anatomically, the human cerebellum has the appearance of a separate structure attached to the bottom of the brain, tucked underneath the cerebral hemispheres. Its cortical surface is covered with finely spaced parallel grooves, in striking contrast to the broad irregular convolutions of the cerebral cortex. These parallel grooves conceal the fact that the cerebellar cortex is actually a continuous thin layer of tissue tightly folded in the style of an accordion. Within this thin layer are several types of neurons with a highly regular arrangement, the most important being Purkinje cells and granule cells. This complex neural organization gives rise to a massive signal-processing capability, but almost all of the output from the cerebellar cortex passes through a set of small deep nuclei lying in the white matter interior of the cerebellum.

In addition to its direct role in motor control, the cerebellum is necessary for several types of motor learning, most notably learning to adjust to changes in sensorimotor relationships.

At the level of gross anatomy, the cerebellum consists of a tightly folded layer of cortex, with white matter underneath and a fluid-filled ventricle at the base. Four deep cerebellar nuclei are embedded in the white matter. Each part of the cortex consists of the same small set of neuronal elements, laid out in a highly stereotyped geometry. At an intermediate level, the cerebellum and its auxiliary structures can be separated into several hundred or thousand independently functioning modules called "microzones" or "microcompartments".

The cerebellum is located in the posterior cranial fossa. The fourth ventricle, pons and medulla are in front of the cerebellum. It is separated from the overlying cerebrum by a layer of leathery dura mater, the tentorium cerebelli; all of its connections with other parts of the brain travel through the pons. Anatomists classify the cerebellum as part of the metencephalon, which also includes the pons; the metencephalon is the upper part of the rhombencephalon or "hindbrain". Like the cerebral cortex, the cerebellum is divided into two hemispheres; it also contains a narrow midline zone (the vermis). A set of large folds is, by convention, used to divide the overall structure into 10 smaller "lobules". Because of its large number of tiny granule cells, the cerebellum contains more neurons than the total from the rest of the brain, but takes up only 10% of the total brain volume. The number of neurons in the cerebellum is related to the number of neurons in the neocortex. There are about 3.6 times as many neurons in the cerebellum as in the neocortex, a ratio that is conserved across many different mammalian species.

The unusual surface appearance of the cerebellum conceals the fact that most of its volume is made up of a very tightly folded layer of gray matter: the cerebellar cortex. Each ridge or gyrus in this layer is called a folium. It is estimated that, if the human cerebellar cortex were completely unfolded, it would give rise to a layer of neural tissue about 1 meter long and averaging 5 centimeters wide—a total surface area of about 500 square cm, packed within a volume of dimensions 6 cm × 5 cm × 10 cm. Underneath the gray matter of the cortex lies white matter, made up largely of myelinated nerve fibers running to and from the cortex. Embedded within the white matter—which is sometimes called the arbor vitae (tree of life) because of its branched, tree-like appearance in cross-section—are four deep cerebellar nuclei, composed of gray matter.

Connecting the cerebellum to different parts of the nervous system are three paired cerebellar peduncles. These are the superior cerebellar peduncle, the middle cerebellar peduncle and the inferior cerebellar peduncle, named by their position relative to the vermis. The superior cerebellar peduncle is mainly an output to the cerebral cortex, carrying efferent fibers via thalamic nuclei to upper motor neurons in the cerebral cortex. The fibers arise from the deep cerebellar nuclei. The middle cerebellar peduncle is connected to the pons and receives all of its input from the pons mainly from the pontine nuclei. The input to the pons is from the cerebral cortex and is relayed from the pontine nuclei via transverse pontine fibers to the cerebellum. The middle peduncle is the largest of the three and its afferent fibers are grouped into three separate fascicles taking their inputs to different parts of the cerebellum. The inferior cerebellar peduncle receives input from afferent fibers from the vestibular nuclei, spinal cord and the tegmentum. Output from the inferior peduncle is via efferent fibers to the vestibular nuclei and the reticular formation. The whole of the cerebellum receives modulatory input from the inferior olivary nucleus via the inferior cerebellar peduncle.

Based on the surface appearance, three lobes can be distinguished within the cerebellum: the anterior lobe (above the primary fissure), the posterior lobe (below the primary fissure), and the flocculonodular lobe (below the posterior fissure). These lobes divide the cerebellum from rostral to caudal (in humans, top to bottom). In terms of function, however, there is a more important distinction along the medial-to-lateral dimension. Leaving out the flocculonodular lobe, which has distinct connections and functions, the cerebellum can be parsed functionally into a medial sector called the spinocerebellum and a larger lateral sector called the cerebrocerebellum. A narrow strip of protruding tissue along the midline is called the cerebellar vermis. (Vermis is Latin for "worm".)

The smallest region, the flocculonodular lobe, is often called the vestibulocerebellum. It is the oldest part in evolutionary terms (archicerebellum) and participates mainly in balance and spatial orientation; its primary connections are with the vestibular nuclei, although it also receives visual and other sensory input. Damage to this region causes disturbances of balance and gait.

The medial zone of the anterior and posterior lobes constitutes the spinocerebellum, also known as paleocerebellum. This sector of the cerebellum functions mainly to fine-tune body and limb movements. It receives proprioceptive input from the dorsal columns of the spinal cord (including the spinocerebellar tract) and from the cranial trigeminal nerve, as well as from visual and auditory systems. It sends fibers to deep cerebellar nuclei that, in turn, project to both the cerebral cortex and the brain stem, thus providing modulation of descending motor systems.

The lateral zone, which in humans is by far the largest part, constitutes the cerebrocerebellum, also known as neocerebellum. It receives input exclusively from the cerebral cortex (especially the parietal lobe) via the pontine nuclei (forming cortico-ponto-cerebellar pathways), and sends output mainly to the ventrolateral thalamus (in turn connected to motor areas of the premotor cortex and primary motor area of the cerebral cortex) and to the red nucleus. There is disagreement about the best way to describe the functions of the lateral cerebellum: It is thought to be involved in planning movement that is about to occur, in evaluating sensory information for action, and in a number of purely cognitive functions, such as determining the verb which best fits with a certain noun (as in "sit" for "chair").

Two types of neuron play dominant roles in the cerebellar circuit: Purkinje cells and granule cells. Three types of axons also play dominant roles: mossy fibers and climbing fibers (which enter the cerebellum from outside), and parallel fibers (which are the axons of granule cells). There are two main pathways through the cerebellar circuit, originating from mossy fibers and climbing fibers, both eventually terminating in the deep cerebellar nuclei.

Mossy fibers project directly to the deep nuclei, but also give rise to the following pathway: mossy fibers → granule cells → parallel fibers → Purkinje cells → deep nuclei. Climbing fibers project to Purkinje cells and also send collaterals directly to the deep nuclei. The mossy fiber and climbing fiber inputs each carry fiber-specific information; the cerebellum also receives dopaminergic, serotonergic, noradrenergic, and cholinergic inputs that presumably perform global modulation.

The cerebellar cortex is divided into three layers. At the bottom lies the thick granular layer, densely packed with granule cells, along with interneurons, mainly Golgi cells but also including Lugaro cells and unipolar brush cells. In the middle lies the Purkinje layer, a narrow zone that contains the cell bodies of Purkinje cells and Bergmann glial cells. At the top lies the molecular layer, which contains the flattened dendritic trees of Purkinje cells, along with the huge array of parallel fibers penetrating the Purkinje cell dendritic trees at right angles. This outermost layer of the cerebellar cortex also contains two types of inhibitory interneuron: stellate cells and basket cells. Both stellate and basket cells form GABAergic synapses onto Purkinje cell dendrites.

Purkinje cells are among the most distinctive neurons in the brain, and one of the earliest types to be recognized—they were first described by the Czech anatomist Jan Evangelista Purkyně in 1837. They are distinguished by the shape of their dendritic tree: The dendrites branch very profusely, but are severely flattened in a plane perpendicular to the cerebellar folds. Thus, the dendrites of a Purkinje cell form a dense planar net, through which parallel fibers pass at right angles. The dendrites are covered with dendritic spines, each of which receives synaptic input from a parallel fiber. Purkinje cells receive more synaptic inputs than any other type of cell in the brain—estimates of the number of spines on a single human Purkinje cell run as high as 200,000. The large, spherical cell bodies of Purkinje cells are packed into a narrow layer (one cell thick) of the cerebellar cortex, called the Purkinje layer. After emitting collaterals that affect nearby parts of the cortex, their axons travel into the deep cerebellar nuclei, where they make on the order of 1,000 contacts each with several types of nuclear cells, all within a small domain. Purkinje cells use GABA as their neurotransmitter, and therefore exert inhibitory effects on their targets.

Purkinje cells form the heart of the cerebellar circuit, and their large size and distinctive activity patterns have made it relatively easy to study their response patterns in behaving animals using extracellular recording techniques. Purkinje cells normally emit action potentials at a high rate even in the absence of the synaptic input. In awake, behaving animals, mean rates averaging around 40 Hz are typical. The spike trains show a mixture of what are called simple and complex spikes. A simple spike is a single action potential followed by a refractory period of about 10 ms; a complex spike is a stereotyped sequence of action potentials with very short inter-spike intervals and declining amplitudes. Physiological studies have shown that complex spikes (which occur at baseline rates around 1 Hz and never at rates much higher than 10 Hz) are reliably associated with climbing fiber activation, while simple spikes are produced by a combination of baseline activity and parallel fiber input. Complex spikes are often followed by a pause of several hundred milliseconds during which simple spike activity is suppressed.

A specific, recognizable feature of Purkinje neurons is the expression of calbindin. Calbindin staining of rat brain after unilateral chronic sciatic nerve injury suggests that Purkinje neurons may be newly generated in the adult brain, initiating the organization of new cerebellar lobules.

Cerebellar granule cells, in contrast to Purkinje cells, are among the smallest neurons in the brain. They are also easily the most numerous neurons in the brain: In humans, estimates of their total number average around 50 billion, which means that about 3/4 of the brain's neurons are cerebellar granule cells. Their cell bodies are packed into a thick layer at the bottom of the cerebellar cortex. A granule cell emits only four to five dendrites, each of which ends in an enlargement called a dendritic claw. These enlargements are sites of excitatory input from mossy fibers and inhibitory input from Golgi cells.

The thin, unmyelinated axons of granule cells rise vertically to the upper (molecular) layer of the cortex, where they split in two, with each branch traveling horizontally to form a parallel fiber; the splitting of the vertical branch into two horizontal branches gives rise to a distinctive "T" shape. A human parallel fiber runs for an average of 3 mm in each direction from the split, for a total length of about 6 mm (about 1/10 of the total width of the cortical layer). As they run along, the parallel fibers pass through the dendritic trees of Purkinje cells, contacting one of every 3–5 that they pass, making a total of 80–100 synaptic connections with Purkinje cell dendritic spines. Granule cells use glutamate as their neurotransmitter, and therefore exert excitatory effects on their targets.

Granule cells receive all of their input from mossy fibers, but outnumber them by 200 to 1 (in humans). Thus, the information in the granule cell population activity state is the same as the information in the mossy fibers, but recoded in a much more expansive way. Because granule cells are so small and so densely packed, it is difficult to record their spike activity in behaving animals, so there is little data to use as a basis for theorizing. The most popular concept of their function was proposed in 1969 by David Marr, who suggested that they could encode combinations of mossy fiber inputs. The idea is that with each granule cell receiving input from only 4–5 mossy fibers, a granule cell would not respond if only a single one of its inputs were active, but would respond if more than one were active. This combinatorial coding scheme would potentially allow the cerebellum to make much finer distinctions between input patterns than the mossy fibers alone would permit.

Mossy fibers enter the granular layer from their points of origin, many arising from the pontine nuclei, others from the spinal cord, vestibular nuclei etc. In the human cerebellum, the total number of mossy fibers has been estimated at about 200 million. These fibers form excitatory synapses with the granule cells and the cells of the deep cerebellar nuclei. Within the granular layer, a mossy fiber generates a series of enlargements called rosettes. The contacts between mossy fibers and granule cell dendrites take place within structures called glomeruli. Each glomerulus has a mossy fiber rosette at its center, and up to 20 granule cell dendritic claws contacting it. Terminals from Golgi cells infiltrate the structure and make inhibitory synapses onto the granule cell dendrites. The entire assemblage is surrounded by a sheath of glial cells. Each mossy fiber sends collateral branches to several cerebellar folia, generating a total of 20–30 rosettes; thus a single mossy fiber makes contact with an estimated 400–600 granule cells.

Purkinje cells also receive input from the inferior olivary nucleus on the contralateral side of the brainstem via climbing fibers. Although the inferior olive lies in the medulla oblongata and receives input from the spinal cord, brainstem and cerebral cortex, its output goes entirely to the cerebellum. A climbing fiber gives off collaterals to the deep cerebellar nuclei before entering the cerebellar cortex, where it splits into about 10 terminal branches, each of which gives input to a single Purkinje cell. In striking contrast to the 100,000-plus inputs from parallel fibers, each Purkinje cell receives input from exactly one climbing fiber; but this single fiber "climbs" the dendrites of the Purkinje cell, winding around them and making a total of up to 300 synapses as it goes. The net input is so strong that a single action potential from a climbing fiber is capable of producing an extended complex spike in the Purkinje cell: a burst of several spikes in a row, with diminishing amplitude, followed by a pause during which activity is suppressed. The climbing fiber synapses cover the cell body and proximal dendrites; this zone is devoid of parallel fiber inputs.

Climbing fibers fire at low rates, but a single climbing fiber action potential induces a burst of several action potentials in a target Purkinje cell (a complex spike). The contrast between parallel fiber and climbing fiber inputs to Purkinje cells (over 100,000 of one type versus exactly one of the other type) is perhaps the most provocative feature of cerebellar anatomy, and has motivated much of the theorizing. In fact, the function of climbing fibers is the most controversial topic concerning the cerebellum. There are two schools of thought, one following Marr and Albus in holding that climbing fiber input serves primarily as a teaching signal, the other holding that its function is to shape cerebellar output directly. Both views have been defended in great length in numerous publications. In the words of one review, "In trying to synthesize the various hypotheses on the function of the climbing fibers, one has the sense of looking at a drawing by Escher. Each point of view seems to account for a certain collection of findings, but when one attempts to put the different views together, a coherent picture of what the climbing fibers are doing does not appear. For the majority of researchers, the climbing fibers signal errors in motor performance, either in the usual manner of discharge frequency modulation or as a single announcement of an 'unexpected event'. For other investigators, the message lies in the degree of ensemble synchrony and rhythmicity among a population of climbing fibers."

Sagittal cross-section of human cerebellum, showing the dentate nucleus, as well as the pons and inferior olivary nucleus
The deep nuclei of the cerebellum are clusters of gray matter lying within the white matter at the core of the cerebellum. They are, with the minor exception of the nearby vestibular nuclei, the sole sources of output from the cerebellum. These nuclei receive collateral projections from mossy fibers and climbing fibers as well as inhibitory input from the Purkinje cells of the cerebellar cortex. The four nuclei (dentate, globose, emboliform, and fastigial) each communicate with different parts of the brain and cerebellar cortex. (The globose and the emboliform nuclei are also referred to as combined in the interposed nucleus). The fastigial and interposed nuclei belong to the spinocerebellum. The dentate nucleus, which in mammals is much larger than the others, is formed as a thin, convoluted layer of gray matter, and communicates exclusively with the lateral parts of the cerebellar cortex. The flocculonodular lobe is the only part of the cerebellar cortex that does not project to the deep nuclei—its output goes to the vestibular nuclei instead.

The majority of neurons in the deep nuclei have large cell bodies and spherical dendritic trees with a radius of about 400 μm, and use glutamate as their neurotransmitter. These cells project to a variety of targets outside the cerebellum. Intermixed with them are a lesser number of small cells, which use GABA as a neurotransmitter and project exclusively to the inferior olivary nucleus, the source of climbing fibers. Thus, the nucleo-olivary projection provides an inhibitory feedback to match the excitatory projection of climbing fibers to the nuclei. There is evidence that each small cluster of nuclear cells projects to the same cluster of olivary cells that send climbing fibers to it; there is strong and matching topography in both directions.

When a Purkinje cell axon enters one of the deep nuclei, it branches to make contact with both large and small nuclear cells, but the total number of cells contacted is only about 35 (in cats). Conversely, a single deep nuclear cell receives input from approximately 860 Purkinje cells (again in cats).

From the viewpoint of gross anatomy, the cerebellar cortex appears to be a homogeneous sheet of tissue, and, from the viewpoint of microanatomy, all parts of this sheet appear to have the same internal structure. There are, however, a number of respects in which the structure of the cerebellum is compartmentalized. There are large compartments that are generally known as zones; these can be divided into smaller compartments known as microzones.

The first indications of compartmental structure came from studies of the receptive fields of cells in various parts of the cerebellar cortex. Each body part maps to specific points in the cerebellum, but there are numerous repetitions of the basic map, forming an arrangement that has been called "fractured somatotopy". A clearer indication of compartmentalization is obtained by immunostaining the cerebellum for certain types of protein. The best-known of these markers are called "zebrins", because staining for them gives rise to a complex pattern reminiscent of the stripes on a zebra. The stripes generated by zebrins and other compartmentalization markers are oriented perpendicular to the cerebellar folds—that is, they are narrow in the mediolateral direction, but much more extended in the longitudinal direction. Different markers generate different sets of stripes, the widths and lengths vary as a function of location, but they all have the same general shape.

The strongest clues to the function of the cerebellum have come from examining the consequences of damage to it. Animals and humans with cerebellar dysfunction show, above all, problems with motor control, on the same side of the body as the damaged part of the cerebellum. They continue to be able to generate motor activity but lose precision, producing erratic, uncoordinated, or incorrectly timed movements. A standard test of cerebellar function is to reach with the tip of the finger for a target at arm's length: A healthy person will move the fingertip in a rapid straight trajectory, whereas a person with cerebellar damage will reach slowly and erratically, with many mid-course corrections. Deficits in non-motor functions are more difficult to detect. Thus, the general conclusion reached decades ago is that the basic function of the cerebellum is to calibrate the detailed form of a movement, not to initiate movements or to decide which movements to execute.

Prior to the 1990s the function of the cerebellum was almost universally believed to be purely motor-related, but newer findings have brought that view into question. Functional imaging studies have shown cerebellar activation in relation to language, attention, and mental imagery; correlation studies have shown interactions between the cerebellum and non-motor areas of the cerebral cortex; and a variety of non-motor symptoms have been recognized in people with damage that appears to be confined to the cerebellum. In particular, the cerebellar cognitive affective syndrome or Schmahmann's syndrome has been described in adults and children. Estimates based on functional mapping of the cerebellum using functional MRI suggest that more than half of the cerebellar cortex is interconnected with association zones of the cerebral cortex.

Damage to the cerebellum often causes motor-related symptoms, the details of which depend on the part of the cerebellum involved and how it is damaged. Damage to the flocculonodular lobe may show up as a loss of equilibrium and in particular an altered, irregular walking gait, with a wide stance caused by difficulty in balancing. Damage to the lateral zone typically causes problems in skilled voluntary and planned movements which can cause errors in the force, direction, speed and amplitude of movements. Other manifestations include hypotonia (decreased muscle tone), dysarthria (problems with speech articulation), dysmetria (problems judging distances or ranges of movement), dysdiadochokinesia (inability to perform rapid alternating movements such as walking), impaired check reflex or rebound phenomenon, and intention tremor (involuntary movement caused by alternating contractions of opposing muscle groups). Damage to the midline portion may disrupt whole-body movements, whereas damage localized more laterally is more likely to disrupt fine movements of the hands or limbs. Damage to the upper part of the cerebellum tends to cause gait impairments and other problems with leg coordination; damage to the lower part is more likely to cause uncoordinated or poorly aimed movements of the arms and hands, as well as difficulties in speed. This complex of motor symptoms is called ataxia.

The cerebellum is provided with blood from three paired major arteries: the superior cerebellar artery (SCA), the anterior inferior cerebellar artery (AICA), and the posterior inferior cerebellar artery (PICA). The SCA supplies the upper region of the cerebellum. It divides at the upper surface and branches into the pia mater where the branches anastomose with those of the anterior and posterior inferior cerebellar arteries. The AICA supplies the front part of the undersurface of the cerebellum. The PICA arrives at the undersurface, where it divides into a medial branch and a lateral branch. The medial branch continues backward to the cerebellar notch between the two hemispheres of the cerebellum; while the lateral branch supplies the under surface of the cerebellum, as far as its lateral border, where it anastomoses with the AICA and the SCA.

### Brainstem

The brainstem lies beneath the cerebrum and consists of the midbrain, pons and medulla. It lies in the back part of the skull, resting on the part of the base known as the clivus, and ends at the foramen magnum, a large opening in the occipital bone. The brainstem continues below this as the spinal cord, protected by the vertebral column.

Ten of the twelve pairs of cranial nerves emerge directly from the brainstem. The brainstem also contains many cranial nerve nuclei and nuclei of peripheral nerves, as well as nuclei involved in the regulation of many essential processes including breathing, control of eye movements and balance. The reticular formation, a network of nuclei of ill-defined formation, is present within and along the length of the brainstem. Many nerve tracts, which transmit information to and from the cerebral cortex to the rest of the body, pass through the brainstem.

Cerebrospinal fluid is a clear, colourless transcellular fluid that circulates around the brain in the subarachnoid space, in the ventricular system, and in the central canal of the spinal cord. It also fills some gaps in the subarachnoid space, known as subarachnoid cisterns. The four ventricles, two lateral, a third, and a fourth ventricle, all contain choroid plexus that produces cerebrospinal fluid. The third ventricle lies in the midline and is connected to the lateral ventricles. A single duct, the cerebral aqueduct between the pons and the cerebellum, connects the third ventricle to the fourth ventricle. Three separate openings, the middle and two lateral apertures, drain the cerebrospinal fluid from the fourth ventricle to the cisterna magna one of the major cisterns. From here, cerebrospinal fluid circulates around the brain and spinal cord in the subarachnoid space, between the arachnoid mater and pia mater. At any one time, there is about 150mL of cerebrospinal fluid – most within the subarachnoid space. It is constantly being regenerated and absorbed, and is replaced about once every 5–6 hours.

The internal carotid arteries supply oxygenated blood to the front of the brain and the vertebral arteries supply blood to the back of the brain. These two circulations join together in the circle of Willis, a ring of connected arteries that lies in the interpeduncular cistern between the midbrain and pons.

The internal carotid arteries are branches of the common carotid arteries. They enter the cranium through the carotid canal, travel through the cavernous sinus and enter the subarachnoid space. They then enter the circle of Willis, with two branches, the anterior cerebral arteries emerging. These branches travel forward and then upward along the longitudinal fissure, and supply the front and midline parts of the brain. One or more small anterior communicating arteries join the two anterior cerebral arteries shortly after they emerge as branches. The internal carotid arteries continue forward as the middle cerebral arteries. They travel sideways along the sphenoid bone of the eye socket, then upwards through the insula cortex, where final branches arise. The middle cerebral arteries send branches along their length.

The vertebral arteries emerge as branches of the left and right subclavian arteries. They travel upward through transverse foramina which are spaces in the cervical vertebrae. Each side enters the cranial cavity through the foramen magnum along the corresponding side of the medulla. They give off one of the three cerebellar branches. The vertebral arteries join in front of the middle part of the medulla to form the larger basilar artery, which sends multiple branches to supply the medulla and pons, and the two other anterior and superior cerebellar branches. Finally, the basilar artery divides into two posterior cerebral arteries. These travel outwards, around the superior cerebellar peduncles, and along the top of the cerebellar tentorium, where it sends branches to supply the temporal and occipital lobes. Each posterior cerebral artery sends a small posterior communicating artery to join with the internal carotid arteries.

## Spinal cord

The spinal cord is a long, thin, tubular structure made up of nervous tissue, which extends from the medulla oblongata in the brainstem to the lumbar region of the vertebral column. It encloses the central canal of the spinal cord, which contains cerebrospinal fluid. The brain and spinal cord together make up the central nervous system (CNS). In humans, the spinal cord begins at the occipital bone, passing through the foramen magnum and entering the spinal canal at the beginning of the cervical vertebrae. The spinal cord extends down to between the first and second lumbar vertebrae, where it ends. The enclosing bony vertebral column protects the relatively shorter spinal cord. It is around 45 cm (18 in) in men and around 43 cm (17 in) long in women. The diameter of the spinal cord ranges from 13 mm (1⁄2 in) in the cervical and lumbar regions to 6.4 mm (1⁄4 in) in the thoracic area.

The spinal cord functions primarily in the transmission of nerve signals from the motor cortex to the body, and from the afferent fibers of the sensory neurons to the sensory cortex. It is also a center for coordinating many reflexes and contains reflex arcs that can independently control reflexes. It is also the location of groups of spinal interneurons that make up the neural circuits known as central pattern generators. These circuits are responsible for controlling motor instructions for rhythmic movements such as walking.

The spinal cord is the main pathway for information connecting the brain and peripheral nervous system. Much shorter than its protecting spinal column, the human spinal cord originates in the brainstem, passes through the foramen magnum, and continues through to the conus medullaris near the second lumbar vertebra before terminating in a fibrous extension known as the filum terminale.

It is about 45 cm (18 in) long in men and around 43 cm (17 in) in women, ovoid-shaped, and is enlarged in the cervical and lumbar regions. The cervical enlargement, stretching from the C5 to T1 vertebrae, is where sensory input comes from and motor output goes to the arms and trunk. The lumbar enlargement, located between L1 and S3, handles sensory input and motor output coming from and going to the legs.

The spinal cord is continuous with the caudal portion of the medulla, running from the base of the skull to the body of the first lumbar vertebra. It does not run the full length of the vertebral column in adults. It is made of 31 segments from which branch one pair of sensory nerve roots and one pair of motor nerve roots. The nerve roots then merge into bilaterally symmetrical pairs of spinal nerves. The peripheral nervous system is made up of these spinal roots, nerves, and ganglia.

The dorsal roots are afferent fascicles, receiving sensory information from the skin, muscles, and visceral organs to be relayed to the brain. The roots terminate in dorsal root ganglia, which are composed of the cell bodies of the corresponding neurons. Ventral roots consist of efferent fibers that arise from motor neurons whose cell bodies are found in the ventral (or anterior) gray horns of the spinal cord.

The cord is stabilized within the dura mater by the connecting denticulate ligaments, which extend from the enveloping pia mater laterally between the dorsal and ventral roots. The dural sac ends at the vertebral level of the second sacral vertebra.

In cross-section, the peripheral region of the cord contains neuronal white matter tracts containing sensory and motor axons. Internal to this peripheral region is the grey matter, which contains the nerve cell bodies arranged in the three grey columns that give the region its butterfly-shape. This central region surrounds the central canal, which is an extension of the fourth ventricle and contains cerebrospinal fluid.

The spinal cord is elliptical in cross section, being compressed dorsolaterally. Two prominent grooves, or sulci, run along its length. The posterior median sulcus is the groove in the dorsal side, and the anterior median fissure is the groove in the ventral side.

The human spinal cord is divided into segments where pairs of spinal nerves (mixed; sensory and motor) form. Six to eight motor nerve rootlets branch out of right and left ventro lateral sulci in a very orderly manner. Nerve rootlets combine to form nerve roots. Likewise, sensory nerve rootlets form off right and left dorsal lateral sulci and form sensory nerve roots. The ventral (motor) and dorsal (sensory) roots combine to form spinal nerves (mixed; motor and sensory), one on each side of the spinal cord. Spinal nerves, with the exception of C1 and C2, form inside the intervertebral foramen (IVF). These rootlets form the demarcation between the central and peripheral nervous systems.

The grey column, (as three regions of grey columns) in the center of the cord, is shaped like a butterfly and consists of cell bodies of interneurons, motor neurons, neuroglia cells and unmyelinated axons. The anterior and posterior grey column present as projections of the grey matter and are also known as the horns of the spinal cord. Together, the grey columns and the gray commissure form the "grey H."

The white matter is located outside of the grey matter and consists almost totally of myelinated motor and sensory axons. "Columns" of white matter carry information either up or down the spinal cord.

The spinal cord proper terminates in a region called the conus medullaris, while the pia mater continues as an extension called the filum terminale, which anchors the spinal cord to the coccyx. The cauda equina ("horse's tail") is a collection of nerves inferior to the conus medullaris that continue to travel through the vertebral column to the coccyx. The cauda equina forms because the spinal cord stops growing in length at about age four, even though the vertebral column continues to lengthen until adulthood. This results in sacral spinal nerves originating in the upper lumbar region.

Within the CNS, nerve cell bodies are generally organized into functional clusters, called nuclei. Axons within the CNS are grouped into tracts.

There are 31 spinal cord nerve segments in a human spinal cord:

* 8 cervical segments forming 8 pairs of cervical nerves (C1 spinal nerves exit the spinal column between the foramen magnum and the C1 vertebra; C2 nerves exit between the posterior arch of the C1 vertebra and the lamina of C2; C3–C8 spinal nerves pass through the IVF above their corresponding cervical vertebrae, with the exception of the C8 pair which exit between the C7 and T1 vertebrae)
* 12 thoracic segments forming 12 pairs of thoracic nerves
* 5 lumbar segments forming 5 pairs of lumbar nerves
* 5 sacral segments forming 5 pairs of sacral nerves
* 1 coccygeal segment

There are two regions where the spinal cord enlarges:

* Cervical enlargement – corresponds roughly to the brachial plexus nerves, which innervate the upper limb. It includes spinal cord segments from about C4 to T1. The vertebral levels of the enlargement are roughly the same (C4 to T1).
* Lumbar enlargement – corresponds to the lumbosacral plexus nerves, which innervate the lower limb. It comprises the spinal cord segments from L2 to S3 and is found about the vertebral levels of T9 to T12.

The spinal cord is made from part of the neural tube during development. There are four stages of the spinal cord that arises from the neural tube: The neural plate, neural fold, neural tube, and the spinal cord. Neural differentiation occurs within the spinal cord portion of the tube. As the neural tube begins to develop, the notochord begins to secrete a factor known as Sonic hedgehog or SHH. As a result, the floor plate then also begins to secrete SHH, and this will induce the basal plate to develop motor neurons. During the maturation of the neural tube, its lateral walls thicken and form a longtitudinal groove called the sulcus limitans. This extends the length of the spinal cord into dorsal and ventral portions as well. Meanwhile, the overlying ectoderm secretes bone morphogenetic protein (BMP). This induces the roof plate to begin to secrete BMP, which will induce the alar plate to develop sensory neurons. Opposing gradients of such morphogens as BMP and SHH form different domains of dividing cells along the dorsal ventral axis. Dorsal root ganglion neurons differentiate from neural crest progenitors. As the dorsal and ventral column cells proliferate, the lumen of the neural tube narrows to form the small central canal of the spinal cord. The alar plate and the basal plate are separated by the sulcus limitans. Additionally, the floor plate also secretes netrins. The netrins act as chemoattractants to decussation of pain and temperature sensory neurons in the alar plate across the anterior white commissure, where they then ascend towards the thalamus. Following the closure of the caudal neuropore and formation of the brain's ventricles that contain the choroid plexus tissue, the central canal of the caudal spinal cord is filled with cerebrospinal fluid.

Earlier findings by Viktor Hamburger and Rita Levi-Montalcini in the chick embryo have been confirmed by more recent studies which have demonstrated that the elimination of neuronal cells by programmed cell death (PCD) is necessary for the correct assembly of the nervous system.

Overall, spontaneous embryonic activity has been shown to play a role in neuron and muscle development but is probably not involved in the initial formation of connections between spinal neurons.

The spinal cord is supplied with blood by three arteries that run along its length starting in the brain, and many arteries that approach it through the sides of the spinal column. The three longitudinal arteries are the anterior spinal artery, and the right and left posterior spinal arteries. These travel in the subarachnoid space and send branches into the spinal cord. They form anastamoses (connections) via the anterior and posterior segmental medullary arteries, which enter the spinal cord at various points along its length. The actual blood flow caudally through these arteries, derived from the posterior cerebral circulation, is inadequate to maintain the spinal cord beyond the cervical segments.

The major contribution to the arterial blood supply of the spinal cord below the cervical region comes from the radially arranged posterior and anterior radicular arteries, which run into the spinal cord alongside the dorsal and ventral nerve roots, but with one exception do not connect directly with any of the three longitudinal arteries. These intercostal and lumbar radicular arteries arise from the aorta, provide major anastomoses and supplement the blood flow to the spinal cord. In humans the largest of the anterior radicular arteries is known as the artery of Adamkiewicz, or anterior radicularis magna (ARM) artery, which usually arises between L1 and L2, but can arise anywhere from T9 to L5. Impaired blood flow through these critical radicular arteries, especially during surgical procedures that involve abrupt disruption of blood flow through the aorta for example during aortic aneursym repair, can result in spinal cord infarction and paraplegia.

## Central Neural Pathways

A neural pathway is the connection formed by axons that project from neurons to make synapses onto neurons in another location, to enable a signal to be sent from one region of the nervous system to another. Neurons are connected by a single axon, or by a bundle of axons known as a nerve tract, or fasciculus. Shorter neural pathways are found within grey matter in the brain, whereas longer projections, made up of myelinated axons, constitute white matter.

Descending motor pathways of the pyramidal tracts travel from the cerebral cortex to the brainstem or lower spinal cord. Ascending sensory tracts in the dorsal column–medial lemniscus pathway (DCML) carry information from the periphery to the cortex of the brain.

The first named pathways are evident to the naked eye even in a poorly preserved brain, and were named by the great anatomists of the Renaissance using cadaver material. Examples of these include the great commissures of the brain such as the corpus callosum (Latin, "hard body"; not to be confused with the Latin word "colossus" – the "huge" statue), anterior commissure, and posterior commissure. Further examples include the pyramidal tract, crus cerebri (Latin, "leg of the brain"), and cerebellar peduncles (Latin, "little foot of the cerebellum"). Note that these names describe the appearance of a structure but give one no information on its function or location.

Later, as neuroanatomical knowledge became more sophisticated, the trend was toward naming pathways by their origin and termination. For example, the nigrostriatal pathway runs from the substantia nigra (Latin, "black substance") to the corpus striatum (Latin, "striped body"). This naming can extend to include any number of structures in a pathway, such that the cerebellorubrothalamocortical pathway originates in the cerebellum, synapses in the red nucleus ("ruber" in Latin), on to the thalamus, and finally terminating in the cerebral cortex.

Sometimes, these two naming conventions coexist. For example, the name "pyramidal tract" has been mainly supplanted by lateral corticospinal tract in most texts. Note that the "old" name was primarily descriptive, evoking the pyramids of antiquity, from the appearance of this neural pathway in the medulla oblongata. The "new" name is based primarily on its origin (in the primary motor cortex, Brodmann area 4) and termination (onto the alpha motor neurons of the spinal cord).

In the cerebellum one of the two major pathways is that of the mossy fibers. Mossy fibers project directly to the deep nuclei, but also give rise to the following pathway: mossy fibers → granule cells → parallel fibers → Purkinje cells → deep nuclei. The other main pathway is from the climbing fibers and these project to Purkinje cells and also send collaterals directly to the deep nuclei.

### The Corpus callosum

The corpus callosum (Latin for "tough body"), also callosal commissure, is a wide, thick nerve tract, consisting of a flat bundle of commissural fibers, beneath the cerebral cortex in the brain. The corpus callosum is only found in placental mammals. It spans part of the longitudinal fissure, connecting the left and right cerebral hemispheres, enabling communication between them. It is the largest white matter structure in the human brain, about ten centimetres in length and consisting of 200–300 million axonal projections.

A number of separate nerve tracts, classed as subregions of the corpus callosum, connect different parts of the hemispheres. The main ones are known as the genu, the rostrum, the trunk or body, and the splenium.

The corpus callosum forms the floor of the longitudinal fissure that separates the two cerebral hemispheres. It also forms part of the roof of the lateral ventricles.

The corpus callosum has four main parts; individual nerve tracts that connect different parts of the hemispheres. These are the rostrum, the genu, the trunk or body, and the splenium. A narrowed part between the trunk and the splenium is known as the isthmus.

The front part of the corpus callosum, towards the frontal lobes is called the genu ("knee"). The genu curves downward and backward in front of the septum pellucidum, diminishing greatly in thickness. The lower much thinner part is the rostrum and is connected below with the lamina terminalis, which stretches from the interventricular foramina to the recess at the base of the optic stalk. The rostrum is named for its resemblance to a bird's beak.

The end part of the corpus callosum, towards the cerebellum, is called the splenium. This is the thickest part, and overlaps the tela choroidea of the third ventricle and the midbrain, and ends in a thick, convex, free border. Splenium translates as bandage in Greek.

The trunk of the corpus callosum lies between the splenium and the genu.

The callosal sulcus separates the corpus callosum from the cingulate gyrus.

On either side of the corpus callosum, the fibers radiate in the white matter and pass to the various parts of the cerebral cortex; those curving forward from the genu into the frontal lobes constitute the forceps minor (also forceps anterior) and those curving backward from the splenium into the occipital lobes, the forceps major (also forceps posterior). Between these two parts is the main body of the fibers which constitute the tapetum and extend laterally on either side into the temporal lobe, and cover in the central part of the lateral ventricle. The tapetum and anterior commissure share the function of connecting left and right temporal lobes.

The anterior cerebral arteries are in contact with the under surface of the rostrum, they arch over the front of the genu and are carried along the trunk, supplying the front four-fifths of the corpus callosum.

The size, amount of myelination, and density of the fibers in the subregions relate to the functions of the brain regions they connect. Myelination is the process of coating neurons with myelin, which helps the transfer of information between neurons. The process is believed to occur until an individual's thirties with peak growth in the first decade of one’s life. Thinner, lightly myelinated fibres are slower conducting and they connect the association and prefrontal areas. Thicker and fast-conducting fibers connect the visual and motor areas.

The tractogram pictured, shows the nerve tracts from six segments of the corpus callosum, providing linking of the cortical regions between the cerebral hemispheres. Those of the genu are shown in coral, of the premotor – green, of the sensory-motor – purple, of the parietal – pink, of the temporal – yellow, and of the splenium – blue.

Thinner axons in the genu connect the prefrontal cortex between the two halves of the brain; these fibres arise from a fork-like bundle of fibers from the tapetum, the forceps minor. Thicker axons in the trunk of the corpus callosum, interconnect areas of the motor cortex, with proportionately more of the corpus callosum dedicated to supplementary motor regions including Broca's area. The splenium, communicates somatosensory information between the two halves of the parietal lobe and the visual cortex at the occipital lobe, these are the fibres of the forceps major.

In a study of five- to eighteen-year-olds there was found to be a positive correlation between age and callosal thickness.

### The Pyramidal tracts

The pyramidal tracts include both the corticobulbar tract and the corticospinal tract. These are aggregations of efferent nerve fibers from the upper motor neurons that travel from the cerebral cortex and terminate either in the brainstem (corticobulbar) or spinal cord (corticospinal) and are involved in the control of motor functions of the body.

The corticobulbar tract conducts impulses from the brain to the cranial nerves. These nerves control the muscles of the face and neck and are involved in facial expression, mastication, swallowing, and other functions.

The corticospinal tract conducts impulses from the brain to the spinal cord. It is made up of a lateral and anterior tract. The corticospinal tract is involved in voluntary movement. The majority of fibres of the corticospinal tract cross over in the medulla oblongata, resulting in muscles being controlled by the opposite side of the brain. The corticospinal tract also contains the axons of Betz cells (the largest pyramidal cells) located in the primary motor cortex.

The pyramidal tracts are named because they pass through the pyramids of the medulla oblongata. The corticospinal fibers when descending from the internal capsule to the brain stem, converge to a point from multiple directions giving the impression of an inverted pyramid.

The myelination of the pyramidal fibres is incomplete at birth and gradually progresses in cranio-caudal direction and thereby progressively gaining functionality. Most of the myelination is complete by two years of age and thereafter it progresses very slowly in cranio-caudal direction up to twelve years of age.

The term pyramidal tracts refers to upper motor neurons that originate in the cerebral cortex and terminate in the spinal cord (corticospinal) or brainstem (corticobulbar). Nerves emerge in the cerebral cortex, pass down and may cross sides in the medulla oblongata, and travel as part of the spinal cord until they synapse with interneurons in the grey column of the spinal cord.

There is some variation in terminology. The pyramidal tracts definitively encompass the corticospinal tracts, and many authors also include the corticobulbar tracts.

### Corticospinal tract

Nerve fibres in the corticospinal tract originate from pyramidal cells in layer V of the cerebral cortex. Fibres arise from the primary motor cortex (about 30%), supplementary motor area and the premotor cortex (together also about 30%), and the somatosensory cortex, parietal lobe, and cingulate gyrus supplies the rest. The cells have their bodies in the cerebral cortex, and the axons form the bulk of the pyramidal tracts. The nerve axons travel from the cortex through the posterior limb of internal capsule, through the cerebral peduncle and into the brainstem and anterior medulla oblongata. Here they form two prominences called the medulla oblongatary pyramids. Below the prominences, the majority of axons cross over to the opposite side from which they originated, known as decussation. The axons that cross over move to the outer part of the medulla oblongata and form the lateral corticospinal tract, whereas the fibres that remain form the anterior corticospinal tract. About 80% of axons cross over and form the lateral corticospinal tract; 10% do not cross over and join the tract, and 10% of fibres travel in the anterior corticospinal tract.

The nerve axons traveling down the tract are the efferent nerve fibers of the upper motor neurons. These axons travel down the tracts in the white matter of the spinal cord until they reach the vertebral level of the muscle that they will innervate. At this point, the axons synapse with lower motor neurons. The majority of axons do not directly synapse with lower motor neurons, but instead synapse with an interneuron that then synapses with a lower motor neuron. This generally occurs in the anterior grey column. Nerve axons of the lateral corticospinal tract that did not cross over in the medulla oblongata do so at the level of the spinal cord they terminate in.

These tracts contain more than 1 million axons and the majority of the axons are myelinated. The corticospinal tracts myelinate largely during the first and second years after birth. The majority of nerve axons are small (<4μm) in diameter. About 3% of nerve axons have a much larger diameter (16μm) and arise from Betz cells, mostly in the leg area of the primary motor cortex. These cells are notable because of their rapid conduction rate, over 70m/sec, the fastest conduction of any signals from the brain to the spinal cord.

### Corticobulbar tract

Fibres from the ventral motor cortex travel with the corticospinal tract through the internal capsule, but terminate in a number of locations in the midbrain (cortico-mesencephalic tract), pons (Corticopontine tract), and medulla oblongata (cortico-bulbar tract). The upper motor neurons of the corticobulbar tract synapse with interneurons or directly with the lower motor neurons located in the motor cranial nerve nuclei, namely oculomotor, trochlear, motor nucleus of the trigeminal nerve, abducens, facial nerve and accessory and in the nucleus ambiguus to the hypoglossal, vagus and accessory nerves. These nuclei are supplied by nerves from both sides of the brain, with the exception of the parts of the facial nerve that control muscles of the lower face. These muscles are only innervated by nerves from the contralateral (opposite) side of the cortex.

The nerves within the corticospinal tract are involved in movement of muscles of the body. Because of the crossing-over of fibres, muscles are supplied by the side of the brain opposite to that of the muscle. The nerves within the corticobulbar tract are involved in movement in muscles of the head. They are involved in swallowing, phonation, and movements of the tongue. By virtue of involvement with the facial nerve, the corticobulbar tract is also responsible for transmitting facial expression. With the exception of lower muscles of facial expression, all functions of the corticobulbar tract involve inputs from both sides of the brain.

The term extrapyramidal motor system is used to refer to tracts within the spinal cord involved in involuntary movement but not part of the pyramidal tracts. Their functions include the control of posture and muscle tone.

Damage to the fibres of the corticospinal tracts, anywhere along their course from the cerebral cortex to the lower end of the spinal cord, can cause an upper motor neuron syndrome. A few days after the injury to the upper motor neurons, a pattern of motor signs and symptoms appears, including spasticity, hyperactive reflexes, a loss of the ability to perform fine movements, and an extensor plantar response known as the Babinski sign. Symptoms generally occur alongside other sensory problems. Causes may include masses such as strokes, subdural hemorrhage, abscesses and tumours, neurodegenerative diseases such as multiple system atrophy, inflammation such as meningitis and multiple sclerosis, and trauma to the spinal cord, including from slipped discs.

If the corticobulbar tract is damaged on only one side, then only the lower face will be affected, however if there is involvement of both the left and right tracts, then the result is pseudobulbar palsy. This causes problems with swallowing, speaking, and emotional lability.

Severe disabling involuntary movements such as hemiballismus or severe chorea might exhaust the patient and become a life threatening situation. In the past, this condition was treated by partial section of the pyramidal tract either at the primary motor cortex or at the cruz cerebri (pedunculotomy).

### Corticopontine fibers

Corticopontine fibers are projections from the cerebral cortex to the pontine nuclei. Depending upon the lobe of origin, they can be classified as frontopontine fibers, parietopontine fibers, temporopontine fibers or occipitopontine fibers.

### Cerebral peduncle

The cerebral peduncles are structures at the front of the midbrain which arise from the front of the pons and contain the large ascending (sensory) and descending (motor) nerve tracts that run to and from the cerebrum from the pons. Mainly, the three common areas that give rise to the cerebral peduncles are the cerebral cortex, the spinal cord and the cerebellum. The cerebral peduncle, by most classifications, is everything in the midbrain except the tectum. The region includes the tegmentum, crus cerebri and pretectum. By this definition, the cerebral peduncles are also known as the basis pedunculi, while the large ventral bundle of efferent fibers is referred to as the cerebral crus or the pes pedunculi.

The cerebral peduncles are located on either side of the midbrain and are the frontmost part of the midbrain, and act as the connectors between the rest of the midbrain and the thalamic nuclei and thus the cerebrum. As a whole, the cerebral peduncles assists in refining motor movements, learning of new motor skills, and converting proprioceptive information into balance and posture maintenance. Important fiber tracts that run through the cerebral peduncles are: cortico-spinal, cortico-pontine, and cortico-bulbar tracts.

Damage to the cerebral peduncles results in unrefined motor skills, imbalance, and lack of proprioception.

The descending upper fibers from the internal capsule continue on through the midbrain and are then seen as the fibers in the cerebral peduncles. The cortico-pontine fibers are found in the outer and inner third of the cerebral peduncle, these are the cortical input to the pontine nuclei. The cortico-bulbar and cortico-spinal fibers are found in the middle third of the cerebral peduncle. The cortico-spinal tract exits the internal capsule and is seen in the mid portion of the cerebral peduncles.

Cranial nerve 3 (oculomotor nerve) appears ventrally between the two cerebral peduncles in the interpeduncular fossa. Cranial nerve 4 (trochlear nerve) wraps around the lowest part of the cerebral peduncle.

### Spinal tracts

The somatosensory organization of the spinal cord is divided into the dorsal column-medial lemniscus tract (the touch/proprioception/vibration sensory pathway) and the anterolateral system, or ALS (the pain/temperature sensory pathway). Both sensory pathways use three different neurons to get information from sensory receptors at the periphery to the cerebral cortex. These neurons are designated primary, secondary and tertiary sensory neurons. In both pathways, primary sensory neuron cell bodies are found in the dorsal root ganglia, and their central axons project into the spinal cord.

In the dorsal column-medial leminiscus tract, a primary neuron's axon enters the spinal cord and then enters the dorsal column. If the primary axon enters below spinal level T6, the axon travels in the fasciculus gracilis, the medial part of the column. If the axon enters above level T6, then it travels in the fasciculus cuneatus, which is lateral to the fasciculus gracilis. Either way, the primary axon ascends to the lower medulla, where it leaves its fasciculus and synapses with a secondary neuron in one of the dorsal column nuclei: either the nucleus gracilis or the nucleus cuneatus, depending on the pathway it took. At this point, the secondary axon leaves its nucleus and passes anteriorly and medially. The collection of secondary axons that do this are known as internal arcuate fibers. The internal arcuate fibers decussate and continue ascending as the contralateral medial lemniscus. Secondary axons from the medial lemniscus finally terminate in the ventral posterolateral nucleus (VPLN) of the thalamus, where they synapse with tertiary neurons. From there, tertiary neurons ascend via the posterior limb of the internal capsule and end in the primary sensory cortex.

The proprioception of the lower limbs differs from the upper limbs and upper trunk. There is a four-neuron pathway for lower limb proprioception. This pathway initially follows the dorsal spino-cerebellar pathway. It is arranged as follows: proprioceptive receptors of lower limb → peripheral process → dorsal root ganglion → central process → Clarke's column → 2nd order neuron → medulla oblongata (Caudate nucleus) → 3rd order neuron → VPLN of thalamus → 4th order neuron → posterior limb of internal capsule → corona radiata → sensory area of cerebrum.

The anterolateral system works somewhat differently. Its primary neurons axons enter the spinal cord and then ascend one to two levels before synapsing in the substantia gelatinosa. The tract that ascends before synapsing is known as Lissauer's tract. After synapsing, secondary axons decussate and ascend in the anterior lateral portion of the spinal cord as the spinothalamic tract. This tract ascends all the way to the VPLN, where it synapses on tertiary neurons. Tertiary neuronal axons then travel to the primary sensory cortex via the posterior limb of the internal capsule.

Some of the "pain fibers" in the ALS deviate from their pathway towards the VPLN. In one such deviation, axons travel towards the reticular formation in the midbrain. The reticular formation then projects to a number of places including the hippocampus (to create memories about the pain), the centromedian nucleus (to cause diffuse, non-specific pain) and various parts of the cortex. Additionally, some ALS axons project to the periaqueductal gray in the pons, and the axons forming the periaqueductal gray then project to the nucleus raphes magnus, which projects back down to where the pain signal is coming from and inhibits it. This helps control the sensation of pain to some degree.

The corticospinal tract serves as the motor pathway for upper motor neuronal signals coming from the cerebral cortex and from primitive brainstem motor nuclei.

Cortical upper motor neurons originate from Brodmann areas 1, 2, 3, 4, and 6 and then descend in the posterior limb of the internal capsule, through the crus cerebri, down through the pons, and to the medullary pyramids, where about 90% of the axons cross to the contralateral side at the decussation of the pyramids. They then descend as the lateral corticospinal tract. These axons synapse with lower motor neurons in the ventral horns of all levels of the spinal cord. The remaining 10% of axons descend on the ipsilateral side as the ventral corticospinal tract. These axons also synapse with lower motor neurons in the ventral horns. Most of them will cross to the contralateral side of the cord (via the anterior white commissure) right before synapsing.

The midbrain nuclei include four motor tracts that send upper motor neuronal axons down the spinal cord to lower motor neurons. These are the rubrospinal tract, the vestibulospinal tract, the tectospinal tract and the reticulospinal tract. The rubrospinal tract descends with the lateral corticospinal tract, and the remaining three descend with the anterior corticospinal tract.

The function of lower motor neurons can be divided into two different groups: the lateral corticospinal tract and the anterior cortical spinal tract. The lateral tract contains upper motor neuronal axons which synapse on dorsal lateral (DL) lower motor neurons. The DL neurons are involved in distal limb control. Therefore, these DL neurons are found specifically only in the cervical and lumbosacral enlargements within the spinal cord. There is no decussation in the lateral corticospinal tract after the decussation at the medullary pyramids.

The anterior corticospinal tract descends ipsilaterally in the anterior column, where the axons emerge and either synapse on lower ventromedial (VM) motor neurons in the ventral horn ipsilaterally or descussate at the anterior white commissure where they synapse on VM lower motor neurons contralaterally . The tectospinal, vestibulospinal and reticulospinal descend ipsilaterally in the anterior column but do not synapse across the anterior white commissure. Rather, they only synapse on VM lower motor neurons ipsilaterally. The VM lower motor neurons control the large, postural muscles of the axial skeleton. These lower motor neurons, unlike those of the DL, are located in the ventral horn all the way throughout the spinal cord.

### Spinocerebellar tracts

Proprioceptive information in the body travels up the spinal cord via three tracks. Below L2, the proprioceptive information travels up the spinal cord in the ventral spinocerebellar tract. Also known as the anterior spinocerebellar tract, sensory receptors take in the information and travel into the spinal cord. The cell bodies of these primary neurons are located in the dorsal root ganglia. In the spinal cord, the axons synapse and the secondary neuronal axons decussates and then travel up to the superior cerebellar peduncle where they decussate again. From here, the information is brought to deep nuclei of the cerebellum including the fastigial and interposed nuclei.

From the levels of L2 to T1, proprioceptive information enters the spinal cord and ascends ipsilaterally, where it synapses in Clarke's nucleus. The secondary neuronal axons continue to ascend ipsilaterally and then pass into the cerebellum via the inferior cerebellar peduncle. This tract is known as the dorsal spinocerebellar tract.

From above T1, proprioceptive primary axons enter the spinal cord and ascend ipsilaterally until reaching the accessory cuneate nucleus, where they synapse. The secondary axons pass into the cerebellum via the inferior cerebellar peduncle where again, these axons synapse on cerebellar deep nuclei. This tract is known as the cuneocerebellar tract.

Motor information travels from the brain down the spinal cord via descending spinal cord tracts. Descending tracts involve two neurons: the upper motor neuron (UMN) and lower motor neuron (LMN). A nerve signal travels down the upper motor neuron until it synapses with the lower motor neuron in the spinal cord. Then, the lower motor neuron conducts the nerve signal to the spinal root where efferent nerve fibers carry the motor signal toward the target muscle. The descending tracts are composed of white matter. There are several descending tracts serving different functions. The corticospinal tracts (lateral and anterior) are responsible for coordinated limb movements.

The spinal cord ends at the level of vertebrae L1–L2, while the subarachnoid space —the compartment that contains cerebrospinal fluid— extends down to the lower border of S2. Lumbar punctures in adults are usually performed between L3–L5 (cauda equina level) in order to avoid damage to the spinal cord. In the fetus, the spinal cord extends the full length of the spine and regresses as the body grows.

## Sensory maps

Sensory maps are areas of the brain which respond to sensory stimulation, and are spatially organized according to some feature of the sensory stimulation. In some cases the sensory map is simply a topographic representation of a sensory surface such as the skin, cochlea, or retina. In other cases it represents other stimulus properties resulting from neuronal computation and is generally ordered in a manner that reflects the periphery. An example is the somatosensory map which is a projection of the skin's surface in the brain that arranges the processing of tactile sensation. This type of somatotopic map is the most common, possibly because it allows for physically neighboring areas of the brain to react to physically similar stimuli in the periphery or because it allows for greater motor control.

The somatosensory cortex is adjacent to the primary motor cortex which is similarly mapped. Sensory maps may play an important role in facilitating motor responses. Other examples of sensory map organization may be that adjacent brain regions are related through proximity of the receptors that they process as in the map of the cochlea in the brain, or that similar features are processed as in the map of the feature detectors or the retinotopic map, or that time codes are used in organization as in the maps of an owl's sense of direction via interaural time difference between ears. These examples exist in contrast to non-mapped or randomly distributed patterns of processing. An example of a non-mapped sensory processing system is the olfactory system where unrelated odorants are processed side-by-side in the olfactory bulb. In addition to non-mapped and mapped processing, stimuli may be processed under multiple maps as in the human visual system.

Mapped sensory processing areas are a complex phenomenon and must therefore serve an adaptive advantage as it is highly unlikely for complex phenomena to appear otherwise. Sensory maps are also very old in evolutionary history as they are nearly ubiquitous in all species of animals and are found for nearly all sensory systems. Some advantages of sensory maps have been elucidated by scientific exploration:

Filling In: When sensory stimulation is organized in the brain in some form of topographic pattern, then the animal might be able to “fill in” information that is missing using neighboring regions of the map since they will usually be activated together when all information is present. Loss of signal from one area can be filled in from adjacent areas of the brain if those areas are for physically related parts of the periphery. This is evident in animal studies where the neurons bordering a lesioned, or damaged, brain area (which used to process the sense of touch in a hand) to recover processing of that sensory region because they process information from adjacent hand areas.[1]
Lateral Inhibition: Lateral inhibition is an organizing principle, it allows contrast in many systems from the visual to the somatosensory. This means that if adjacent areas inhibit one another then stimulation which activates one brain region can simultaneously inhibit the adjoining brain regions to create a sharper resolution between stimuli. This is evident in the visual system of humans where sharp lines can be detected between bright and dark regions because of simple cells which inhibit their neighbors.
Summation: Organization also allows related stimuli to be summed in the neural assessment of sensory information. Examples of this are found in the summation of tactile inputs neurally or visual inputs under low light.[2]


Topographic maps[edit] may be thought of as a mapping of the surface of the body onto the brain structure. Phrased another way, topographic maps are organized in the neural system in a manner that is a projection of the sensory surface onto the brain. This means that the organization in the periphery mirrors the order of the information processing in the brain. This organization can be somatotopic,[3] as in the tactile sense of touch, or tonotopic,[4] as in the ear, and the retinotopic map which is laid out in the brain as the cells are arranged on the retina.

* Wilder Penfield[5] discovered the original topographic map in the form of the internal somatosensory Homunculus. His work on human neural systems showed that the brain areas that processed tactile sensations are mapped in the same fashion that the body is laid out. This sensory map exaggerates certain regions that have many peripheral sense cells like the lips and hands while reduces the relative space for processing areas with few receptors like the back.
* Hair cells in the auditory system display tonotopic organization.[6] This tonotopic arrangement means that cells are laid out to range from low frequency to high frequency and processed in that same organization within the brain.
