# Development Of The Nervous System

The development of the nervous system, or neural development, or neurodevelopment, refers to the processes that generate, shape, and reshape the nervous system of animals, from the earliest stages of embryonic development to adulthood. The field of neural development draws on both neuroscience and developmental biology to describe and provide insight into the cellular and molecular mechanisms by which complex nervous systems develop, from nematodes and fruit flies to mammals. Defects in neural development can lead to malformations and a wide variety of sensory, motor, and cognitive impairments neurological disorders and intellectual disability.

The central nervous system (CNS) is derived from the ectoderm—the outermost tissue layer of the embryo. In the third week of human embryonic development the neuroectoderm appears and forms the neural plate along the dorsal side of the embryo. The neural plate is the source of the majority of neurons and glial cells of the CNS. A groove forms along the long axis of the neural plate and, by week four of development, the neural plate wraps in on itself to give rise to the neural tube, which is filled with cerebrospinal fluid (CSF). As the embryo develops, the anterior part of the neural tube forms three primary brain vesicles, which become the primary anatomical regions of the brain: the forebrain (prosencephalon), midbrain (mesencephalon), and hindbrain (rhombencephalon). These simple, early vesicles enlarge and further divide into the five secondary brain vesicles – the telencephalon (future cerebral cortex and basal ganglia), diencephalon (future thalamus and hypothalamus), mesencephalon (future colliculi), metencephalon (future pons and cerebellum), and myelencephalon (future medulla). The CSF-filled central chamber is continuous from the telencephalon to the spinal cord, and constitutes the developing ventricular system of the CNS. Because the neural tube gives rise to the brain and spinal cord any mutations at this stage in development can lead to fatal deformities like anencephaly or lifelong disabilities like spina bifida. During this time, the walls of the neural tube contain neural stem cells, which drive brain growth as they divide many times. Gradually some of the cells stop dividing and differentiate into neurons and glial cells, which are the main cellular components of the CNS. The newly generated neurons migrate to different parts of the developing brain to self-organize into different brain structures. Once the neurons have reached their regional positions, they extend axons and dendrites, which allow them to communicate with other neurons via synapses. Synaptic communication between neurons leads to the establishment of functional neural circuits that mediate sensory and motor processing, and underlie behavior.

## Neural Induction

During early embryonic development the ectoderm becomes specified to give rise to the epidermis (skin) and the neural plate. The conversion of undifferentiated ectoderm to neuro-ectoderm requires signals from the mesoderm. At the onset of gastrulation presumptive mesodermal cells move through the dorsal blastopore lip and form a layer in between the endoderm and the ectoderm. These mesodermal cells that migrate along the dorsal midline give rise to a structure called the notochord. Ectodermal cells overlying the notochord develop into the neural plate in response to a diffusible signal produced by the notochord. The remainder of the ectoderm gives rise to the epidermis (skin). The ability of the mesoderm to convert the overlying ectoderm into neural tissue is called neural induction.

The neural plate folds outwards during the third week of gestation to form the neural groove. Beginning in the future neck region, the neural folds of this groove close to create the neural tube. The formation of the neural tube from the ectoderm is called neurulation. The ventral part of the neural tube is called the basal plate; the dorsal part is called the alar plate. The hollow interior is called the neural canal. By the end of the fourth week of gestation, the open ends of the neural tube, called the neuropores, close off.

A transplanted blastopore lip can convert ectoderm into neural tissue and is said to have an inductive effect. Neural inducers are molecules that can induce the expression of neural genes in ectoderm explants without inducing mesodermal genes as well. Neural induction is often studied in *Xenopus laevis* embryos since they have a simple body pattern and there are good markers to distinguish between neural and non-neural tissue. Examples of neural inducers are the molecules noggin and chordin.

When embryonic ectodermal cells are cultured at low density in the absence of mesodermal cells they undergo neural differentiation (express neural genes), suggesting that neural differentiation is the default fate of ectodermal cells. In explant cultures (which allow direct cell-cell interactions) the same cells differentiate into epidermis. This is due to the action of BMP4 (a TGF-β family protein) that induces ectodermal cultures to differentiate into epidermis. During neural induction, noggin and chordin are produced by the dorsal mesoderm (notochord) and diffuse into the overlying ectoderm to inhibit the activity of BMP4. This inhibition of BMP4 causes the cells to differentiate into neural cells. Inhibition of TGF-β and BMP (bone morphogenetic protein) signaling can efficiently induce neural tissue from human pluripotent stem cells, a model of early human development.

## The Early Brain

Late in the fourth week, the superior part of the neural tube flexes at the level of the future midbrain—the mesencephalon. Above the mesencephalon is the prosencephalon (future forebrain) and beneath it is the rhombencephalon (future hindbrain). The optical vesicle (which will eventually become the optic nerve, retina and iris) forms at the basal plate of the prosencephalon.

The spinal cord forms from the lower part of the neural tube. The wall of the neural tube consists of neuroepithelial cells, which differentiate into neuroblasts, forming the mantle layer (the gray matter). Nerve fibers emerge from these neuroblasts to form the marginal layer (the white matter). The ventral part of the mantle layer (the basal plates) forms the motor areas of the spinal cord, whilst the dorsal part (the alar plates) forms the sensory areas. Between the basal and alar plates is an intermediate layer that contains neurons of the autonomic nervous system.

In the fifth week, the alar plate of the prosencephalon expands to form the cerebral hemispheres (the telencephalon). The basal plate becomes the diencephalon.

The diencephalon, mesencephalon and rhombencephalon constitute the brain stem of the embryo. It continues to flex at the mesencephalon. The rhombencephalon folds posteriorly, which causes its alar plate to flare and form the fourth ventricle of the brain. The pons and the cerebellum form in the upper part of the rhombencephalon, whilst the medulla oblongata forms in the lower part.

Some landmarks of neural development include the birth and differentiation of neurons from stem cell precursors, the migration of immature neurons from their birthplaces in the embryo to their final positions, outgrowth of axons and dendrites from neurons, guidance of the motile growth cone through the embryo towards postsynaptic partners, the generation of synapses between these axons and their postsynaptic partners, and finally the lifelong changes in synapses, which are thought to underlie learning and memory.

Typically, these neurodevelopmental processes can be broadly divided into two classes: activity-independent mechanisms and activity-dependent mechanisms. Activity-independent mechanisms are generally believed to occur as hardwired processes determined by genetic programs played out within individual neurons. These include differentiation, migration and axon guidance to their initial target areas. These processes are thought of as being independent of neural activity and sensory experience. Once axons reach their target areas, activity-dependent mechanisms come into play. Although synapse formation is an activity-independent event, modification of synapses and synapse elimination requires neural activity.

Developmental neuroscience uses a variety of animal models including the mouse *Mus musculus*, the fruit fly *Drosophila melanogaster*, the zebrafish *Danio rerio*, the frog Xenopus laevis, and the roundworm *Caenorhabditis elegans*.

Myelination, formation of the lipid myelin bilayer around neuronal axons, is a process that is essential for normal brain function. The myelin sheath provides insulation for the nerve impulse when communicating between neural systems. Without it, the impulse would be disrupted and the signal would not reach its target, thus impairing normal functioning. 

## Patterning Of The Nervous System

In chordates, dorsal ectoderm forms all neural tissue and the nervous system. Patterning occurs due to specific environmental conditions - different concentrations of signaling molecules

The ventral half of the neural plate is controlled by the notochord, which acts as the 'organiser'. The dorsal half is controlled by the ectoderm plate, which flanks either side of the neural plate.

Ectoderm follows a default pathway to become neural tissue. Evidence for this comes from single, cultured cells of ectoderm, which go on to form neural tissue. This is postulated to be because of a lack of BMPs, which are blocked by the organiser. The organiser may produce molecules such as follistatin, noggin and chordin that inhibit BMPs.

The ventral neural tube is patterned by sonic hedgehog (Shh) from the notochord, which acts as the inducing tissue. Notochord-derived Shh signals to the floor plate, and induces Shh expression in the floor plate. Floor plate-derived Shh subsequently signals to other cells in the neural tube, and is essential for proper specification of ventral neuron progenitor domains. Loss of Shh from the notochord and/or floor plate prevents proper specification of these progenitor domains. Shh binds Patched1, relieving Patched-mediated inhibition of Smoothened, leading to activation of the Gli family of transcription factors (GLI1, GLI2, and GLI3).

In this context Shh acts as a morphogen - it induces cell differentiation dependent on its concentration. At low concentrations it forms ventral interneurons, at higher concentrations it induces motor neuron development, and at highest concentrations it induces floor plate differentiation. Failure of Shh-modulated differentiation causes holoprosencephaly, a disorder in which the prosencephalon (the forebrain of the embryo) fails to develop into two hemispheres.

The dorsal neural tube is patterned by BMPs from the epidermal ectoderm flanking the neural plate. These induce sensory interneurons by activating Sr/Thr kinases and altering SMAD transcription factor levels.

Signals that control anteroposterior neural development include FGF and retinoic acid, which act in the hindbrain and spinal cord. The hindbrain, for example, is patterned by Hox genes, which are expressed in overlapping domains along the anteroposterior axis under the control of retinoic acid. The 3′ (3 prime end) genes in the Hox cluster are induced by retinoic acid in the hindbrain, whereas the 5′ (5 prime end) Hox genes are not induced by retinoic acid and are expressed more posteriorly in the spinal cord. Hoxb-1 is expressed in rhombomere 4 and gives rise to the facial nerve. Without this Hoxb-1 expression, a nerve similar to the trigeminal nerve arises.

## Neurogenesis

Neurogenesis is the process by which neurons are generated from neural stem cells and progenitor cells. Neurons are 'post-mitotic', meaning that they will never divide again for the lifetime of the organism.

Epigenetic modifications play a key role in regulating gene expression in differentiating neural stem cells and are critical for cell fate determination in the developing and adult mammalian brain. Epigenetic modifications include DNA cytosine methylation to form 5-methylcytosine and 5-methylcytosine demethylation. DNA cytosine methylation is catalyzed by DNA methyltransferases (DNMTs). Methylcytosine demethylation is catalyzed in several sequential steps by TET (**T**en-**e**leven **t**ranslocation methylcytosine dioxygenase) enzymes that carry out oxidative reactions (e.g. 5-methylcytosine to 5-hydroxymethylcytosine) and enzymes of the DNA base excision repair (BER) pathway.

## Neuronal Migration

Neuronal precursor cells proliferate in the ventricular zone of the developing neocortex, where the principal neural stem cell is the radial glial cell. The first postmitotic cells must leave the stem cell niche and migrate outward to form the preplate, which is destined to become Cajal-Retzius cells and subplate neurons. These cells do so by somal translocation. Neurons migrating with this mode of locomotion are bipolar and attach the leading edge of the process to the pia. The soma is then transported to the pial surface by nucleokinesis, a process by which a microtubule "cage" around the nucleus elongates and contracts in association with the centrosome to guide the nucleus to its final destination. Radial glial cells, whose fibers serve as a scaffolding for migrating cells and a means of radial communication mediated by calcium dynamic activity, act as the main excitatory neuronal stem cell of the cerebral cortex or translocate to the cortical plate and differentiate either into astrocytes or neurons. Somal translocation can occur at any time during development.

Subsequent waves of neurons split the preplate by migrating along radial glial fibres to form the cortical plate. Each wave of migrating cells travel past their predecessors forming layers in an inside-out manner, meaning that the youngest neurons are the closest to the surface. 

Most interneurons migrate tangentially through multiple modes of migration to reach their appropriate location in the cortex. An example of tangential migration is the movement of interneurons from the ganglionic eminence to the cerebral cortex. One example of ongoing tangential migration in a mature organism, observed in some animals, is the rostral migratory stream connecting subventricular zone and olfactory bulb.

Many neurons migrating along the anterior-posterior axis of the body use existing axon tracts to migrate along; this is called axophilic migration. An example of this mode of migration is in GnRH-expressing neurons, which make a long journey from their birthplace in the nose, through the forebrain, and into the hypothalamus. Many of the mechanisms of this migration have been worked out, starting with the extracellular guidance cues that trigger intracellular signaling. These intracellular signals, such as calcium signaling, lead to actin  and microtubule cytoskeletal dynamics, which produce cellular forces that interact with the extracellular environment through cell adhesion proteins  to cause the movement of these cells.

## Neurotrophic Factors

The survival of neurons is regulated by survival factors, called trophic factors. The neurotrophic hypothesis was formulated by [Viktor Hamburger](https://en.wikipedia.org/wiki/Viktor_Hamburger) and [Rita Levi Montalcini](https://en.wikipedia.org/wiki/Rita_Levi-Montalcini) based on studies of the developing nervous system. Victor Hamburger discovered that implanting an extra limb in the developing chick led to an increase in the number of spinal motor neurons. Initially he thought that the extra limb was inducing proliferation of motor neurons, but he and his colleagues later showed that there was a great deal of motor neuron death during normal development, and the extra limb prevented this cell death. According to the neurotrophic hypothesis, growing axons compete for limiting amounts of target-derived trophic factors and axons that fail to receive sufficient trophic support die by apoptosis. It is now clear that factors produced by a number of sources contribute to neuronal survival.

* Nerve Growth Factor (NGF): Rita Levi Montalcini and [Stanley Cohen](https://en.wikipedia.org/wiki/Stanley_Cohen_(biochemist)) purified the first trophic factor, Nerve Growth Factor, for which they received the Nobel Prize. There are three NGF-related trophic factors: BDNF, NT3, and NT4, which regulate survival of various neuronal populations. The Trk proteins act as receptors for NGF and related factors. Trk is a receptor tyrosine kinase. Trk dimerization and phosphorylation leads to activation of various intracellular signaling pathways including the MAP kinase, Akt, and PKC pathways.
* CNTF: Ciliary neurotrophic factor is another protein that acts as a survival factor for motor neurons. CNTF acts via a receptor complex that includes CNTFRα, GP130, and LIFRβ. Activation of the receptor leads to phosphorylation and recruitment of the JAK kinase, which in turn phosphorylates LIFRβ. LIFRβ acts as a docking site for the STAT transcription factors. JAK kinase phosphorylates STAT proteins, which dissociate from the receptor and translocate to the nucleus to regulate gene expression.
* GDNF: Glial derived neurotrophic factor is a member of the TGFb family of proteins, and is a potent trophic factor for striatal neurons. The functional receptor is a heterodimer, composed of type 1 and type 2 receptors. Activation of the type 1 receptor leads to phosphorylation of Smad proteins, which translocate to the nucleus to activate gene expression.

## Activity Dependent Mechanisms In The Assembly Of Neural Circuits

The processes of neuronal migration, differentiation and axon guidance are generally believed to be activity-independent mechanisms and rely on hard-wired genetic programs in the neurons themselves. Research findings however have implicated a role for activity-dependent mechanisms in mediating some aspects of these processes such as the rate of neuronal migration, aspects of neuronal differentiation and axon pathfinding. Activity-dependent mechanisms influence neural circuit development and are crucial for laying out early connectivity maps and the continued refinement of synapses which occurs during development. There are two distinct types of neural activity we observe in developing circuits -early spontaneous activity and sensory-evoked activity. Spontaneous activity occurs early during neural circuit development even when sensory input is absent and is observed in many systems such as the developing visual system, auditory system, motor system, hippocampus, cerebellum and neocortex.

Experimental techniques such as direct electrophysiological recording, fluorescence imaging using calcium indicators and optogenetic techniques have shed light on the nature and function of these early bursts of activity. They have distinct spatial and temporal patterns during development and their ablation during development has been known to result in deficits in network refinement in the visual system. In the immature retina, waves of spontaneous action potentials arise from the retinal ganglion cells and sweep across the retinal surface in the first few postnatal weeks. These waves are mediated by neurotransmitter acetylcholine in the initial phase and later on by glutamate. They are thought to instruct the formation of two sensory maps- the retinotopic map and eye-specific segregation. Retinotopic map refinement occurs in downstream visual targets in the brain-the superior colliculus (SC) and dorsal lateral geniculate nucleus (LGN). Pharmacological disruption and mouse models lacking the β2 subunit of the nicotinic acetylcholine receptor has shown that the lack of spontaneous activity leads to marked defects in retinotopy and eye-specific segregation.

In the developing auditory system, developing cochlea generate bursts of activity which spreads across the inner hair cells and spiral ganglion neurons which relay auditory information to the brain. ATP release from supporting cells triggers action potentials in inner hair cells. In the auditory system, spontaneous activity is thought to be involved in tonotopic map formation by segregating cochlear neuron axons tuned to high and low frequencies. In the motor system, periodic bursts of spontaneous activity are driven by excitatory GABA and glutamate during the early stages and by acetylcholine and glutamate at later stages. In the cortex, early waves of activity have been observed in the cerebellum and cortical slices. Once sensory stimulus becomes available, final fine-tuning of sensory-coding maps and circuit refinement begins to rely more and more on sensory-evoked activity as demonstrated by classic experiments about the effects of sensory deprivation during critical periods.
