# The Gustatory System


Taste, gustatory perception, or gustation (Adjectival form: gustatory) is one of the five traditional senses that belongs to the gustatory system.

Taste is the sensation produced or stimulated when a substance in the mouth reacts chemically with taste receptor cells located on taste buds in the oral cavity, mostly on the tongue. Taste, along with smell (olfaction) and trigeminal nerve stimulation (registering texture, pain, and temperature), determines flavors of food and/or other substances. Humans have taste receptors on taste buds (gustatory calyculi) and other areas including the upper surface of the tongue and the epiglottis. The gustatory cortex is responsible for the perception of taste.

The tongue is covered with thousands of small bumps called papillae, which are visible to the naked eye. Within each papilla are hundreds of taste buds. The exception to this is the filiform papillae that do not contain taste buds. There are between 2000 and 5000 taste buds that are located on the back and front of the tongue. Others are located on the roof, sides and back of the mouth, and in the throat. Each taste bud contains 50 to 100 taste receptor cells.

The sensation of taste includes five established basic tastes: sweetness, sourness, saltiness, bitterness, and savoriness (also known as savory or umami). Scientific experiments have demonstrated that these five tastes exist and are distinct from one another. Taste buds are able to distinguish between different tastes through detecting interaction with different molecules or ions. Sweet, savoriness, and bitter tastes are triggered by the binding of molecules to G protein-coupled receptors on the cell membranes of taste buds. Saltiness and sourness are perceived when alkali metal or hydrogen ions enter taste buds, respectively.

The basic tastes contribute only partially to the sensation and flavor of food in the mouth—other factors include smell, detected by the olfactory epithelium of the nose; texture, detected through a variety of mechanoreceptors, muscle nerves, etc.; temperature, detected by thermoreceptors; and "coolness" (such as of menthol) and "hotness" (pungency), through chemesthesis.

As taste senses both harmful and beneficial things, all basic tastes are classified as either aversive or appetitive, depending upon the effect the things they sense have on our bodies. Sweetness helps to identify energy-rich foods, while bitterness serves as a warning sign of poisons.

Among humans, taste perception begins to fade around 50 years of age because of loss of tongue papillae and a general decrease in saliva production. Humans can also have distortion of tastes through dysgeusia. Not all mammals share the same taste senses: some rodents can taste starch (which humans cannot), cats cannot taste sweetness, and several other carnivores including hyenas, dolphins, and sea lions, have lost the ability to sense up to four of their ancestral five taste senses.


Taste in the gustatory system allows humans to distinguish between safe and harmful food, and to gauge foods’ nutritional value. Digestive enzymes in saliva begin to dissolve food into base chemicals that are washed over the papillae and detected as tastes by the taste buds. The tongue is covered with thousands of small bumps called papillae, which are visible to the naked eye. Within each papilla are hundreds of taste buds. The exception to this are the filiform papillae that do not contain taste buds. There are between 2000 and 5000 taste buds that are located on the back and front of the tongue. Others are located on the roof, sides and back of the mouth, and in the throat. Each taste bud contains 50 to 100 taste receptor cells.

Bitter foods are generally found unpleasant, while sour, salty, sweet, and umami tasting foods generally provide a pleasurable sensation. The five specific tastes received by taste receptors are saltiness, sweetness, bitterness, sourness, and savoriness, often known by its Japanese term "umami" which translates to ‘deliciousness’. As of the early twentieth century, Western physiologists and psychologists believed there were four basic tastes: sweetness, sourness, saltiness, and bitterness. At that time, savoriness was not identified, but now a large number of authorities recognize it as the fifth taste.

One study found that both salt and sour taste mechanisms detect, in different ways, the presence of sodium chloride (salt) in the mouth, however, acids are also detected and perceived as sour. The detection of salt is important to many organisms, but specifically mammals, as it serves a critical role in ion and water homeostasis in the body. It is specifically needed in the mammalian kidney as an osmotically active compound which facilitates passive re-uptake of water into the blood.[citation needed] Because of this, salt elicits a pleasant taste in most humans.

Sour and salt tastes can be pleasant in small quantities, but in larger quantities become more and more unpleasant to taste. For sour taste this is presumably because the sour taste can signal under-ripe fruit, rotten meat, and other spoiled foods, which can be dangerous to the body because of bacteria which grow in such media. Additionally, sour taste signals acids, which can cause serious tissue damage.

Bitter is a generally negative flavor, though its method of action is unknown. It has the characteristic of accustomed enjoyment.

Sweet taste signals the presence of carbohydrates in solution. Since carbohydrates have a very high calorie count (saccharides have many bonds, therefore much energy), they are desirable to the human body, which evolved to seek out the highest calorie intake foods. They are used as direct energy (sugars) and storage of energy (glycogen). However, there are many non-carbohydrate molecules that trigger a sweet response, leading to the development of many artificial sweeteners, including saccharin, sucralose, and aspartame. It is still unclear how these substances activate the sweet receptors and what adaptational significance this has had.

The savory taste (known in Japanese as "umami") was identified by Japanese chemist Kikunae Ikeda of Tokyo Imperial University, which signals the presence of the amino acid L-glutamate, triggers a pleasurable response and thus encourages the intake of peptides and proteins. The amino acids in proteins are used in the body to build muscles and organs, transport molecules (hemoglobin), antibodies, and the organic catalysts known as enzymes. These are all critical molecules, and as such it is important to have a steady supply of amino acids, hence the pleasurable response to their presence in the mouth.

In Asian countries within the sphere of mainly Chinese and Indian cultural influence, pungency (piquancy or hotness) had traditionally been considered a sixth basic taste. In 2015, researchers suggested a new basic taste of fatty acids called fat taste, although oleogustus and pinguis have both been proposed as alternate terms.

Sweetness
Main article: Sweetness

Sweetness, usually regarded as a pleasurable sensation, is produced by the presence of sugars and substances that mimic sugar. Sweetness may be connected to aldehydes and ketones, which contain a carbonyl group. Sweetness is detected by a variety of G protein coupled receptors (GPCR) coupled to the G protein gustducin found on the taste buds. At least two different variants of the "sweetness receptors" must be activated for the brain to register sweetness. Compounds the brain senses as sweet are compounds that can bind with varying bond strength to two different sweetness receptors. These receptors are T1R2+3 (heterodimer) and T1R3 (homodimer), which account for all sweet sensing in humans and animals. Taste detection thresholds for sweet substances are rated relative to sucrose, which has an index of 1. The average human detection threshold for sucrose is 10 millimoles per liter. For lactose it is 30 millimoles per liter, with a sweetness index of 0.3, and 5-nitro-2-propoxyaniline 0.002 millimoles per liter. “Natural” sweeteners such as saccharides activate the GPCR, which releases gustducin. The gustducin then activates the molecule adenylate cyclase, which catalyzes the production of the molecule cAMP, or adenosine 3', 5'-cyclic monophosphate. This molecule closes potassium ion channels, leading to depolarization and neurotransmitter release. Synthetic sweeteners such as saccharin activate different GPCRs and induce taste receptor cell depolarization by an alternate pathway.

Sourness
"Sour" redirects here. For other uses, see Sour (disambiguation).

Sourness is the taste that detects acidity. The sourness of substances is rated relative to dilute hydrochloric acid, which has a sourness index of 1. By comparison, tartaric acid has a sourness index of 0.7, citric acid an index of 0.46, and carbonic acid an index of 0.06.

Sour taste is detected by a small subset of cells that are distributed across all taste buds in the tongue. Sour taste cells can be identified by expression of the protein PKD2L1, although this gene is not required for sour responses. There is evidence that the protons that are abundant in sour substances can directly enter the sour taste cells through apically located ion channels. In 2018, the proton-elective ion channel otopetrin 1 (Otop1) was implicated as the primary mediator of this proton influx. This transfer of positive charge into the cell can itself trigger an electrical response. It has also been proposed that weak acids such as acetic acid, which is not fully dissociated at physiological pH values, can penetrate taste cells and thereby elicit an electrical response. According to this mechanism, intracellular hydrogen ions inhibit potassium channels, which normally function to hyperpolarize the cell. By a combination of direct intake of hydrogen ions (which itself depolarizes the cell) and the inhibition of the hyperpolarizing channel, sourness causes the taste cell to fire action potentials and release neurotransmitter.

The most common foods with natural sourness are fruits, such as lemon, grape, orange, tamarind, and bitter melon. Fermented foods, such as wine, vinegar or yogurt, may have sour taste. Children in the US and UK show a greater enjoyment of sour flavors than adults, and sour candy containing citric acid or malic acid is common.

Saltiness
"Saltiness" redirects here. For the saltiness in the water, see Salinity.
The simplest receptor found in the mouth is the sodium chloride (salt) receptor. Saltiness is a taste produced primarily by the presence of sodium ions. Other ions of the alkali metals group also taste salty, but the further from sodium, the less salty the sensation is. A sodium channel in the taste cell wall allows sodium cations to enter the cell. This on its own depolarizes the cell, and opens voltage-dependent calcium channels, flooding the cell with positive calcium ions and leading to neurotransmitter release. This sodium channel is known as an epithelial sodium channel (ENaC) and is composed of three subunits. An ENaC can be blocked by the drug amiloride in many mammals, especially rats. The sensitivity of the salt taste to amiloride in humans, however, is much less pronounced, leading to conjecture that there may be additional receptor proteins besides ENaC to be discovered.

The size of lithium and potassium ions most closely resemble those of sodium, and thus the saltiness is most similar. In contrast, rubidium and caesium ions are far larger, so their salty taste differs accordingly.[citation needed] The saltiness of substances is rated relative to sodium chloride (NaCl), which has an index of 1. Potassium, as potassium chloride (KCl), is the principal ingredient in salt substitutes and has a saltiness index of 0.6.

Other monovalent cations, e.g. ammonium (NH4+), and divalent cations of the alkali earth metal group of the periodic table, e.g. calcium (Ca2+), ions generally elicit a bitter rather than a salty taste even though they, too, can pass directly through ion channels in the tongue, generating an action potential. But the chloride of calcium is saltier and less bitter than potassium chloride, and is commonly used in pickle brine instead of KCl.

Bitterness
See also: Bitter taste evolution

Bitterness is one of the most sensitive of the tastes, and many perceive it as unpleasant, sharp, or disagreeable, but it is sometimes desirable and intentionally added via various bittering agents. Common bitter foods and beverages include coffee, unsweetened cocoa, South American mate, coca tea, bitter gourd, uncured olives, citrus peel, many plants in the family Brassicaceae, dandelion greens, horehound, wild chicory, and escarole. The ethanol in alcoholic beverages tastes bitter, as do the additional bitter ingredients found in some alcoholic beverages including hops in beer and gentiana in bitters. Quinine is also known for its bitter taste and is found in tonic water.

Bitterness is of interest to those who study evolution, as well as various health researchers since a large number of natural bitter compounds are known to be toxic. The ability to detect bitter-tasting, toxic compounds at low thresholds is considered to provide an important protective function. Plant leaves often contain toxic compounds, and among leaf-eating primates there is a tendency to prefer immature leaves, which tend to be higher in protein and lower in fiber and poisons than mature leaves. Amongst humans, various food processing techniques are used worldwide to detoxify otherwise inedible foods and make them palatable. Furthermore, the use of fire, changes in diet, and avoidance of toxins has led to neutral evolution in human bitter sensitivity. This has allowed several loss of function mutations that has led to a reduced sensory capacity towards bitterness in humans when compared to other species.

The threshold for stimulation of bitter taste by quinine averages a concentration of 8 μM (8 micromolar). The taste thresholds of other bitter substances are rated relative to quinine, which is thus given a reference index of 1. For example, brucine has an index of 11, is thus perceived as intensely more bitter than quinine, and is detected at a much lower solution threshold. The most bitter natural substance is amarogentin a compound present in the roots of the plant gentiana lutea and the most bitter substance known is the synthetic chemical denatonium, which has an index of 1,000. It is used as an aversive agent (a bitterant) that is added to toxic substances to prevent accidental ingestion. It was discovered accidentally in 1958 during research on a local anesthetic, by MacFarlan Smith of Gorgie, Edinburgh, Scotland.

Research has shown that TAS2Rs (taste receptors, type 2, also known as T2Rs) such as TAS2R38 coupled to the G protein gustducin are responsible for the human ability to taste bitter substances. They are identified not only by their ability to taste for certain "bitter" ligands, but also by the morphology of the receptor itself (surface bound, monomeric). The TAS2R family in humans is thought to comprise about 25 different taste receptors, some of which can recognize a wide variety of bitter-tasting compounds. Over 670 bitter-tasting compounds have been identified, on a bitter database, of which over 200 have been assigned to one or more specific receptors. Recently it is speculated that the selective constraints on the TAS2R family have been weakened due to the relatively high rate of mutation and pseudogenization. Researchers use two synthetic substances, phenylthiocarbamide (PTC) and 6-n-propylthiouracil (PROP) to study the genetics of bitter perception. These two substances taste bitter to some people, but are virtually tasteless to others. Among the tasters, some are so-called "supertasters" to whom PTC and PROP are extremely bitter. The variation in sensitivity is determined by two common alleles at the TAS2R38 locus. This genetic variation in the ability to taste a substance has been a source of great interest to those who study genetics.

Gustducin is made of three subunits. When it is activated by the GPCR, its subunits break apart and activate phosphodiesterase, a nearby enzyme, which in turn converts a precursor within the cell into a secondary messenger, which closes potassium ion channels.[citation needed] Also, this secondary messenger can stimulate the endoplasmic reticulum to release Ca2+ which contributes to depolarization. This leads to a build-up of potassium ions in the cell, depolarization, and neurotransmitter release. It is also possible for some bitter tastants to interact directly with the G protein, because of a structural similarity to the relevant GPCR.

Savoriness
Main article: Umami
Savory, or savoriness is an appetitive taste and is occasionally described by its Japanese name, umami or "meaty". It can be tasted in cheese and soy sauce. A loanword from Japanese meaning "good flavor" or "good taste", umami (旨味) is considered fundamental to many Asian cuisines and dates back to the Romans' deliberate use of fermented fish sauce (also called garum).

Umami was first studied in 1907 by isolating its dashi taste called ajinomoto, Japanese for "at the origin of flavor", later identified as the chemical monosodium glutamate (MSG). MSG is a sodium salt that produces a strong savory taste, especially combined with foods rich in nucleotides such as meats, fish, nuts, and mushrooms.

Some savory taste buds respond specifically to glutamate in the same way that "sweet" ones respond to sugar. Glutamate binds to a variant of G protein coupled glutamate receptors. L-glutamate may bond to a type of GPCR known as a metabotropic glutamate receptor (mGluR4) which causes the G-protein complex to activate the sensation of umami.

In the human body a stimulus refers to a form of energy which elicits a physiological or psychological action or response. Sensory receptors are the structures in the body which change the stimulus from one form of energy to another. This can mean changing the presence of a chemical, sound wave, source of heat, or touch to the skin into an electrical action potential which can be understood by the brain, the body's control center. Sensory receptors are modified ends of sensory neurons; modified to deal with specific types of stimulus, thus there are many different types of sensory receptors in the body. The neuron is the primary component of the nervous system, which transmits messages from sensory receptors all over the body.

Taste is a form of chemoreception which occurs in the specialised taste receptors in the mouth. To date, there are five different types of taste these receptors can detect which are recognized: salt, sweet, sour, bitter, and umami. Each type of receptor has a different manner of sensory transduction: that is, of detecting the presence of a certain compound and starting an action potential which alerts the brain. It is a matter of debate whether each taste cell is tuned to one specific tastant or to several; Smith and Margolskee claim that "gustatory neurons typically respond to more than one kind of stimulus, [a]lthough each neuron responds most strongly to one tastant". Researchers[who?] believe that the brain interprets complex tastes by examining patterns from a large set of neuron responses. This enables the body to make "keep or spit out" decisions when there is more than one tastant present. "No single neuron type alone is capable of discriminating among stimuli or different qualities, because a given cell can respond the same way to disparate stimuli."[citation needed] As well, serotonin is thought to act as an intermediary hormone which communicates with taste cells within a taste bud, mediating the signals being sent to the brain. Receptor molecules are found on the top of microvilli of the taste cells.

Sweetness
Sweetness is produced by the presence of sugars, some proteins, and other substances such as alcohols like anethol, glycerol and propylene glycol, saponins such as glycyrrhizin, artificial sweeteners (organic compounds with a variety of structures), and lead compounds such as lead acetate.[citation needed] It is often connected to aldehydes and ketones, which contain a carbonyl group.[citation needed] Many foods can be perceived as sweet despite of the sugar content, alcoholic drinks can taste sweet despite of having sugar or not, some plants such as liquorice, anise or stevia are sometimes used as sweeteners. Rebaudioside A is a steviol glycoside coming from stevia that is 200 times sweeter than sugar. Lead acetate and other lead compounds were used as sweeteners, mostly for wine, until lead poisoning became known. Romans used to deliberately boil the must inside of lead vessels to make a sweeter wine. Sweetness is detected by a variety of G protein-coupled receptors coupled to a G protein that acts as an intermediary in the communication between taste bud and brain, gustducin. These receptors are T1R2+3 (heterodimer) and T1R3 (homodimer), which account for sweet sensing in humans and other animals.

Saltiness
Saltiness is a taste produced best by the presence of cations (such as Na+
, K+
 or Li+
) and is directly detected by cation influx into glial like cells via leak channels causing depolarisation of the cell.

Other monovalent cations, e.g., ammonium, NH+
4, and divalent cations of the alkali earth metal group of the periodic table, e.g., calcium, Ca2+
, ions, in general, elicit a bitter rather than a salty taste even though they, too, can pass directly through ion channels in the tongue.[citation needed]

Sourness
Sourness is acidity, and, like salt, it is a taste sensed using ion channels. Undissociated acid diffuses across the plasma membrane of a presynaptic cell, where it dissociates in accordance with Le Chatelier's principle. The protons that are released then block potassium channels, which depolarise the cell and cause calcium influx. In addition, the taste receptor PKD2L1 has been found to be involved in tasting sour.

Bitterness
Research has shown that TAS2Rs (taste receptors, type 2, also known as T2Rs) such as TAS2R38 are responsible for the human ability to taste bitter substances. They are identified not only by their ability to taste certain bitter ligands, but also by the morphology of the receptor itself (surface bound, monomeric).

Savoriness
The amino acid glutamic acid is responsible for savoriness, but some nucleotides (inosinic acid and guanylic acid) can act as complements, enhancing the taste.

Glutamic acid binds to a variant of the G protein-coupled receptor, producing a savory taste.

Further sensations and transmission
The tongue can also feel other sensations not generally included in the basic tastes. These are largely detected by the somatosensory system. In humans, the sense of taste is conveyed via three of the twelve cranial nerves. The facial nerve (VII) carries taste sensations from the anterior two thirds of the tongue, the glossopharyngeal nerve (IX) carries taste sensations from the posterior one third of the tongue while a branch of the vagus nerve (X) carries some taste sensations from the back of the oral cavity.

The trigeminal nerve (cranial nerve V) provides information concerning the general texture of food as well as the taste-related sensations of peppery or hot (from spices).


The glossopharyngeal nerve innervates a third of the tongue including the circumvallate papillae. The facial nerve innervates the other two thirds of the tongue and the cheek via the chorda tympani.

The pterygopalatine ganglia are ganglia (one on each side) of the soft palate. The greater petrosal, lesser palatine and zygomatic nerves all synapse here. The greater petrosal, carries soft palate taste signals to the facial nerve. The lesser palatine sends signals to the nasal cavity; which is why spicy foods cause nasal drip. The zygomatic sends signals to the lacrimal nerve that activate the lacrimal gland; which is the reason that spicy foods can cause tears. Both the lesser palatine and the zygomatic are maxillary nerves (from the trigeminal nerve).

The special visceral afferents of the vagus nerve carry taste from the epiglottal region of the tongue.

The lingual nerve (trigeminal, not shown in diagram) is deeply interconnected with chorda tympani in that it provides all other sensory info from the ⅔ of the tongue. This info is processed separately (nearby) in rostal lateral subdivision of nucleus of the solitary tract (NST).

NST receives input from the amygdala (regulates oculomotor nuclei output), bed nuclei of stria terminalis, hypothalamus, and prefrontal cortex. NST is the topographical map that processes gustatory and sensory (temp, texture, etc.) info.

Reticular formation (includes Raphe nuclei responsible for serotonin production) is signaled to release serotonin during and after a meal to suppress appetite. Similarly, salivary nuclei are signaled to decrease saliva secretion.

Hypoglossal and thalamic connections aid in oral-related movements.

Hypothalamus connections hormonally regulate hunger and the digestive system.

Substantia innominata connects the thalamus, temporal lobe, and insula.

Edinger-Westphal nucleus reacts to taste stimuli by dilating and constricting the pupils.

Spinal ganglion are involved in movement.

The frontal operculum is speculated to be the memory and association hub for taste.[citation needed]

The insula cortex aids in swallowing and gastric motility.


