# The Motor System

The motor system is the set of central and peripheral structures in the nervous system that support motor functions, i.e. movement. Peripheral structures may include skeletal muscles and neural connections with muscle tissues. Central structures include cerebral cortex, brainstem, spinal cord, pyramidal system including the upper motor neurons, extrapyramidal system, cerebellum, and the lower motor neurons in the brainstem and the spinal cord.

## Pyramidal motor system

The pyramidal motor system, also called the pyramidal tract or the corticospinal tract, start in the motor center of the cerebral cortex. There are upper and lower motor neurons in the corticospinal tract. The motor impulses originate in the giant pyramidal cells or Betz cells of the motor area; i.e., precentral gyrus of cerebral cortex. These are the upper motor neurons (UMN) of the corticospinal tract. The axons of these cells pass in the depth of the cerebral cortex to the corona radiata and then to the internal capsule passing through the posterior branch of internal capsule and continue to descend in the midbrain and the medulla oblongata. In the lower part of Medulla oblongata 80 to 85% of these fibers decussate (pass to the opposite side) and descend in the white matter of the lateral funiculus of the spinal cord on the opposite side. The remaining 15 to 20% pass to the same side. Fibers for the extremities (limbs) pass 100% to the opposite side. The fibers of the corticospinal tract terminate at different levels in the anterior horn of the grey matter of the spinal cord. Here the lower motor neurons (LMN) of the corticospinal cord are located. Peripheral motor nerves carry the motor impulses from the anterior horn to the voluntary muscles.

The pyramidal tracts include both the corticobulbar tract and the corticospinal tract. These are aggregations of efferent nerve fibers from the upper motor neurons that travel from the cerebral cortex and terminate either in the brainstem (corticobulbar) or spinal cord (corticospinal) and are involved in the control of motor functions of the body.

The corticobulbar tract conducts impulses from the brain to the cranial nerves. These nerves control the muscles of the face and neck and are involved in facial expression, mastication, swallowing, and other functions.

The corticospinal tract conducts impulses from the brain to the spinal cord. It is made up of a lateral and anterior tract. The corticospinal tract is involved in voluntary movement. The majority of fibres of the corticospinal tract cross over in the medulla oblongata, resulting in muscles being controlled by the opposite side of the brain. The corticospinal tract also contains the axons of Betz cells (the largest pyramidal cells) located in the primary motor cortex.

The pyramidal tracts are named because they pass through the pyramids of the medulla oblongata. The corticospinal fibers when descending from the internal capsule to the brain stem, converge to a point from multiple directions giving the impression of an inverted pyramid.

The myelination of the pyramidal fibres is incomplete at birth and gradually progresses in cranio-caudal direction and thereby progressively gaining functionality. Most of the myelination is complete by two years of age and thereafter it progresses very slowly in cranio-caudal direction up to twelve years of age.


The term pyramidal tracts refers to upper motor neurons that originate in the cerebral cortex and terminate in the spinal cord (corticospinal) or brainstem (corticobulbar). Nerves emerge in the cerebral cortex, pass down and may cross sides in the medulla oblongata, and travel as part of the spinal cord until they synapse with interneurons in the grey column of the spinal cord.

There is some variation in terminology. The pyramidal tracts definitively encompass the corticospinal tracts, and many authors also include the corticobulbar tracts.

Corticospinal tract
Further information: Corticospinal tract
Nerve fibres in the corticospinal tract originate from pyramidal cells in layer V of the cerebral cortex. Fibres arise from the primary motor cortex (about 30%), supplementary motor area and the premotor cortex (together also about 30%), and the somatosensory cortex, parietal lobe, and cingulate gyrus supplies the rest. The cells have their bodies in the cerebral cortex, and the axons form the bulk of the pyramidal tracts. The nerve axons travel from the cortex through the posterior limb of internal capsule, through the cerebral peduncle and into the brainstem and anterior medulla oblongata. Here they form two prominences called the medulla oblongatary pyramids. Below the prominences, the majority of axons cross over to the opposite side from which they originated, known as decussation. The axons that cross over move to the outer part of the medulla oblongata and form the lateral corticospinal tract, whereas the fibres that remain form the anterior corticospinal tract. About 80% of axons cross over and form the lateral corticospinal tract; 10% do not cross over and join the tract, and 10% of fibres travel in the anterior corticospinal tract.[citation needed]

The nerve axons traveling down the tract are the efferent nerve fibers of the upper motor neurons. These axons travel down the tracts in the white matter of the spinal cord until they reach the vertebral level of the muscle that they will innervate. At this point, the axons synapse with lower motor neurons. The majority of axons do not directly synapse with lower motor neurons, but instead synapse with an interneuron that then synapses with a lower motor neuron. This generally occurs in the anterior grey column. Nerve axons of the lateral corticospinal tract that did not cross over in the medulla oblongata do so at the level of the spinal cord they terminate in.

These tracts contain more than 1 million axons and the majority of the axons are myelinated. The corticospinal tracts myelinate largely during the first and second years after birth. The majority of nerve axons are small (<4μm) in diameter. About 3% of nerve axons have a much larger diameter (16μm) and arise from Betz cells, mostly in the leg area of the primary motor cortex. These cells are notable because of their rapid conduction rate, over 70m/sec, the fastest conduction of any signals from the brain to the spinal cord.


Horizontal section through the lower part of the pons, showing the fibers of the corticospinal tract (#19) passing through the pontine nuclei
Corticobulbar tract
Further information: Corticobulbar tract
Fibres from the ventral motor cortex travel with the corticospinal tract through the internal capsule, but terminate in a number of locations in the midbrain (cortico-mesencephalic tract), pons (Corticopontine tract), and medulla oblongata (cortico-bulbar tract). The upper motor neurons of the corticobulbar tract synapse with interneurons or directly with the lower motor neurons located in the motor cranial nerve nuclei, namely oculomotor, trochlear, motor nucleus of the trigeminal nerve, abducens, facial nerve and accessory and in the nucleus ambiguus to the hypoglossal, vagus and accessory nerves. These nuclei are supplied by nerves from both sides of the brain, with the exception of the parts of the facial nerve that control muscles of the lower face. These muscles are only innervated by nerves from the contralateral (opposite) side of the cortex.

Function
The nerves within the corticospinal tract are involved in movement of muscles of the body. Because of the crossing-over of fibres, muscles are supplied by the side of the brain opposite to that of the muscle. The nerves within the corticobulbar tract are involved in movement in muscles of the head. They are involved in swallowing, phonation, and movements of the tongue. By virtue of involvement with the facial nerve, the corticobulbar tract is also responsible for transmitting facial expression. With the exception of lower muscles of facial expression, all functions of the corticobulbar tract involve inputs from both sides of the brain.


## Extrapyramidal motor system

The extrapyramidal motor system consists of motor-modulation systems, particularly the basal ganglia and cerebellum. The system is called extrapyramidal to distinguish it from the tracts of the motor cortex that reach their targets by traveling through the pyramids of the medulla. The pyramidal tracts (corticospinal tract and corticobulbar tracts) may directly innervate motor neurons of the spinal cord or brainstem (anterior (ventral) horn cells or certain cranial nerve nuclei), whereas the extrapyramidal system centers on the modulation and regulation (indirect control) of anterior (ventral) horn cells.

Extrapyramidal tracts are chiefly found in the reticular formation of the pons and medulla, and target lower motor neurons in the spinal cord that are involved in reflexes, locomotion, complex movements, and postural control. These tracts are in turn modulated by various parts of the central nervous system, including the nigrostriatal pathway, the basal ganglia, the cerebellum, the vestibular nuclei, and different sensory areas of the cerebral cortex. All of these regulatory components can be considered part of the extrapyramidal system, in that they modulate motor activity without directly innervating motor neurons.

The extrapyramidal tracts include parts of the following:

* rubrospinal tract
* pontine reticulospinal tract
* medullary reticulospinal tract
* lateral vestibulospinal tract
* tectospinal tract

## The Basal Ganglia

The basal ganglia (or basal nuclei) are a group of subcortical nuclei, of varied origin, in the brains of vertebrates, including humans, which are situated at the base of the forebrain and top of the midbrain. There are some differences in the basal ganglia of primates. Basal ganglia are strongly interconnected with the cerebral cortex, thalamus, and brainstem, as well as several other brain areas. The basal ganglia are associated with a variety of functions, including control of voluntary motor movements, procedural learning, habit learning, eye movements, cognition, and emotion.

The nomenclature of the basal ganglia system and its components has always been problematic. Early anatomists, seeing the macroscopic anatomical structure but knowing nothing of the cellular architecture or neurochemistry, grouped together components that are now believed to have distinct functions (such as the internal and external segments of the globus pallidus), and gave distinct names to components that are now thought to be functionally parts of a single structure (such as the caudate nucleus and putamen).

The term "basal" comes from the fact that most of its elements are located in the basal part of the forebrain. The term ganglia is a misnomer: In modern usage, neural clusters are called "ganglia" only in the peripheral nervous system; in the central nervous system they are called "nuclei". For this reason, the basal ganglia are also occasionally known as the "basal nuclei". 

The main components of the basal ganglia – as defined functionally – are the striatum; both dorsal striatum (caudate nucleus and putamen) and ventral striatum (nucleus accumbens and olfactory tubercle), globus pallidus, ventral pallidum, substantia nigra, and subthalamic nucleus. Each of these components has a complex internal anatomical and neurochemical organization. The largest component, the striatum (dorsal and ventral), receives input from many brain areas beyond the basal ganglia, but only sends output to other components of the basal ganglia. The pallidum receives input from the striatum, and sends inhibitory output to a number of motor-related areas. The substantia nigra is the source of the striatal input of the neurotransmitter dopamine, which plays an important role in basal ganglia function. The subthalamic nucleus receives input mainly from the striatum and cerebral cortex, and projects to the globus pallidus.

Popular theories implicate the basal ganglia primarily in action selection – in helping to decide which of several possible behaviors to execute at any given time. In more specific terms, the basal ganglia's primary function is likely to control and regulate activities of the motor and premotor cortical areas so that voluntary movements can be performed smoothly. Experimental studies show that the basal ganglia exert an inhibitory influence on a number of motor systems, and that a release of this inhibition permits a motor system to become active. The "behavior switching" that takes place within the basal ganglia is influenced by signals from many parts of the brain, including the prefrontal cortex, which plays a key role in executive functions.

The basal ganglia are of major importance for normal brain function and behaviour. Their dysfunction results in a wide range of neurological conditions including disorders of behaviour control and movement. Those of behaviour include Tourette syndrome, obsessive–compulsive disorder, and addiction. Movement disorders include, most notably Parkinson's disease, which involves degeneration of the dopamine-producing cells in the substantia nigra, Huntington's disease, which primarily involves damage to the striatum, dystonia, and more rarely hemiballismus. The basal ganglia have a limbic sector whose components are assigned distinct names: the nucleus accumbens, ventral pallidum, and ventral tegmental area (VTA). There is considerable evidence that this limbic part plays a central role in reward learning as well as cognition and frontal lobe functioning, via the mesolimbic pathway from the VTA to the nucleus accumbens that uses the neurotransmitter dopamine, and the mesocortical pathway. A number of highly addictive drugs, including cocaine, amphetamine, specific medications that are prescribed by a doctor, and nicotine, are thought to work by increasing the efficacy of this dopamine signal. There is also evidence implicating overactivity of the VTA dopaminergic projection in schizophrenia.

The basal ganglia form a fundamental component of the cerebrum. In contrast to the cortical layer that lines the surface of the forebrain, the basal ganglia are a collection of distinct masses of gray matter lying deep in the brain not far from the junction of the thalamus. They lie to the side of and surround the thalamus. Like most parts of the brain, the basal ganglia consist of left and right sides that are virtual mirror images of each other.

In terms of anatomy, the basal ganglia are divided into four distinct structures, depending on how superior or rostral they are (in other words depending on how close to the top of the head they are): Two of them, the striatum and the pallidum, are relatively large; the other two, the substantia nigra and the subthalamic nucleus, are smaller. In the illustration to the right, two coronal sections of the human brain show the location of the basal ganglia components. Of note, and not seen in this section, the subthalamic nucleus and substantia nigra lie farther back (posteriorly) in the brain than the striatum and pallidum.

### Striatum

The striatum is a subcortical structure generally divided into the dorsal striatum and ventral striatum, although a medial lateral classification has been suggested to be more relevant behaviorally and is being more widely used.

The striatum is composed mostly of medium spiny neurons. These GABAergic neurons project to the external (lateral) globus pallidus and internal (medial) globus pallidus as well as the substantia nigra pars reticulata. The projections into the globus pallidus and substantia nigra are primarily dopaminergic, although enkephalin, dynorphin and substance P are expressed. The striatum also contains interneurons that are classified into nitrergic neurons (due to use of nitric oxide as a neurotransmitter), tonically active[clarification needed] cholinergic interneurons, parvalbumin-expressing neurons and calretinin-expressing neurons. The dorsal striatum receives significant glutamatergic inputs from the cortex, as well as dopaminergic inputs from the substantia nigra pars compacta. The dorsal striatum is generally considered to be involved in sensorimotor activities. The ventral striatum receives glutamatergic inputs from the limbic areas as well as dopaminergic inputs from the VTA, via the mesolimbic pathway. The ventral striatum is believed to play a role in reward and other limbic functions. The dorsal striatum is divided into the caudate and putamen by the internal capsule while the ventral striatum is composed of the nucleus accumbens and olfactory tubercle. The caudate has three primary regions of connectivity, with the head of the caudate demonstrating connectivity to the prefrontal cortex, cingulate cortex and amygdala. The body and tail show differentiation between the dorsolateral rim and ventral caudate, projecting to the sensorimotor and limbic regions of the striatum respectively. Striatopallidal fibres connect the striatum to the pallidus.

### Pallidum

The pallidum consists of a large structure called the globus pallidus ("pale globe") together with a smaller ventral extension called the ventral pallidum. The globus pallidus appears as a single neural mass, but can be divided into two functionally distinct parts, called the internal (or medial) and external (lateral) segments, abbreviated GPi and GPe. Both segments contain primarily GABAergic neurons, which therefore have inhibitory effects on their targets. The two segments participate in distinct neural circuits. The GPe receives input mainly from the striatum, and projects to the subthalamic nucleus. The GPi receives signals from the striatum via the "direct" and "indirect" pathways. Pallidal neurons operate using a disinhibition principle. These neurons fire at steady high rates in the absence of input, and signals from the striatum cause them to pause or reduce their rate of firing. Because pallidal neurons themselves have inhibitory effects on their targets, the net effect of striatal input to the pallidum is a reduction of the tonic inhibition exerted by pallidal cells on their targets (disinhibition) with an increased rate of firing in the targets.

### Substantia nigra

The substantia nigra is a midbrain gray matter portion of the basal ganglia that has two parts – the pars compacta (SNc) and the pars reticulata (SNr). SNr often works in unison with GPi, and the SNr-GPi complex inhibits the thalamus. Substantia nigra pars compacta (SNc) however, produces the neurotransmitter dopamine, which is very significant in maintaining balance in the striatal pathway. The circuit portion below explains the role and circuit connections of each of the components of the basal ganglia.

The substantia nigra (SN) is a basal ganglia structure located in the midbrain that plays an important role in reward and movement. Substantia nigra is Latin for "black substance", reflecting the fact that parts of the substantia nigra appear darker than neighboring areas due to high levels of neuromelanin in dopaminergic neurons. It was discovered in 1784 by Félix Vicq-d'Azyr, and Samuel Thomas von Sömmerring alluded to this structure in 1791. Parkinson's disease is characterized by the loss of dopaminergic neurons in the substantia nigra pars compacta.

Although the substantia nigra appears as a continuous band in brain sections, anatomical studies have found that it actually consists of two parts with very different connections and functions: the pars compacta (SNpc) and the pars reticulata (SNpr). This classification was first proposed by Sano in 1910. The pars compacta serves mainly as an output to the basal ganglia circuit, supplying the striatum with dopamine. The pars reticulata, though, serves mainly as an input, conveying signals from the basal ganglia to numerous other brain structures.

The substantia nigra is an important player in brain function, in particular, in eye movement, motor planning, reward-seeking, learning, and addiction. Many of the substantia nigra's effects are mediated through the striatum. The nigral dopaminergic input to the striatum via the nigrostriatal pathway is intimately linked with the striatum's function. The co-dependence between the striatum and substantia nigra can be seen in this way: when the substantia nigra is electrically stimulated, no movement occurs; however, the symptoms of nigral degeneration due to Parkinson's is a poignant example of the substantia nigra's influence on movement. In addition to striatum-mediated functions, the substantia nigra also serves as a major source of GABAergic inhibition to various brain targets.

The substantia nigra is critical in the development of many diseases and syndromes, including parkinsonism and Parkinson's disease.
Parkinson's disease is a neurodegenerative disease characterized, in part, by the death of dopaminergic neurons in the SNpc. The major symptoms of Parkinson's disease include tremor, akinesia, bradykinesia, and stiffness. Other symptoms include disturbances to posture, fatigue, sleep abnormalities, and depressed mood. The cause of death of dopaminergic neurons in the SNpc is unknown. The substantia nigra is the target of chemical therapeutics for the treatment of Parkinson's disease. Levodopa (commonly referred to as L-DOPA), the dopamine precursor, is the most commonly prescribed medication for Parkinson's disease, despite controversy concerning the neurotoxicity of dopamine and L-DOPA. The drug is especially effective in treating patients in the early stages of Parkinson's, although it does lose its efficacy over time. Levodopa can cross the blood–brain barrier and increases dopamine levels in the substantia nigra, thus alleviating the symptoms of Parkinson's disease. The drawback of levodopa treatment is that it treats the symptoms of Parkinson's (low dopamine levels), rather than the cause (the death of dopaminergic neurons in the substantia nigra).

### Subthalamic nucleus

The subthalamic nucleus is a diencephalic gray matter portion of the basal ganglia, and the only portion of the ganglia that produces an excitatory neurotransmitter, glutamate. The role of the subthalamic nucleus is to stimulate the SNr-GPi complex and it is part of the indirect pathway. The subthalamic nucleus receives inhibitory input from the external part of the globus pallidus and sends excitatory input to the GPi.

