# The Somatic Sensory System

The somatic sensory system is a part of the sensory nervous system. The somatosensory system is a complex system of sensory neurons and neural pathways that responds to changes at the surface or inside the body. The axons (as afferent nerve fibers) of sensory neurons connect with, or respond to, various receptor cells. These sensory receptor cells are activated by different stimuli such as heat and nociception, giving a functional name to the responding sensory neuron, such as a thermoreceptor which carries information about temperature changes. Other types include mechanoreceptors, chemoreceptors, and nociceptors which send signals along a sensory nerve to the spinal cord where they may be processed by other sensory neurons and then relayed to the brain for further processing. Sensory receptors are found all over the body including the skin, epithelial tissues, muscles, bones and joints, internal organs, and the cardiovascular system.

Somatic senses are sometimes referred to as somesthetic senses, with the understanding that somesthesis includes the sense of touch, proprioception (sense of position and movement), and (depending on usage) haptic perception.

The mapping of the body surfaces in the brain is called somatotopy. In the cortex, it is also referred to as the cortical homunculus. This brain-surface ("cortical") map is not immutable, however. Dramatic shifts can occur in response to stroke or injury.

Peripheral neuropathy, often shortened to neuropathy, is a general term describing disease affecting the peripheral nerves, meaning nerves beyond the brain and spinal cord. Damage to peripheral nerves may impair sensation, movement, gland or organ function depending on which nerves are affected; in other words, neuropathy affecting motor, sensory, or autonomic nerves result in different symptoms. More than one type of nerve may be affected simultaneously. Peripheral neuropathy may be acute (with sudden onset, rapid progress) or chronic (symptoms begin subtly and progress slowly), and may be reversible or permanent. Paresthesia is an abnormal sensation of the skin (tingling, pricking, chilling, burning, numbness) with no apparent physical cause. Paresthesia may be transient or chronic, and may have any of dozens of possible underlying causes. Paresthesias are usually painless and can occur anywhere on the body, but most commonly occur in the arms and legs.

## Sensory Receptors

The four mechanoreceptors in the skin each respond to different stimuli for short or long periods.

Merkel cell nerve endings are found in the basal epidermis and hair follicles; they react to low vibrations (5–15 Hz) and deep static touch such as shapes and edges. Due to having a small receptive field (extremely detailed info), they are used in areas like fingertips the most; they are not covered (shelled) and thus respond to pressures over long periods.

Tactile corpuscles react to moderate vibration (10–50 Hz) and light touch. They are located in the dermal papillae; due to their reactivity, they are primarily located in fingertips and lips. They respond in quick action potentials, unlike Merkel nerve endings. They are responsible for the ability to read Braille and feel gentle stimuli.

Lamellar corpuscles determine gross touch and distinguish rough and soft substances. They react in quick action potentials, especially to vibrations around 250 Hz (even up to centimeters away). They are the most sensitive to vibrations and have large receptor fields. Pacinian reacts only to sudden stimuli so pressures like clothes that are always compressing their shape are quickly ignored.

Bulbous corpuscles react slowly and respond to sustained skin stretch. They are responsible for the feeling of object slippage and play a major role in the kinesthetic sense and control of finger position and movement. Merkel and bulbous cells - slow-response - are myelinated; the rest - fast-response - are not. All of these receptors are activated upon pressures that squish their shape causing an action potential.

## The Somatosensory Pathways

All afferent touch/vibration info ascends the spinal cord via the posterior (dorsal) column-medial lemniscus pathway via gracilis (T7 and below) or cuneatus (T6 and above). Cuneatus sends signals to the cochlear nucleus indirectly via spinal grey matter, this info is used in determining if a perceived sound is just villi noise/irritation. All fibers cross (left becomes right) in the medulla.

A somatosensory pathway will typically have three neurons: first-order, second-order, and third-order.

The first-order neuron always has its cell body in the dorsal root ganglion of the spinal nerve (if sensation is in parts of the head or neck not covered by the cervical nerves, it will be the trigeminal nerve ganglia or the ganglia of other sensory cranial nerves).

The second-order neuron has its cell body either in the spinal cord or in the brainstem. This neuron's ascending axons will cross (decussate) to the opposite side either in the spinal cord or in the brainstem.
In the case of touch and certain types of pain, the third-order neuron has its cell body in the VPN of the thalamus and ends in the postcentral gyrus of the parietal lobe.

Photoreceptors, similar to those found in the retina of the eye, detect potentially damaging ultraviolet radiation (ultraviolet A specifically), inducing increased production of melanin by melanocytes. Thus tanning potentially offers the skin rapid protection from DNA damage and sunburn caused by ultraviolet radiation (DNA damage caused by ultraviolet B). However, whether this offers protection is debatable, because the amount of melanin released by this process is modest in comparison to the amounts released in response to DNA damage caused by ultraviolet B radiation.

The tactile feedback from proprioception is derived from the proprioceptors in the skin, muscles, and joints.

Balance

The receptor for the sense of balance resides in the vestibular system in the ear (for the three-dimensional orientation of the head, and by inference, the rest of the body). Balance is also mediated by the kinesthetic reflex fed by proprioception (which senses the relative location of the rest of the body to the head). In addition, proprioception estimates the location of objects which are sensed by the visual system (which provides confirmation of the place of those objects relative to the body), as input to the mechanical reflexes of the body.

Fine touch and crude touch

Fine touch (or discriminative touch) is a sensory modality that allows a subject to sense and localize touch. The form of touch where localization is not possible is known as crude touch. The posterior column–medial lemniscus pathway is the pathway responsible for the sending of fine touch information to the cerebral cortex of the brain.

Crude touch (or non-discriminative touch) is a sensory modality that allows the subject to sense that something has touched them, without being able to localize where they were touched (contrasting "fine touch"). Its fibres are carried in the spinothalamic tract, unlike the fine touch, which is carried in the dorsal column.  As fine touch normally works in parallel to crude touch, a person will be able to localize touch until fibres carrying fine touch (Posterior column–medial lemniscus pathway) have been disrupted. Then the subject will feel the touch, but be unable to identify where they were touched.

The somatosensory cortex encodes incoming sensory information from receptors all over the body. Affective touch is a type of sensory information that elicits an emotional reaction and is usually social in nature, such as a physical human touch. This type of information is actually coded differently than other sensory information. Intensity of affective touch is still encoded in the primary somatosensory cortex and is processed in a similar way to emotions invoked by sight and sound, as exemplified by the increase of adrenaline caused by the social touch of a loved one, as opposed to the physical inability to touch someone you don't love.

Meanwhile, the feeling of pleasantness associated with affective touch activates the anterior cingulate cortex more than the primary somatosensory cortex. Functional magnetic resonance imaging (fMRI) data shows that increased blood-oxygen-level contrast (BOLD) signal in the anterior cingulate cortex as well as the prefrontal cortex is highly correlated with pleasantness scores of an affective touch. Inhibitory transcranial magnetic stimulation (TMS) of the primary somatosensory cortex inhibits the perception of affective touch intensity, but not affective touch pleasantness. Therefore, the S1 is not directly involved in processing socially affective touch pleasantness, but still plays a role in discriminating touch location and intensity.

## The Primary Somatosensory Cortex

The primary somatosensory cortex is located in the postcentral gyrus, and is part of the somatosensory system. It was initially defined from surface stimulation studies of Wilder Penfield, and parallel surface potential studies of Bard, Woolsey, and Marshall. Although initially defined to be roughly the same as Brodmann areas 3, 1 and 2, more recent work by Kaas has suggested that for homogeny with other sensory fields only area 3 should be referred to as "primary somatosensory cortex", as it receives the bulk of the thalamocortical projections from the sensory input fields.

At the primary somatosensory cortex, tactile representation is orderly arranged (in an inverted fashion) from the toe (at the top of the cerebral hemisphere) to mouth (at the bottom). However, some body parts may be controlled by partially overlapping regions of cortex. Each cerebral hemisphere of the primary somatosensory cortex only contains a tactile representation of the opposite (contralateral) side of the body. The amount of primary somatosensory cortex devoted to a body part is not proportional to the absolute size of the body surface, but, instead, to the relative density of cutaneous tactile receptors on that body part. The density of cutaneous tactile receptors on a body part is generally indicative of the degree of sensitivity of tactile stimulation experienced at said body part. For this reason, the human lips and hands have a larger representation than other body parts.

Brodmann areas 3, 1, and 2 make up the primary somatosensory cortex of the human brain (or S1). Because Brodmann sliced the brain somewhat obliquely, he encountered area 1 first; however, from anterior to posterior, the Brodmann designations are 3, 1, and 2, respectively.

Brodmann area (BA) 3 is subdivided into areas 3a and 3b. Where BA 1 occupies the apex of the postcentral gyrus, the rostral border of BA 3a is in the nadir of the Central sulcus, and is caudally followed by BA 3b, then BA 1, with BA 2 following and ending in the nadir of the postcentral sulcus. BA 3b is now conceived as the primary somatosensory cortex because 1) it receives dense inputs from the NP nucleus of the thalamus; 2) its neurons are highly responsive to somatosensory stimuli, but not other stimuli; 3) lesions here impair somatic sensation; and 4) electrical stimulation evokes somatic sensory experience. BA 3a also receives dense input from the thalamus; however, this area is concerned with proprioception.

Areas 1 and 2 receive dense inputs from BA 3b. The projection from 3b to 1 primarily relays texture information; the projection to area 2 emphasizes size and shape. Lesions confined to these areas produce predictable dysfunction in texture, size, and shape discrimination.

Somatosensory cortex, like other neocortex, is layered. Like other sensory cortex (i.e., visual and auditory) the thalamic inputs project into layer IV, which in turn project into other layers. As in other sensory cortices, S1 neurons are grouped together with similar inputs and responses into vertical columns that extend across cortical layers (e.g., As shown by Vernon Mountcastle, into alternating layers of slowly adapting and rapidly adapting neurons; or spatial segmentation of the vibrissae on mouse/rat cerebral cortex).

This area of cortex, as shown by Wilder Penfield and others, is organized somatotopically, having the pattern of a homunculus. That is, the legs and trunk fold over the midline; the arms and hands are along the middle of the area shown here; and the face is near the bottom of the figure. While it is not well-shown here, the lips and hands are enlarged on a proper homunculus, since a larger number of neurons in the cerebral cortex are devoted to processing information from these areas.

These areas contain cells that project to the secondary somatosensory cortex.

## Proprioception

Proprioception is the sense of self-movement and body position. It is sometimes described as the "sixth sense".

Proprioception is mediated by proprioceptors, mechanosensory neurons located within muscles, tendons, and joints. There are multiple types of proprioceptors which are activated during distinct behaviors and encode distinct types of information: limb velocity and movement, load on a limb, and limb limits. Vertebrates and invertebrates have distinct but similar modes of encoding this information.

The central nervous system integrates proprioception and other sensory systems, such as vision and the vestibular system, to create an overall representation of body position, movement, and acceleration.

In vertebrates, limb velocity and movement (muscle length and the rate of change) are encoded by one group of sensory neurons (Type Ia sensory fiber) and another type encode static muscle length (Group II neurons). These two types of sensory neurons compose muscle spindles. There is a similar division of encoding in invertebrates; different subgroups of neurons of the Chordotonal organ encode limb position and velocity.

To determine the load on a limb, vertebrates use sensory neurons in the Golgi tendon organs: type Ib afferents. These proprioceptors are activated at given muscle forces, which indicate the resistance that muscle is experiencing. Similarly, invertebrates have a mechanism to determine limb load: the Campaniform sensilla. These proprioceptors are active when a limb experiences resistance.

A third role for proprioceptors is to determine when a joint is at a specific position. In vertebrates, this is accomplished by Ruffini endings and Pacinian corpuscles. These proprioceptors are activated when the joint is at a threshold, usually at the extremes of joint position. Invertebrates use hair plates to accomplish this; a row of bristles located along joints detect when the limb moves.

The sense of proprioception is ubiquitous across mobile animals and is essential for the motor coordination of the body. Proprioceptors can form reflex circuits with motor neurons to provide rapid feedback about body and limb position. These mechanosensory circuits are important for flexibly maintaining posture and balance, especially during locomotion. For example, consider the stretch reflex, in which stretch across a muscle is detected by a sensory receptor (e.g., muscle spindle, chordotonal neurons), which activates a motor neuron to induce muscle contraction and oppose the stretch. During locomotion, sensory neurons can reverse their activity when stretched, to promote rather than oppose movement.

In humans, a distinction is made between conscious proprioception and non-conscious proprioception:

Non-conscious proprioception is communicated primarily via the dorsal spinocerebellar tract and ventral spinocerebellar tract, to the cerebellum. A non-conscious reaction is seen in the human proprioceptive reflex, or righting reflex—in the event that the body tilts in any direction, the person will cock their head back to level the eyes against the horizon. This is seen even in infants as soon as they gain control of their neck muscles. This control comes from the cerebellum, the part of the brain affecting balance.

Proprioception is mediated by mechanically sensitive proprioceptor neurons distributed throughout an animal's body. Most vertebrates possess three basic types of proprioceptors: muscle spindles, which are embedded in skeletal muscle fibers, Golgi tendon organs, which lie at the interface of muscles and tendons, and joint receptors, which are low-threshold mechanoreceptors embedded in joint capsules. Many invertebrates, such as insects, also possess three basic proprioceptor types with analogous functional properties: chordotonal neurons, campaniform sensilla, and hair plates.

The initiation of proprioception is the activation of a proprioreceptor in the periphery. The proprioceptive sense is believed to be composed of information from sensory neurons located in the inner ear (motion and orientation) and in the stretch receptors located in the muscles and the joint-supporting ligaments (stance). There are specific nerve receptors for this form of perception termed "proprioreceptors", just as there are specific receptors for pressure, light, temperature, sound, and other sensory experiences. Proprioreceptors are sometimes known as adequate stimuli receptors. TRPN, a member of the transient receptor potential family of ion channels, has been found to be responsible for proprioception in fruit flies, nematode worms, African clawed frogs, and zebrafish. PIEZO2, a nonselective cation channel, has been shown to underlie the mechanosensitivity of proprioceptors in mice. The channel mediating human proprioceptive mechanosensation has yet to be discovered.

Proprioception of the head stems from the muscles innervated by the trigeminal nerve, where the GSA fibers pass without synapsing in the trigeminal ganglion (first-order sensory neuron), reaching the mesencephalic tract and the mesencephalic nucleus of trigeminal nerve.

Although it was known that finger kinesthesia relies on skin sensation, recent research has found that kinesthesia-based haptic perception relies strongly on the forces experienced during touch. This research allows the creation of "virtual", illusory haptic shapes with different perceived qualities.

An important role for proprioception is to allow an animal to stabilize itself against perturbations. For instance, for a person to walk or stand upright, they must continuously monitor their posture and adjust muscle activity as needed to provide balance. Similarly, when walking on unfamiliar terrain or even tripping, the person must adjust the output of their muscles quickly based on estimated limb position and velocity. Proprioceptor reflex circuits are thought to play an important role to allow fast and unconscious execution of these behaviors, To make control of these behaviors efficient, proprioceptors are also thought to regulate reciprocal inhibition in muscles, leading to agonist-antagonist muscle pairs.

When planning complex movements such as reaching or grooming, animals must consider the current position and velocity of their limb and use it to adjust dynamics to target a final position. If the animal's estimate of their limb's initial position is wrong, this can lead to a deficiency in the movement. Furthermore, proprioception is crucial in refining the movement if it deviates from the trajectory.

